-- Running in auto input_syntax mode. Trying TPTP
-- Refutation found. Thanks to Tanya!
-- Lean proof output generated by Vampire
import VampLean
section vamproof
universe u
set_option maxHeartbeats 400000000
set_option linter.all false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option maxRecDepth 1048576


variable {ι : Type u}
variable [inst : Inhabited ι]
variable {«_sK25» «_sK27» «_sK26» «_sK28» :  ι → ι → ι}
  {«_sK15» «_sK19» «_sK18» «_sK16» «_sK17» «_sK20» «_sK21» «_sK22» «_sK23» «_sK24» :  ι → ι}
  {«_sK12» «_sK13» «_sK14» «_sK10» «_sK11» «_sK9» : ι}
  {«_op_zE» «_op_zS» «_op_zT» «_yp_zS» «_yp_zT» :  ι → ι → Prop}
  {«_sP0» «_sP1» «_sP2» :  ι → Prop}
-- step 3 rectify
theorem inf_s3 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ (¬(¬(∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ («_op_zT» v0 v1)))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_op_zT» v0 v1))))) → (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_op_zT» v0 v1)))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ (¬(¬(∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22)))))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28) ∧ True))))))))) ∧ (∀ v29 : ι,(∀ v30 : ι,((∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34) ∧ True))))) → («_op_zT» v29 v30))))) → (∀ v35 : ι,(∀ v36 : ι,((∃ v37 : ι,(∃ v38 : ι,(∃ v39 : ι,(∃ v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40) ∧ True))))) → («_op_zT» v35 v36)))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 4 true and false elimination
theorem inf_s4 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ (¬(¬(∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22)))))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28) ∧ True))))))))) ∧ (∀ v29 : ι,(∀ v30 : ι,((∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34) ∧ True))))) → («_op_zT» v29 v30))))) → (∀ v35 : ι,(∀ v36 : ι,((∃ v37 : ι,(∃ v38 : ι,(∃ v39 : ι,(∃ v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40) ∧ True))))) → («_op_zT» v35 v36)))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (¬(¬(∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22)))))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))))))) ∧ (∀ v29 : ι,(∀ v30 : ι,((∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) → («_op_zT» v29 v30))))) → (∀ v35 : ι,(∀ v36 : ι,((∃ v37 : ι,(∃ v38 : ι,(∃ v39 : ι,(∃ v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40)))))) → («_op_zT» v35 v36)))))) := by
  intro h
  remove_tauto at h<;>
  first | exact h | grind

-- step 5 flattening
theorem inf_s5 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (¬(¬(∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22)))))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))))))) ∧ (∀ v29 : ι,(∀ v30 : ι,((∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) → («_op_zT» v29 v30))))) → (∀ v35 : ι,(∀ v36 : ι,((∃ v37 : ι,(∃ v38 : ι,(∃ v39 : ι,(∃ v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40)))))) → («_op_zT» v35 v36)))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 6 pure predicate removal
theorem inf_s6 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) := by
  grind

-- step 7 pure predicate removal
theorem inf_s7 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) := by
  grind

-- step 8 ennf transformation
theorem inf_s8 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((∃ v31 v32 v33 v34 : ι,((«_op_zT» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) → («_op_zT» v29 v30)))) → (∀ v35 v36 : ι,((∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))) → («_op_zT» v35 v36))))) →
  ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34)))))))) := by
  intros h
  ennf_transformation at h<;>
  exact h

-- step 9 flattening
theorem inf_s9 : ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34)))))))) →
  ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 26 nnf transformation
theorem inf_s26 : ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) →
  ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) := by
  intro h
  nnf_transformation at h<;>
  first | exact h | grind

-- step 27 flattening
theorem inf_s27 : ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) →
  ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 28 rectify
theorem inf_s28 : ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) →
  ((∃ v0 v1 : ι,((¬(«_op_zT» v0 v1)) ∧ (∃ v2 v3 v4 v5 : ι,((«_op_zT» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5))))) ∧ (∀ v6 : ι,((∃ v7 v8 : ι,((«_op_zE» v7 v8) ∧ (v6=v7))) ∨ (∃ v9 v10 : ι,((«_op_zE» v9 v10) ∧ (v6=v10))) ∨ (∃ v11 v12 : ι,((«_op_zS» v11 v12) ∧ (v6=v11))) ∨ («_sP2» v6) ∨ («_sP1» v6) ∨ («_sP0» v6) ∨ (∃ v13 : ι,(v6=v13)) ∨ (∃ v16 : ι,(v6=v16)) ∨ (∃ v17 : ι,(v6=v17)) ∨ (∃ v20 : ι,(v6=v20)))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ (∃ v29 v30 v31 v32 : ι,((«_op_zE» v29 v30) ∧ («_op_zT» v31 v32) ∧ (v30=v31) ∧ (v23=v29) ∧ (v24=v32))) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v33 v34 : ι,((«_op_zT» v33 v34) ∨ (∀ v35 v36 v37 v38 : ι,((¬(«_op_zT» v35 v36)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 70 definition unfolding
theorem inf_s70 : ((¬(«_op_zT» («_sK9») («_sK10»)))) →
  (((«_sK9»)=(«_sK11»))) →
  (((«_sK10»)=(«_sK14»))) →
  ((¬(«_op_zT» («_sK11») («_sK14»)))) := by
  intros h0 h1 h2
  have i0 := h0
  rewrite (occs := [1]) [h1] at i0
  rewrite (occs := [1]) [h2] at i0
  grind only
-- step 71 definition unfolding
theorem inf_s71 : ((«_op_zT» («_sK11») («_sK12»))) →
  (((«_sK12»)=(«_sK13»))) →
  ((«_op_zT» («_sK11») («_sK13»))) := by
  intros h0 h1
  have i0 := h0
  rewrite (occs := [1]) [h1] at i0
  grind only
-- step 75 equality resolution
theorem inf_s75 : (∀ v33 v34 v35 v36 v37 v38 : ι, («_op_zT» v33 v34) ∨ (¬(«_op_zT» v35 v36)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) →
  (∀ v33 v34 v35 v37 v38 : ι, («_op_zT» v33 v34) ∨ (¬(«_op_zT» v35 v37)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) := by
  intros h0 v33 v34 v35 v37 v38
  have i0 := h0 v33 v34 v35 v37 v37 v38
  grind only [cases Or]

-- step 76 equality resolution
theorem inf_s76 : (∀ v33 v34 v35 v37 v38 : ι, («_op_zT» v33 v34) ∨ (¬(«_op_zT» v35 v37)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) →
  (∀ v34 v35 v37 v38 : ι, («_op_zT» v35 v34) ∨ (¬(«_op_zT» v35 v37)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v34=v38))) := by
  intros h0 v34 v35 v37 v38
  have i0 := h0 v35 v34 v35 v37 v38
  grind only [cases Or]

-- step 77 equality resolution
theorem inf_s77 : (∀ v34 v35 v37 v38 : ι, («_op_zT» v35 v34) ∨ (¬(«_op_zT» v35 v37)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v34=v38))) →
  (∀ v35 v37 v38 : ι, (¬(«_op_zT» v37 v38)) ∨ (¬(«_op_zT» v35 v37)) ∨ («_op_zT» v35 v38)) := by
  intros h0 v35 v37 v38
  have i0 := h0 v38 v35 v37 v38
  grind only [cases Or]

-- step 84 resolution
theorem inf_s84 : (∀ v35 v37 v38 : ι, (¬(«_op_zT» v37 v38)) ∨ (¬(«_op_zT» v35 v37)) ∨ («_op_zT» v35 v38)) →
  ((«_op_zT» («_sK13») («_sK14»))) →
  (∀ v0 : ι, (¬(«_op_zT» v0 («_sK13»))) ∨ («_op_zT» v0 («_sK14»))) := by
  intros h0 h1 v0
  have i0 := h0 v0 («_sK13») («_sK14»)
  have i1 := h1
  grind only [cases Or]

-- step 234 resolution
theorem inf_s234 : (∀ v0 : ι, (¬(«_op_zT» v0 («_sK13»))) ∨ («_op_zT» v0 («_sK14»))) →
  ((«_op_zT» («_sK11») («_sK13»))) →
  ((«_op_zT» («_sK11») («_sK14»))) := by
  intros h0 h1
  have i0 := h0 («_sK11»)
  have i1 := h1
  grind only [cases Or]

-- step 236 forward subsumption resolution
theorem inf_s236 : ((«_op_zT» («_sK11») («_sK14»))) →
  ((¬(«_op_zT» («_sK11») («_sK14»)))) →
  False := by
  intros h0 h1
  have i0 := h0
  have i1 := h1
  grind only [cases Or]

theorem fullProof : (((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ (¬(¬(∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ («_op_zT» v0 v1)))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_op_zT» v0 v1))))) → (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_op_zT» v0 v1))))) := by

  apply Classical.byContradiction; intro step2
  have step3 := inf_s3  step2
  have step4 := inf_s4  step3
  have step5 := inf_s5  step4
  have step6 := inf_s6  step5
  have step7 := inf_s7  step6
  have step8 := inf_s8  step7
  have step9 := inf_s9  step8
  -- step10 predicate definition introduction
  let «_sP0» (v0: ι)  := (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))
  have step10 : (∀ v0 : ι,((∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (¬(«_sP0» v0)))) := by
    intros v0
    have s : (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ↔ «_sP0» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step11 predicate definition introduction
  let «_sP1» (v0: ι)  := (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))
  have step11 : (∀ v0 : ι,((∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (¬(«_sP1» v0)))) := by
    intros v0
    have s : (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ↔ «_sP1» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step12 predicate definition introduction
  let «_sP2» (v0: ι)  := (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))
  have step12 : (∀ v0 : ι,((∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (¬(«_sP2» v0)))) := by
    intros v0
    have s : (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ↔ «_sP2» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step13 definition folding
  have step13 := step9
  change ((∃ v35 v36 : ι,((¬(«_op_zT» v35 v36)) ∧ (∃ v37 v38 v39 v40 : ι,((«_op_zT» v37 v38) ∧ («_op_zT» v39 v40) ∧ (v38=v39) ∧ (v35=v37) ∧ (v36=v40))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ («_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))) ∧ (∀ v29 v30 : ι,((«_op_zT» v29 v30) ∨ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zT» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))))) at step13
  have step26 := inf_s26  step13
  have step27 := inf_s27  step26
  have step28 := inf_s28  step27
  -- step39 skolemisation
  exists_prenex at step28
  let ⟨«_sK9»,«_sK10»,«_sK15»,«_sK16»,«_sK11»,«_sK12»,«_sK13»,«_sK14»,«_sK17»,«_sK18»,«_sK19»,«_sK20»,«_sK21»,«_sK22»,«_sK23»,«_sK24»,«_sK25»,«_sK26»,«_sK27»,«_sK28»,step39'⟩ := step28
  have step39 : (((¬(«_op_zT» («_sK9») («_sK10»))) ∧ ((«_op_zT» («_sK11») («_sK12»)) ∧ («_op_zT» («_sK13») («_sK14»)) ∧ ((«_sK12»)=(«_sK13»)) ∧ ((«_sK9»)=(«_sK11»)) ∧ ((«_sK10»)=(«_sK14»)))) ∧ (∀ v6 : ι,(((«_op_zE» («_sK15» v6) («_sK16» v6)) ∧ ((«_sK15» v6)=v6)) ∨ ((«_op_zE» («_sK17» v6) («_sK18» v6)) ∧ ((«_sK18» v6)=v6)) ∨ ((«_op_zS» («_sK19» v6) («_sK20» v6)) ∧ ((«_sK19» v6)=v6)) ∨ («_sP2» v6) ∨ («_sP1» v6) ∨ («_sP0» v6) ∨ ((«_sK21» v6)=v6) ∨ ((«_sK22» v6)=v6) ∨ ((«_sK23» v6)=v6) ∨ ((«_sK24» v6)=v6))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ (¬(«_op_zT» v21 v22))) ∧ ((«_op_zT» v21 v22) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ ((«_op_zE» («_sK25» v23 v24) («_sK26» v23 v24)) ∧ («_op_zT» («_sK27» v23 v24) («_sK28» v23 v24)) ∧ ((«_sK26» v23 v24)=(«_sK27» v23 v24)) ∧ ((«_sK25» v23 v24)=v23) ∧ ((«_sK28» v23 v24)=v24)) ∨ (¬(«_op_zS» v23 v24))))) ∧ (∀ v33 v34 : ι,((«_op_zT» v33 v34) ∨ (∀ v35 v36 v37 v38 : ι,((¬(«_op_zT» v35 v36)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))))))) := by symm_match using step39'
  have step39' := by
    prenexify at step39
    cnfify at step39
    exact step39
  let ⟨s39c0, s39c1, s39c2, s39c3, s39c4, s39c5, s39c6, s39c7, s39c8, s39c9, s39c10, s39c11, s39c12, s39c13, s39c14, s39c15, s39c16, s39c17, s39c18, s39c19, s39c20, s39c21, s39c22, s39c23⟩ := step39'
  ac_nf0 at s39c0 s39c1 s39c2 s39c3 s39c4 s39c5 s39c6 s39c7 s39c8 s39c9 s39c10 s39c11 s39c12 s39c13 s39c14 s39c15 s39c16 s39c17 s39c18 s39c19 s39c20 s39c21 s39c22 s39c23
  have step46 : (∀ v33 v34 v35 v36 v37 v38 : ι, («_op_zT» v33 v34) ∨ (¬(«_op_zT» v35 v36)) ∨ (¬(«_op_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) := by
    try simp only
    ac_nf0
    assumption

  have step64 : (((«_sK10»)=(«_sK14»))) := by
    try simp only
    ac_nf0
    assumption

  have step65 : (((«_sK9»)=(«_sK11»))) := by
    try simp only
    ac_nf0
    assumption

  have step66 : (((«_sK12»)=(«_sK13»))) := by
    try simp only
    ac_nf0
    assumption

  have step67 : ((«_op_zT» («_sK13») («_sK14»))) := by
    try simp only
    ac_nf0
    assumption

  have step68 : ((«_op_zT» («_sK11») («_sK12»))) := by
    try simp only
    ac_nf0
    assumption

  have step69 : ((¬(«_op_zT» («_sK9») («_sK10»)))) := by
    try simp only
    ac_nf0
    assumption

  have step70 := inf_s70  step69 step65 step64
  have step71 := inf_s71  step68 step66
  have step75 := inf_s75  step46
  have step76 := inf_s76  step75
  have step77 := inf_s77  step76
  have step84 := inf_s84  step77 step67
  have step234 := inf_s234  step84 step71
  have step236 := inf_s236  step234 step70
  exact step236

end vamproof
-- ------------------------------
-- Version: Vampire 5.0.1 (Release build, commit a9e19dacc on 2026-09-07 00:00:00 +0000)
-- CaDiCaL version: 2.1.3
-- Termination reason: Refutation
-- ------------------------------
-- ------------------------------
