use super::*;

/// One complete emitted proof carrying the pinned global
/// `prenexify`/`cnfify` package, lifted verbatim out of
/// `Benchmark/Example0001/Certificate/VampireArtifacts/jobs/maint_clause_0/leancheck.lean`
/// (step 19 and its seven targets) around a minimal module frame. It
/// spells the import `VampLean.Runtime` so the legacy Python's own
/// canonicalization is the identity on it and the two implementations'
/// outputs are directly comparable; the emitter's `import VampLean`
/// spelling is equally accepted (see [`accepts_either_pinned_import`]).
const PROJECTION_INPUT: &str = include_str!("fixtures/projection_input.lean");
/// The legacy `rewrite_vamplean_projection_blocks` output on
/// [`PROJECTION_INPUT`], generated from `whiel_synth` and checked in as
/// the differential-parity reference.
const PROJECTION_REWRITTEN: &str = include_str!("fixtures/projection_rewritten.lean");

const JOB: &str = "maint_clause_0";

/// The kernel-SAT context these fixtures run under. Every one of them is a
/// `direct`-profile proof with no AVATAR refutation in it, so the step is
/// a recorded miss and the solver is never asked for a trace; a recorded
/// solver with no traces therefore stands in for the pinned CaDiCaL, and
/// would fail loudly if a fixture ever did carry a helper.
fn kernel_sat_context() -> lrat::RecordedLratSolver {
    lrat::RecordedLratSolver::new(Vec::new())
}

fn cadical_identity() -> serde_json::Value {
    serde_json::json!({ "kind": "test_recorded_lrat_solver" })
}

fn transformed(raw: &str) -> TransformedProof {
    let solver = kernel_sat_context();
    let context = KernelSatContext::new(&solver, cadical_identity());
    apply_proof_transforms(JOB, raw, &context).expect("the fixture is a recognized proof shape")
}

fn projection_record(proof: &TransformedProof) -> &ProofTransformRecord {
    proof
        .transforms
        .iter()
        .find(|record| record.id == ProofTransformId::ClauseProjection)
        .expect("the projection step always runs")
}

// ------------------------------------------------------------
// Differential Parity
// ------------------------------------------------------------

#[test]
fn reproduces_the_legacy_projection_rewrite_byte_for_byte() {
    let proof = transformed(PROJECTION_INPUT);
    assert_eq!(proof.transformed, PROJECTION_REWRITTEN);
}

#[test]
fn records_the_projected_steps_of_the_reference_shape() {
    let proof = transformed(PROJECTION_INPUT);
    let record = projection_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Applied);
    assert_eq!(record.detail["blocks"], 1);
    assert_eq!(record.detail["projections"], 7);
    assert_eq!(record.detail["step_ids"], serde_json::json!([19]));
    assert_eq!(
        record.detail["projected_step_ids"],
        serde_json::json!([[47, 48, 49, 50, 51, 52, 53]])
    );
    assert_eq!(record.detail["missed_step_ids"], serde_json::json!([]));
}

#[test]
fn asks_for_the_clause_projection_import_only_when_it_rewrote_something() {
    let proof = transformed(PROJECTION_INPUT);
    assert_eq!(proof.extra_imports, vec![CLAUSE_PROJECTION_IMPORT]);

    let untouched =
        transformed(&PROJECTION_INPUT.replace("  have step19' := by", "  have step19'"));
    assert!(untouched.extra_imports.is_empty());
}

#[test]
fn is_idempotent_on_an_already_rewritten_proof() {
    let once = transformed(PROJECTION_INPUT);
    let twice = transformed(&once.transformed);
    assert_eq!(twice.transformed, once.transformed);
    let record = projection_record(&twice);
    // The block is recognized again from its generated tactic groups, so
    // the receipt reconstructs the same metadata.
    assert_eq!(record.detail["step_ids"], serde_json::json!([19]));
    assert_eq!(record.outcome, ProofTransformOutcome::Applied);
}

#[test]
fn accepts_either_pinned_import() {
    let emitter_spelling = PROJECTION_INPUT.replace("import VampLean.Runtime", "import VampLean");
    let proof = transformed(&emitter_spelling);
    assert_eq!(
        proof.transformed,
        PROJECTION_REWRITTEN.replace("import VampLean.Runtime", "import VampLean")
    );
}

// ------------------------------------------------------------
// Misses
// ------------------------------------------------------------

#[test]
fn leaves_a_proof_without_a_normalization_core_untouched() {
    let plain = "-- Lean proof output generated by Vampire\nimport VampLean\n\
                 section vamproof\ntheorem fullProof : True := by\n  trivial\nend vamproof\n";
    let proof = transformed(plain);
    assert_eq!(proof.transformed, plain);
    assert_eq!(proof.transformed, proof.canonical);
    assert_eq!(
        projection_record(&proof).outcome,
        ProofTransformOutcome::Miss
    );
    assert!(!proof.rewritten());
}

#[test]
fn reports_an_unrecognized_core_as_a_retained_legacy_step() {
    // A `prenexify` whose `have stepN' := by` header does not match is
    // not a recognized block: the text is unchanged and the step is
    // recorded as retained rather than rewritten.
    let altered = PROJECTION_INPUT.replace("  have step19' := by", "  have step19' :=  by");
    let proof = transformed(&altered);
    assert_eq!(proof.transformed, proof.canonical);
    let record = projection_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(record.detail["missed_step_ids"], serde_json::json!([19]));
}

// ------------------------------------------------------------
// Fail-Closed Refusals
// ------------------------------------------------------------

fn refusal(raw: &str) -> String {
    let solver = kernel_sat_context();
    let context = KernelSatContext::new(&solver, cadical_identity());
    apply_proof_transforms(JOB, raw, &context)
        .expect_err("the mutated fixture must be refused")
        .message
}

#[test]
fn refuses_a_core_whose_targets_are_only_partially_pinned() {
    let partial = PROJECTION_INPUT.replacen(
        "    try simp only\n    ac_nf0\n    assumption",
        "    simp\n    assumption",
        1,
    );
    assert!(refusal(&partial).contains("ambiguous projection target step 47"));
}

#[test]
fn refuses_an_altered_clause_destructure() {
    let altered = PROJECTION_INPUT.replace("let ⟨s19c0, s19c1", "let ⟨s19c1, s19c0");
    assert!(refusal(&altered).contains("noncontiguous clause names"));
}

#[test]
fn refuses_an_altered_clause_normalization() {
    let altered = PROJECTION_INPUT.replace(
        "  ac_nf0 at s19c0 s19c1 s19c2 s19c3 s19c4 s19c5 s19c6",
        "  ac_nf0 at s19c0 s19c1 s19c2 s19c3 s19c4 s19c5",
    );
    assert!(refusal(&altered).contains("altered clause normalization"));
}

#[test]
fn refuses_a_clause_name_used_outside_its_block() {
    let leaked = PROJECTION_INPUT.replace("  trivial\n", "  exact s19c0\n");
    assert!(refusal(&leaked).contains("outside its projection block"));
}

#[test]
fn refuses_a_reused_primed_normalization_result() {
    let reused = PROJECTION_INPUT.replace("  trivial\n", "  exact step19'\n");
    assert!(refusal(&reused).contains("reuses its primed normalization result"));
}

#[test]
fn refuses_a_core_with_no_targets() {
    let headless = PROJECTION_INPUT.replace("  have step47 :", "  have other47 :");
    assert!(refusal(&headless).contains("no exact projection targets"));
}

#[test]
fn refuses_a_stray_projection_call_outside_a_generated_body() {
    let stray =
        PROJECTION_REWRITTEN.replace("  trivial\n", "  vampire_project_ordered using step19\n");
    assert!(
        refusal(&stray)
            .contains("executable vampire_project outside an exact generated projection body")
    );
}

#[test]
fn refuses_a_proof_that_is_not_one_vamplean_module() {
    let foreign = PROJECTION_INPUT.replace(
        "import VampLean.Runtime",
        "import VampLean.Runtime\nimport Mathlib",
    );
    assert!(refusal(&foreign).contains("exactly one import"));

    let sectionless = PROJECTION_INPUT.replace("end vamproof", "end other");
    assert!(refusal(&sectionless).contains("close its section"));
}

// ------------------------------------------------------------
// Canonicalization
// ------------------------------------------------------------

#[test]
fn normalizes_line_endings_and_trailing_whitespace() {
    let ragged = "-- Lean proof output generated by Vampire\r\nimport VampLean   \r\n\
                  section vamproof\ntheorem fullProof : True := by   \n  trivial\n\
                  end vamproof\n\n\n";
    let proof = transformed(ragged);
    assert_eq!(
        proof.canonical,
        "-- Lean proof output generated by Vampire\nimport VampLean\nsection vamproof\n\
         theorem fullProof : True := by\n  trivial\nend vamproof\n"
    );
    assert_eq!(proof.transforms[0].outcome, ProofTransformOutcome::Applied);
}

// ------------------------------------------------------------
// Receipt Bookkeeping
// ------------------------------------------------------------

#[test]
fn chains_the_recorded_digests_across_the_fixed_order() {
    let proof = transformed(PROJECTION_INPUT);
    assert_eq!(proof.transforms.len(), TRANSFORM_ORDER.len());
    for (record, id) in proof.transforms.iter().zip(TRANSFORM_ORDER) {
        assert_eq!(record.id, id);
        assert_eq!(record.version, id.version());
    }
    // The kernel-SAT step sits between the canonical form and the two
    // optional rewrites, and misses on this fixture, so the projection is
    // handed the canonical text and its output is the final text.
    assert_eq!(proof.transforms[1].input_sha256, proof.canonical_sha256);
    assert_eq!(proof.transforms[2].input_sha256, proof.canonical_sha256);
    assert_eq!(proof.transforms[2].output_sha256, proof.transformed_sha256);
    assert!(proof.rewritten());
}

#[test]
fn a_compile_gate_fallback_records_only_the_rewrites_it_gave_up() {
    let proof = transformed(PROJECTION_INPUT);
    let candidate = proof
        .fallback_candidates
        .first()
        .expect("a projected proof has something to retreat to");
    assert_eq!(candidate.dropped, vec![ProofTransformId::ClauseProjection]);
    let mut records = proof.transforms.clone();
    mark_rolled_back(&mut records, &candidate.dropped);
    // The canonical step itself is never rolled back: it is what every
    // candidate is built on. (It reports a miss on this fixture because
    // the fixture is already canonical.)
    assert_eq!(records[0].outcome, ProofTransformOutcome::Miss);
    let projection = records
        .iter()
        .find(|record| record.id == ProofTransformId::ClauseProjection)
        .expect("the projection step ran");
    let rendered = projection.to_json();
    assert_eq!(rendered["outcome"], "fallback");
    assert_eq!(rendered["id"], "clause_projection");
    // A rolled-back step still names the candidate it produced, so the
    // receipt records what was tried as well as what was kept.
    assert_eq!(rendered["output_sha256"], proof.transformed_sha256);
    // Nothing else moved: a step that missed did not become a rollback.
    for record in &records {
        if record.id != ProofTransformId::ClauseProjection {
            assert_ne!(record.outcome, ProofTransformOutcome::Fallback);
        }
    }
}

// ------------------------------------------------------------
// The Fallback Candidate Chain
// ------------------------------------------------------------

/// One run of the fixed order, described by what each step did and the
/// text it left behind, so the chain's own arithmetic can be read on a
/// case no single checked-in fixture exercises end to end.
fn chain_of(steps: [(ProofTransformOutcome, &str); 4]) -> Vec<ProofCandidate> {
    let mut transforms = Vec::new();
    let mut prefixes = Vec::new();
    for (id, (outcome, text)) in TRANSFORM_ORDER.into_iter().zip(steps) {
        transforms.push(ProofTransformRecord {
            id,
            version: id.version(),
            outcome,
            input_sha256: String::new(),
            output_sha256: crate::encoding::bytes_sha256(text.as_bytes()),
            detail: serde_json::json!({}),
        });
        prefixes.push((
            text.to_string(),
            crate::encoding::bytes_sha256(text.as_bytes()),
            Vec::new(),
        ));
    }
    super::fallback_candidates(&transforms, &prefixes)
}

#[test]
fn the_chain_drops_one_optional_rewrite_at_a_time() {
    // Both optional rewrites changed the text, so the chain offers the
    // projected proof first and only then the canonical one — never the
    // canonical one straight away.
    let chain = chain_of([
        (ProofTransformOutcome::Applied, "canonical"),
        (ProofTransformOutcome::Miss, "canonical"),
        (ProofTransformOutcome::Applied, "projected"),
        (ProofTransformOutcome::Applied, "sliced"),
    ]);
    let dropped: Vec<&[ProofTransformId]> = chain
        .iter()
        .map(|candidate| candidate.dropped.as_slice())
        .collect();
    assert_eq!(
        dropped,
        vec![
            &[ProofTransformId::LocalPrenex][..],
            &[
                ProofTransformId::ClauseProjection,
                ProofTransformId::LocalPrenex
            ][..],
        ]
    );
    assert_eq!(chain[0].text, "projected");
    assert_eq!(chain[1].text, "canonical");
}

#[test]
fn the_chain_never_drops_the_kernel_checked_refutation() {
    // Once the kernel-SAT step applied, the shortest candidate is the one
    // it produced: dropping it would put a `bv_decide` reconstruction
    // back into a published module.
    let chain = chain_of([
        (ProofTransformOutcome::Applied, "canonical"),
        (ProofTransformOutcome::Applied, "kernel_sat"),
        (ProofTransformOutcome::Applied, "projected"),
        (ProofTransformOutcome::Applied, "sliced"),
    ]);
    assert_eq!(
        chain
            .iter()
            .map(|candidate| candidate.text.as_str())
            .collect::<Vec<_>>(),
        vec!["projected", "kernel_sat"]
    );
    for candidate in &chain {
        assert!(
            !candidate
                .dropped
                .contains(&ProofTransformId::AvatarKernelSat)
        );
    }
}

#[test]
fn a_step_whose_rewrite_changed_nothing_contributes_no_candidate() {
    // The projection recognizes an already-projected proof and reports it
    // applied, but there is nothing new to retreat to, so the chain does
    // not offer the same text twice.
    let chain = chain_of([
        (ProofTransformOutcome::Applied, "canonical"),
        (ProofTransformOutcome::Miss, "canonical"),
        (ProofTransformOutcome::Applied, "canonical"),
        (ProofTransformOutcome::Applied, "sliced"),
    ]);
    assert_eq!(chain.len(), 1);
    assert_eq!(chain[0].text, "canonical");
    assert_eq!(chain[0].dropped, vec![ProofTransformId::LocalPrenex]);
}

#[test]
fn the_prenex_fixture_offers_the_projected_text_it_was_handed() {
    // On the checked-in slice fixture the targets are already projected,
    // so the projection rewrites nothing and the one candidate is the
    // text the slice step was handed: the same import, the slice gone.
    let proof = prenex_transformed(PRENEX_INPUT);
    assert_eq!(proof.fallback_candidates.len(), 1);
    let candidate = &proof.fallback_candidates[0];
    assert_eq!(candidate.dropped, vec![ProofTransformId::LocalPrenex]);
    assert!(!candidate.text.contains("step39_slice"));
    assert!(candidate.text.contains("vampire_project_ordered"));
    assert_eq!(candidate.extra_imports, vec![CLAUSE_PROJECTION_IMPORT]);
}

#[test]
fn an_avatar_job_that_is_also_projected_retreats_to_the_lrat_proof() {
    // The end of the invariant, on the real pipeline rather than a
    // description of one: a proof carrying both a `bv_decide` AVATAR
    // refutation and a projectable clause package offers exactly one
    // candidate — the kernel-checked refutation with the projection
    // dropped — and neither it nor anything else in the chain reaches
    // the canonical text.
    let raw = PROJECTION_INPUT
        // The AVATAR helper's own guard is a resource option, so the
        // composed fixture also carries Vampire's resource prelude, the
        // way an emitted `casc_2025` proof does.
        .replace(
            "universe u\n",
            "universe u\nset_option maxHeartbeats 0\nset_option maxRecDepth 100000000\n",
        )
        .replace(
            "theorem fullProof",
            &format!("{}\ntheorem fullProof", lrat::tests::AVATAR_BLOCK),
        );
    let solver = avatar_solver();
    let context = KernelSatContext::new(&solver, cadical_identity());
    let proof = apply_proof_transforms(AVATAR_JOB, &raw, &context)
        .expect("the composed fixture is a recognized proof shape");
    assert!(proof.kernel_sat_applied());
    assert_eq!(
        projection_record(&proof).outcome,
        ProofTransformOutcome::Applied
    );

    assert_eq!(proof.fallback_candidates.len(), 1);
    let candidate = &proof.fallback_candidates[0];
    assert_eq!(candidate.dropped, vec![ProofTransformId::ClauseProjection]);
    assert!(!candidate.text.contains("bv_decide"));
    assert!(candidate.text.contains("lrat_proof"));
    assert_ne!(candidate.sha256, proof.canonical_sha256);
    // And the canonical text it is *not* is the one that still carries
    // the native reconstruction.
    assert!(proof.canonical.contains("bv_decide"));
}

#[test]
fn a_proof_nothing_rewrote_has_no_candidates() {
    let plain = "-- Lean proof output generated by Vampire\nimport VampLean\n\
                 section vamproof\ntheorem fullProof : True := by\n  trivial\nend vamproof\n";
    let proof = transformed(plain);
    assert!(proof.fallback_candidates.is_empty());
}

// ------------------------------------------------------------
// The Kernel-SAT Step In The Pipeline
// ------------------------------------------------------------

use lrat::tests::{AVATAR_BLOCK, LRAT_TRACE, raw_proof};

const AVATAR_JOB: &str = "init_clause_0";

/// The recorded stand-in for the pinned CaDiCaL, with the trace it
/// produces for the captured AVATAR block's DIMACS.
fn avatar_solver() -> lrat::RecordedLratSolver {
    lrat::RecordedLratSolver::new(vec![(199, LRAT_TRACE.to_string())])
}

fn avatar_pipeline(
    raw: &str,
    solver: &dyn lrat::LratSolver,
) -> Result<TransformedProof, ProofTransformError> {
    let context = KernelSatContext::new(solver, cadical_identity());
    apply_proof_transforms(AVATAR_JOB, raw, &context)
}

fn kernel_sat_record(proof: &TransformedProof) -> &ProofTransformRecord {
    proof
        .transforms
        .iter()
        .find(|record| record.id == ProofTransformId::AvatarKernelSat)
        .expect("the kernel-SAT step always runs")
}

#[test]
fn the_kernel_sat_step_runs_before_the_optional_rewrites_under_its_pinned_id() {
    // It is mandatory, so it runs inside every prefix the compile gate's
    // candidate chain can retreat to; the two optional speed rewrites
    // follow it and are what the chain gives up.
    assert_eq!(
        TRANSFORM_ORDER,
        [
            ProofTransformId::Canonical,
            ProofTransformId::AvatarKernelSat,
            ProofTransformId::ClauseProjection,
            ProofTransformId::LocalPrenex,
        ]
    );
    assert_eq!(
        ProofTransformId::AvatarKernelSat.name(),
        "avatar_kernel_sat_lrat"
    );
}

#[test]
fn a_proof_without_an_avatar_refutation_records_a_miss() {
    let proof = transformed(PROJECTION_INPUT);
    let record = kernel_sat_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(record.detail["helper_count"], serde_json::json!(0));
    assert_eq!(record.detail["helpers"], serde_json::json!([]));
    assert!(
        !proof
            .extra_imports
            .contains(&lrat::FROM_LRAT_IMPORT.to_string())
    );
}

#[test]
fn a_rewritten_avatar_refutation_asks_for_the_mathlib_import() {
    let solver = avatar_solver();
    let proof = avatar_pipeline(&raw_proof(AVATAR_BLOCK), &solver).unwrap();
    let record = kernel_sat_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Applied);
    assert!(!proof.transformed.contains("bv_decide"));
    assert!(proof.transformed.contains("lrat_proof inf_s199_lrat"));
    assert_eq!(
        proof.extra_imports,
        vec![lrat::FROM_LRAT_IMPORT.to_string()]
    );
    // The module name, never an import line: `packageProof` writes the
    // line, and refuses raw text that carries one.
    assert!(!proof.extra_imports[0].starts_with("import "));
}

#[test]
fn the_receipt_records_the_solver_identity_and_every_helpers_evidence() {
    let solver = avatar_solver();
    let proof = avatar_pipeline(&raw_proof(AVATAR_BLOCK), &solver).unwrap();
    let record = kernel_sat_record(&proof);
    assert_eq!(record.version, lrat::TRANSFORM_VERSION);
    assert_eq!(record.detail["cadical"], cadical_identity());
    assert_eq!(record.detail["already_applied"], serde_json::json!(false));
    assert_eq!(record.detail["helper_count"], serde_json::json!(1));
    let helper = &record.detail["helpers"][0];
    assert_eq!(helper["step_id"], serde_json::json!(199));
    assert_eq!(helper["kind"], serde_json::json!("sat"));
    assert_eq!(helper["clauses"], serde_json::json!(4));
    assert_eq!(helper["variables"], serde_json::json!(3));
    assert_eq!(helper["lrat_additions"], serde_json::json!(3));
    assert_eq!(helper["lrat_deletions"], serde_json::json!(1));
    assert_eq!(helper["lrat_max_clause_id"], serde_json::json!(7));
    assert_eq!(
        helper["lrat_sha256"],
        serde_json::json!(crate::encoding::bytes_sha256(LRAT_TRACE.as_bytes()))
    );
    // The probe module is rendered but never compiled; its digest is the
    // only thing the receipt keeps of it.
    assert!(record.detail["probe_sha256"].is_string());
}

#[test]
fn no_candidate_of_an_avatar_job_reintroduces_bv_decide() {
    // The canonical text of an AVATAR job still closes its Boolean helper
    // by `bv_decide`, so retreating to it would publish a native-runtime
    // reconstruction. The chain therefore stops above the kernel-SAT
    // step: this proof rewrites nothing else, so it has no candidate at
    // all and such a job fails its build instead.
    let solver = avatar_solver();
    let proof = avatar_pipeline(&raw_proof(AVATAR_BLOCK), &solver).unwrap();
    assert!(proof.rewritten());
    assert!(proof.kernel_sat_applied());
    assert!(proof.fallback_candidates.is_empty());
    for candidate in &proof.fallback_candidates {
        assert!(!candidate.text.contains("bv_decide"));
        assert!(
            !candidate
                .dropped
                .contains(&ProofTransformId::AvatarKernelSat)
        );
    }

    // A job the kernel-SAT step missed keeps the ordinary chain down to
    // the canonical text.
    let projected = transformed(PROJECTION_INPUT);
    assert!(projected.rewritten());
    assert!(!projected.kernel_sat_applied());
    assert_eq!(
        projected.fallback_candidates.last().map(|c| &c.sha256),
        Some(&projected.canonical_sha256)
    );
}

#[test]
fn a_rat_bearing_trace_fails_the_job_with_its_recorded_reason() {
    // A RAT step is well-formed evidence outside the accepted RUP-only
    // fragment. It is never a silent skip: the job fails, naming why, and
    // the emitted `bv_decide` reconstruction is not published in its place.
    // The captured block's own trace with a RAT group appended to the
    // first addition's hints: well formed, outside the accepted fragment.
    let solver = lrat::RecordedLratSolver::new(vec![(
        199,
        "5 -1 0 2 3 -1 2 0\n6 2 0 5 1 0\n7 0 6 4 0\n".to_string(),
    )]);
    let error = avatar_pipeline(&raw_proof(AVATAR_BLOCK), &solver)
        .expect_err("a RAT-bearing trace is refused");
    assert_eq!(error.transform, ProofTransformId::AvatarKernelSat);
    assert_eq!(error.job_id, AVATAR_JOB);
    assert!(
        error.message.contains("RUP-only fragment"),
        "{}",
        error.message
    );
    assert!(
        error.message.contains("may not be published"),
        "{}",
        error.message
    );
}

#[test]
fn a_solver_that_produces_no_trace_fails_the_job() {
    let solver = lrat::RecordedLratSolver::new(Vec::new());
    let error = avatar_pipeline(&raw_proof(AVATAR_BLOCK), &solver)
        .expect_err("a proof whose AVATAR refutation has no trace is refused");
    assert_eq!(error.transform, ProofTransformId::AvatarKernelSat);
    assert!(
        error.message.contains("no recorded LRAT trace"),
        "{}",
        error.message
    );
}

// ------------------------------------------------------------
// The Dependency-Sliced Local Prenex
// ------------------------------------------------------------

/// One complete emitted proof carrying the pinned global skolemisation
/// block, lifted verbatim out of
/// `Benchmark/Example0001/Certificate/VampireArtifacts/jobs/term_check/leancheck.lean`
/// (step 39, its `change` lineage through step 28, and its seven already
/// projected targets) around the same minimal module frame as
/// [`PROJECTION_INPUT`], and likewise spelled so the legacy Python's own
/// canonicalization is the identity on it.
const PRENEX_INPUT: &str = include_str!("fixtures/prenex_input.lean");
/// The legacy `rewrite_vamplean_prenex_slices` output on [`PRENEX_INPUT`],
/// generated from `whiel_synth` and checked in as the differential-parity
/// reference.
const PRENEX_REWRITTEN: &str = include_str!("fixtures/prenex_rewritten.lean");

const PRENEX_JOB: &str = "term_check";

// Verbatim projected source around Example5001's failed step79 slice.
// This is a structural transform fixture, not a standalone Lean theorem.
const PRENEX_XOR_TRACE: &str =
    include_str!("fixtures/raw_proofs/Example5001/term_check/projected_trace.lean");

#[test]
fn prenex_declines_the_captured_example5001_xor_lineage() {
    for trace in [
        PRENEX_XOR_TRACE.to_string(),
        PRENEX_XOR_TRACE.replace("Xor'", "VampLean.Xor'"),
    ] {
        let trace = format!("-- Structural regression trace\n{trace}");
        let summary = prenex::rewrite_prenex_slices(&trace).unwrap();
        assert_eq!(summary.source, trace);
        assert_eq!(
            summary.detail()["missed"],
            serde_json::json!([{
                "step_id": 79, "reason": "unsupported_first_conjunct_xor_lineage"
            }])
        );
    }
}

#[test]
fn prenex_xor_guard_uses_executable_whole_tokens() {
    for spelling in ["notXor'", "Xor'suffix", "«Xor'»", "Other.Xor'"] {
        let trace = PRENEX_XOR_TRACE.replace("Xor'", spelling);
        let summary = prenex::rewrite_prenex_slices(&trace).unwrap();
        assert_eq!(summary.block_count(), 1, "{spelling}");
    }
    let source = PRENEX_INPUT.replace("  change ", "  change /- Xor' -/ ");
    let summary = prenex::rewrite_prenex_slices(&source).unwrap();
    assert_eq!(summary.block_count(), 1);
}

fn prenex_transformed(raw: &str) -> TransformedProof {
    let solver = kernel_sat_context();
    let context = KernelSatContext::new(&solver, cadical_identity());
    apply_proof_transforms(PRENEX_JOB, raw, &context)
        .expect("the fixture is a recognized proof shape")
}

fn prenex_refusal(raw: &str) -> String {
    let solver = kernel_sat_context();
    let context = KernelSatContext::new(&solver, cadical_identity());
    apply_proof_transforms(PRENEX_JOB, raw, &context)
        .expect_err("the mutated fixture must be refused")
        .message
}

fn prenex_record(proof: &TransformedProof) -> &ProofTransformRecord {
    proof
        .transforms
        .iter()
        .find(|record| record.id == ProofTransformId::LocalPrenex)
        .expect("the local-prenex step always runs")
}

/// The receipt's miss reasons, in order.
fn prenex_misses(record: &ProofTransformRecord) -> Vec<String> {
    record.detail["missed"]
        .as_array()
        .expect("the receipt always carries a miss list")
        .iter()
        .map(|entry| format!("{}:{}", entry["step_id"], entry["reason"].as_str().unwrap()))
        .collect()
}

#[test]
fn reproduces_the_legacy_prenex_slice_rewrite_byte_for_byte() {
    let proof = prenex_transformed(PRENEX_INPUT);
    assert_eq!(proof.transformed, PRENEX_REWRITTEN);
}

#[test]
fn records_the_sliced_witnesses_of_the_reference_shape() {
    let proof = prenex_transformed(PRENEX_INPUT);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Applied);
    assert_eq!(record.detail["slices"], 1);
    assert_eq!(record.detail["step_ids"], serde_json::json!([39]));
    assert_eq!(record.detail["original_witnesses"], 20);
    assert_eq!(record.detail["retained_witnesses"], 6);
    assert_eq!(record.detail["eliminated_witnesses"], 14);
    assert_eq!(
        record.detail["retained_witness_names"],
        serde_json::json!([[
            "«_sK9»",
            "«_sK10»",
            "«_sK11»",
            "«_sK12»",
            "«_sK13»",
            "«_sK14»"
        ]])
    );
    assert!(prenex_misses(record).is_empty());
}

#[test]
fn the_local_prenex_step_runs_last_after_the_projection_it_depends_on() {
    // Its live names come from projected target headers, so it must
    // follow the projection; being last also makes it the first rewrite
    // the compile gate's chain gives up.
    assert_eq!(
        TRANSFORM_ORDER,
        [
            ProofTransformId::Canonical,
            ProofTransformId::AvatarKernelSat,
            ProofTransformId::ClauseProjection,
            ProofTransformId::LocalPrenex,
        ]
    );
    assert_eq!(ProofTransformId::LocalPrenex.name(), "local_prenex");
}

#[test]
fn a_slice_asks_for_the_clause_projection_import_exactly_once() {
    // The slice proves its own conjunct by `vampire_project_ordered`, the
    // same Whiel-owned tactic the projected targets use, so the allow-list
    // entry is requested once however many steps needed it.
    let proof = prenex_transformed(PRENEX_INPUT);
    assert_eq!(proof.extra_imports, vec![CLAUSE_PROJECTION_IMPORT]);
}

#[test]
fn is_idempotent_on_an_already_sliced_proof() {
    let once = prenex_transformed(PRENEX_INPUT);
    let twice = prenex_transformed(&once.transformed);
    assert_eq!(twice.transformed, once.transformed);
    // The marker's digest binds every field the slice removed, so the
    // receipt is reconstructed from the generated block rather than
    // recomputed from a shape that is no longer there.
    assert_eq!(prenex_record(&twice).detail, prenex_record(&once).detail);
    assert_eq!(
        prenex_record(&twice).outcome,
        ProofTransformOutcome::Applied
    );
}

// ------------------------------------------------------------
// The Contract's Structural Misses
// ------------------------------------------------------------

#[test]
fn leaves_a_block_with_no_projected_target_untouched() {
    let orphaned = PRENEX_INPUT.replace(
        "    vampire_project_ordered using step39",
        "    vampire_project_ordered using step40",
    );
    let proof = prenex_transformed(&orphaned);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:no_exact_projection_targets"]);
}

#[test]
fn leaves_an_altered_prenex_call_untouched() {
    let altered = PRENEX_INPUT.replace("  exists_prenex at step28", "  exists_prenex  at step28");
    let proof = prenex_transformed(&altered);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:altered_prenex_call"]);
}

#[test]
fn leaves_a_block_without_a_changed_formula_lineage_untouched() {
    // Without the `change`d full formula the slice's own statement cannot
    // be read off anything the emitter said, so there is nothing to slice.
    let unlineaged = PRENEX_INPUT.replace("\n  change (", "\n  -- change (");
    let proof = prenex_transformed(&unlineaged);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:no_changed_formula_lineage"]);
}

#[test]
fn leaves_a_function_valued_live_witness_untouched() {
    // A witness the first conjunct applies to an argument is a Skolem
    // *function*: `exists_prenex` over the sliced conjunct would not
    // introduce it in that form, so the block stays as emitted.
    let applied = PRENEX_INPUT.replacen("(«_sK9») («_sK10»)", "(«_sK9» v0) («_sK10»)", 1);
    let proof = prenex_transformed(&applied);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:function_valued_live_witness"]);
}

#[test]
fn leaves_a_block_whose_discarded_witness_is_used_later_untouched() {
    let leaked = PRENEX_INPUT.replace("  exact step91", "  exact («_sK17», step91).2");
    let proof = prenex_transformed(&leaked);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:discarded_witness_used_later"]);
}

#[test]
fn leaves_a_block_whose_global_step_is_used_later_untouched() {
    // The slice replaces `step39` by a differently shaped proposition, so
    // any use of it outside the projected targets it was recognized from
    // takes the block out of the contract.
    let reused = PRENEX_INPUT.replace("  exact step91", "  exact (step39, step91).2");
    let proof = prenex_transformed(&reused);
    let record = prenex_record(&proof);
    assert_eq!(record.outcome, ProofTransformOutcome::Miss);
    assert_eq!(prenex_misses(record), ["39:global_step_used_later"]);
}

#[test]
fn a_missed_block_is_returned_byte_for_byte() {
    let altered = PRENEX_INPUT.replace("  exists_prenex at step28", "  exists_prenex  at step28");
    let proof = prenex_transformed(&altered);
    // Only the projection step's own recovery ran; the skolemisation
    // block is exactly what Vampire emitted.
    assert!(proof.transformed.contains("  exists_prenex  at step28"));
    assert!(!proof.transformed.contains("step39_slice"));
}

// ------------------------------------------------------------
// Fail-Closed Refusals
// ------------------------------------------------------------

#[test]
fn refuses_a_generated_slice_whose_witness_list_was_edited() {
    // The marker's digest covers the retained order, so dropping a witness
    // from the destructure is a refusal, not a silently re-accepted slice.
    let edited = PRENEX_REWRITTEN.replace(
        "  let ⟨«_sK9»,«_sK10»,«_sK11»,«_sK12»,«_sK13»,«_sK14»,step39_slice'⟩",
        "  let ⟨«_sK10»,«_sK9»,«_sK11»,«_sK12»,«_sK13»,«_sK14»,step39_slice'⟩",
    );
    assert!(
        prenex_refusal(&edited).contains("altered dependency-sliced skolem step 39"),
        "{}",
        prenex_refusal(&edited)
    );
}

#[test]
fn refuses_a_generated_slice_whose_projection_call_was_redirected() {
    let redirected = PRENEX_REWRITTEN.replace(
        "    vampire_project_ordered using step28",
        "    vampire_project_ordered using step27",
    );
    assert!(
        prenex_refusal(&redirected).contains("altered dependency-sliced skolem step 39"),
        "{}",
        prenex_refusal(&redirected)
    );
}

#[test]
fn refuses_a_marker_that_no_longer_parses() {
    let damaged = PRENEX_REWRITTEN.replace("; sha256: ", "; sha256 ");
    assert!(
        prenex_refusal(&damaged).contains("altered dependency-sliced skolem step 39"),
        "{}",
        prenex_refusal(&damaged)
    );
}

#[test]
fn refuses_a_slice_name_no_generated_block_owns() {
    let orphan = PRENEX_INPUT.replace("  exact step91", "  exact step39_slice");
    assert!(
        prenex_refusal(&orphan).contains("unowned dependency-sliced proof line"),
        "{}",
        prenex_refusal(&orphan)
    );
}

// ------------------------------------------------------------
// The Compile Gate
// ------------------------------------------------------------

#[test]
fn a_rejected_prenex_slice_returns_to_the_projected_text_not_the_canonical_one() {
    // The chain gives up one optional rewrite at a time, so a slice the
    // compile gate rejects costs the slice and nothing else: the
    // projection stands, and the receipt says so.
    let proof = prenex_transformed(PRENEX_INPUT);
    let candidate = proof
        .fallback_candidates
        .first()
        .expect("the projected proof is the first thing to retreat to");
    assert_eq!(candidate.dropped, vec![ProofTransformId::LocalPrenex]);

    let mut records = proof.transforms.clone();
    mark_rolled_back(&mut records, &candidate.dropped);
    let outcome = |id| {
        records
            .iter()
            .find(|record| record.id == id)
            .expect("every step is recorded")
            .outcome
    };
    assert_eq!(
        outcome(ProofTransformId::Canonical),
        ProofTransformOutcome::Miss
    );
    assert_eq!(
        outcome(ProofTransformId::ClauseProjection),
        ProofTransformOutcome::Applied
    );
    assert_eq!(
        outcome(ProofTransformId::LocalPrenex),
        ProofTransformOutcome::Fallback
    );
    // The rolled-back row still names the candidate it produced.
    let slice = records
        .iter()
        .find(|record| record.id == ProofTransformId::LocalPrenex)
        .expect("the slice step ran");
    assert_eq!(slice.output_sha256, proof.transformed_sha256);
}

#[test]
fn chains_the_recorded_digests_through_the_local_prenex_step() {
    let proof = prenex_transformed(PRENEX_INPUT);
    assert_eq!(proof.transforms.len(), TRANSFORM_ORDER.len());
    // The slice step is last, so it is handed the projection's output and
    // its own output is the text that gets packaged.
    assert_eq!(proof.transforms[3].id, ProofTransformId::LocalPrenex);
    assert_eq!(
        proof.transforms[2].output_sha256,
        proof.transforms[3].input_sha256
    );
    assert_eq!(proof.transforms[3].output_sha256, proof.transformed_sha256);
    assert_ne!(
        proof.transforms[3].input_sha256,
        proof.transforms[3].output_sha256
    );
}

// ------------------------------------------------------------
// Canonical Packaging
// ------------------------------------------------------------

/// One emitter-shaped module frame around `body`, with Vampire's own
/// prelude, its volatile trailer and the two linter options it writes.
fn emitted(body: &str) -> String {
    format!(
        "-- Running in auto input_syntax mode. Trying TPTP\n\
         -- Lean proof output generated by Vampire\n\
         import VampLean\n\
         section vamproof\n\
         universe u\n\
         set_option maxHeartbeats 0\n\
         set_option linter.all false\n\
         set_option linter.unusedTactic false\n\
         set_option linter.unusedSimpArgs false\n\
         set_option maxRecDepth 100000000\n\
         variable {{ι : Type u}}\n\
         {body}\n\
         theorem fullProof : True := by\n\
         \x20 trivial\n\
         end vamproof\n\
         -- Version: Vampire 5.0.1 (Release build, commit a9e19dacc)\n\
         -- Termination reason: Refutation\n\
         -- Time elapsed: 0.003 s\n\
         -- Peak memory usage: 6 MB\n"
    )
}

fn canonical_of(raw: &str) -> Result<String, ProofTransformError> {
    let solver = kernel_sat_context();
    let context = KernelSatContext::new(&solver, cadical_identity());
    apply_proof_transforms(JOB, raw, &context).map(|proof| proof.canonical)
}

/// The checked-in raw-proof fixture corpus, as `(benchmark id, job id,
/// text)`.
///
/// A published certificate no longer carries its solver evidence
/// (`VampireArtifacts/` is not part of the published tree), so this
/// property is measured against a small fixture of genuine raw `leancheck`
/// output instead of the live corpus: `fixtures/raw_proofs/<Example>/<job>/
/// leancheck.lean`, unmodified copies of what the pinned Vampire actually
/// emitted, with a README describing their provenance and how to refresh
/// them. It spans the ordinary case (`Example0001`, one job of each kind),
/// a prophecy-schema case (`Example5010`) and a case with named domain
/// constants (`Example4036`).
fn checked_in_raw_proofs() -> Vec<(String, String, String)> {
    let fixtures = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src/framework2/proof_transform/fixtures/raw_proofs");
    let mut proofs = Vec::new();
    let mut examples: Vec<_> = std::fs::read_dir(&fixtures)
        .expect("the raw-proof fixture directory is in the repository")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    examples.sort();
    for example in examples {
        let Ok(entries) = std::fs::read_dir(&example) else {
            continue;
        };
        let mut job_paths: Vec<_> = entries
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .collect();
        job_paths.sort();
        for job in job_paths {
            let source = job.join("leancheck.lean");
            let Ok(text) = std::fs::read_to_string(&source) else {
                continue;
            };
            proofs.push((
                example
                    .file_name()
                    .expect("a benchmark directory is named")
                    .to_string_lossy()
                    .into_owned(),
                job.file_name()
                    .expect("a job directory is named")
                    .to_string_lossy()
                    .into_owned(),
                text,
            ));
        }
    }
    assert!(
        proofs.len() >= 18,
        "the raw_proofs fixture lost its checked-in solver outputs"
    );
    proofs
}

#[test]
fn canonicalizes_every_checked_in_raw_proof() {
    // The standing form of this step's differential-parity measurement
    // against the legacy Python, run over the checked-in raw-proof fixture
    // (see `checked_in_raw_proofs`) rather than the published corpus, which
    // carries no solver evidence. What this test checks, and what stays
    // true as the fixture is refreshed, is this: every genuine emitted
    // proof in the fixture is accepted, loses its volatile lines, gains
    // the certificate's resource policy, keeps its telescope, and is a
    // fixed point of the step.
    for (example, job, raw) in checked_in_raw_proofs() {
        let named = format!("{example}/{job}");
        let canonical = canonical::canonicalize(&raw)
            .unwrap_or_else(|message| panic!("{named} is refused: {message}"));
        for prefix in canonical::VOLATILE_LINE_PREFIXES {
            assert!(
                !canonical.contains(prefix),
                "{named} still carries `{prefix}`"
            );
        }
        for policy in canonical::CERTIFICATE_RESOURCE_POLICY {
            assert_eq!(
                canonical.matches(policy).count(),
                1,
                "{named} does not carry `{policy}` exactly once"
            );
        }
        assert!(!canonical.contains("set_option maxHeartbeats 0\n"));
        assert!(!canonical.contains("set_option maxRecDepth 100000000"));
        assert!(!canonical.contains("linter.unusedTactic"));
        assert!(!canonical.contains("linter.unusedSimpArgs"));
        // The telescope is the one thing left exactly as emitted.
        for line in raw.split('\n').filter(|line| line.starts_with("variable ")) {
            assert!(
                canonical.contains(line.trim_end()),
                "{named} reordered its `variable` telescope"
            );
        }
        assert_eq!(
            canonical::canonicalize(&canonical).expect("a canonical proof canonicalizes"),
            canonical,
            "{named} is not a fixed point of the canonical step"
        );
    }
}

#[test]
fn the_volatile_prefixes_match_the_emitter_check() {
    // `scripts/check_leancheck_emitter.py` is the single authority for
    // which comment lines are volatile. This reads its tuple back and
    // pins the Rust constant to it, so the two cannot drift apart in
    // silence: a prefix added there and not here would be published.
    let script = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("the crate sits inside the repository")
        .join("scripts/check_leancheck_emitter.py");
    let source = std::fs::read_to_string(&script).expect("the emitter check is in the repository");
    let (_, rest) = source
        .split_once("VOLATILE_PREFIXES = (")
        .expect("the emitter check declares VOLATILE_PREFIXES");
    let (tuple, _) = rest
        .split_once(')')
        .expect("the VOLATILE_PREFIXES tuple is closed");
    let declared: Vec<String> = tuple
        .split('\n')
        .filter_map(|line| {
            let line = line.trim().trim_end_matches(',');
            let line = line.strip_prefix('"')?.strip_suffix('"')?;
            Some(line.to_string())
        })
        .collect();
    assert_eq!(declared, canonical::VOLATILE_LINE_PREFIXES);
}

#[test]
fn drops_the_volatile_lines_and_the_two_linter_options() {
    let canonical = canonical_of(&emitted("")).unwrap();
    for prefix in canonical::VOLATILE_LINE_PREFIXES {
        assert!(
            !canonical.contains(prefix),
            "the canonical text still carries `{prefix}`"
        );
    }
    assert!(!canonical.contains("linter.unusedTactic"));
    assert!(!canonical.contains("linter.unusedSimpArgs"));
    // Everything else the emitter wrote about the run stays: these are
    // facts about the pinned toolchain, not about this machine.
    assert!(canonical.contains("set_option linter.all false"));
    assert!(canonical.contains("-- Version: Vampire 5.0.1"));
    assert!(canonical.contains("-- Termination reason: Refutation"));
}

#[test]
fn replaces_vampires_resource_prelude_by_the_certificate_policy() {
    let canonical = canonical_of(&emitted("")).unwrap();
    assert!(!canonical.contains("set_option maxHeartbeats 0"));
    assert!(!canonical.contains("set_option maxRecDepth 100000000"));
    for line in canonical::CERTIFICATE_RESOURCE_POLICY {
        assert!(
            canonical.contains(line),
            "the canonical text is missing `{line}`"
        );
    }
    // In place, not appended: the policy sits where Vampire's prelude was.
    let heartbeats = canonical
        .find("set_option maxHeartbeats 400000000")
        .unwrap();
    let rec_depth = canonical.find("set_option maxRecDepth 1048576").unwrap();
    let section = canonical.find("section vamproof").unwrap();
    let declaration = canonical.find("\nvariable {ι").unwrap();
    assert!(section < heartbeats && heartbeats < rec_depth && rec_depth < declaration);
}

#[test]
fn a_resource_option_in_a_comment_or_a_string_is_not_a_command() {
    // The legacy `test_raw_proof_resource_normalization_is_exact_and_
    // fail_closed`, first half: mentions survive untouched.
    let raw = emitted(
        "-- set_option maxHeartbeats 0\n\
         def resourceMessage := \"set_option maxRecDepth 100000000\"",
    );
    let canonical = canonical_of(&raw).unwrap();
    assert!(canonical.contains("-- set_option maxHeartbeats 0"));
    assert!(canonical.contains("\"set_option maxRecDepth 100000000\""));
}

#[test]
fn canonical_removes_only_genuine_solver_comments_and_complete_linter_commands() {
    let comment = "/- outer\n/- nested\n\
        -- Time elapsed: comment text\n\
        -- Peak memory usage: comment text\n\
        -- Success in time comment text\n\
        --  found proof, printing to comment text\n\
        set_option linter.unusedTactic false\n\
        set_option linter.unusedSimpArgs false\n\
        -/\n-/";
    let scoped = "set_option linter.unusedTactic false in\n\
        theorem helper : True := trivial";
    let annotated = "set_option linter.unusedSimpArgs false -- retained annotation";
    let closing_comment = "/-\n-- Time elapsed: -/ -- actual trailing comment";
    let source = emitted(&format!(
        "{comment}\n{scoped}\n{annotated}\n{closing_comment}"
    ));
    let result = canonical::canonicalize(&source).unwrap();
    assert!(result.contains(comment));
    assert!(result.contains(scoped));
    assert!(result.contains(annotated));
    assert!(result.contains(closing_comment));
    for prefix in canonical::VOLATILE_LINE_PREFIXES {
        let count = if prefix == "-- Time elapsed:" { 2 } else { 1 };
        assert_eq!(result.matches(prefix).count(), count);
    }
    assert_eq!(canonical::canonicalize(&result).unwrap(), result);
}

#[test]
fn canonical_refuses_multiline_statement_literals_before_changing_any_bytes() {
    for literal in [
        "\n-- Time elapsed: statement text\n",
        "\nset_option linter.unusedTactic false\n",
        "\nstatement trailing spaces   \n",
        "statement\r\ntext",
        "statement\rtext",
    ] {
        let source = format!(
            "import VampLean\nsection vamproof\nuniverse u\n\
             set_option maxHeartbeats 0\n\
             set_option maxRecDepth 100000000\n\
             theorem fullProof : \"{literal}\" = \"{literal}\" := rfl\n\
             end vamproof\n"
        );
        let error = canonical::canonicalize(&source).unwrap_err();
        assert!(error.contains("multiline string literal"), "{error}");
    }
}

#[test]
fn canonical_keeps_single_line_literal_contents_while_normalizing_code_whitespace() {
    let literal = r#"def note := "literal  \"quoted\" -- Time elapsed:  ""#;
    let source = emitted(&format!("{literal} \t")).replace('\n', "\r\n");
    let result = canonical::canonicalize(&source).unwrap();
    assert!(result.contains(&format!("{literal}\n")));
    assert!(!result.contains('\r'));
    assert_eq!(canonical::canonicalize(&result).unwrap(), result);
}

#[test]
fn canonical_refuses_literal_shapes_the_emitter_does_not_write() {
    for source in [
        "variable {«name with spaces» : ι}",
        "variable {«name\rwith_cr» : ι}",
        "variable {«name  \nwith_newline» : ι}",
        "variable {«name--comment» : ι}",
        r##"def note := r#"raw \" text"#"##,
        r#"def note := r"raw text""#,
        "def note := s!\"{\"\n-- Time elapsed: interpolation content\n\"}\"",
        "def note := s!  \"{\"\nset_option linter.unusedTactic false\n\"}\"",
        "def note := f!\"formatted\"",
        "def note := custom! \"macro literal\"",
        "def note := s!\n\"macro literal\"",
        "def note := s! /- comment -/ \"macro literal\"",
        "def note := 'x'",
        "def note := '\"'",
        "def note := `(command|\nset_option linter.unusedTactic false\n)",
    ] {
        let error = canonical::canonicalize(&emitted(source)).unwrap_err();
        assert!(error.contains("unsupported"), "{source}: {error}");
    }
}

#[test]
fn refuses_an_unexpected_resource_option() {
    // The legacy test's second half: a changed value, a repeated option,
    // and a prelude out of order are each a refusal, never a guess.
    let base = emitted("");
    let malformed = [
        base.replace("set_option maxHeartbeats 0", "set_option maxHeartbeats 1"),
        base.replace(
            "set_option maxRecDepth 100000000\n",
            "set_option maxRecDepth 100000000\nset_option maxRecDepth 100000000\n",
        ),
        base.replace(
            "set_option maxRecDepth 100000000\nvariable {ι : Type u}",
            "variable {ι : Type u}\nset_option maxRecDepth 100000000",
        ),
    ];
    for source in malformed {
        let error = canonical_of(&source).expect_err("an unexpected resource option is refused");
        assert_eq!(error.transform, ProofTransformId::Canonical);
        assert!(
            error.message.contains("resource option") || error.message.contains("resource prelude"),
            "{}",
            error.message
        );
    }
}

#[test]
fn admits_the_pinned_avatar_helper_guard_below_the_first_declaration() {
    // The `casc_2025` profile writes one `set_option … in` above every
    // AVATAR Boolean helper. The canonical step runs before the kernel-LRAT
    // step that deletes those blocks, so it admits exactly this spelling
    // and leaves it alone.
    let raw = emitted("set_option maxHeartbeats 200000000 in\ntheorem helper : True := trivial");
    let canonical = canonical_of(&raw).unwrap();
    assert!(canonical.contains("set_option maxHeartbeats 200000000 in"));

    // Above the first declaration it is a prelude option in disguise.
    let raw = emitted("").replace(
        "set_option maxRecDepth 100000000\n",
        "set_option maxRecDepth 100000000\nset_option maxHeartbeats 200000000 in\n",
    );
    let error = canonical_of(&raw).expect_err("a guard in the prelude is refused");
    assert!(
        error.message.contains("resource option"),
        "{}",
        error.message
    );
}

#[test]
fn refuses_an_injected_proof_hole_before_anything_compiles_it() {
    for hole in ["sorry", "admit", "axiom bad : False", "run_tac skip"] {
        let raw = emitted(&format!("theorem hole : True := by\n  {hole}"));
        let error = canonical_of(&raw).expect_err("a proof hole is refused");
        assert_eq!(error.transform, ProofTransformId::Canonical);
        assert!(
            error.message.contains("forbidden Lean token"),
            "{}",
            error.message
        );
    }
}

#[test]
fn a_banned_token_inside_a_comment_or_a_string_is_prose() {
    let raw = emitted("-- sorry, this step is long\ndef note := \"unsafe\"");
    canonical_of(&raw).expect("a banned token that is not code is not a hole");
}

#[test]
fn refuses_a_lean_command() {
    let raw = emitted("#print axioms Nat");
    let error = canonical_of(&raw).expect_err("a generated `#` command is refused");
    assert_eq!(error.transform, ProofTransformId::Canonical);
    assert!(error.message.contains("Lean command"), "{}", error.message);
}

#[test]
fn refuses_lean_commands_inside_same_line_wrappers() {
    for command in [
        "set_option pp.universes true in #check Nat",
        "set_option pp.universes true in #eval (1 + 1)",
        "set_option pp.universes true in #guard_msgs in #check Nat",
        "set_option pp.universes true in /- wrapper -/ #eval (1 + 1)",
    ] {
        let error = canonical_of(&emitted(command)).expect_err("wrapped command is refused");
        assert_eq!(error.transform, ProofTransformId::Canonical);
        assert!(error.message.contains("Lean command"), "{}", error.message);
    }
}

#[test]
fn command_text_inside_comments_and_strings_is_preserved() {
    let body = concat!(
        "-- set_option pp.universes true in #eval (1 + 1)\n",
        "/- #check Nat /- #eval (1 + 1) -/ -/\n",
        "def note := \"#eval #check #guard_msgs\"",
    );
    let canonical = canonical_of(&emitted(body)).expect("non-code command text is harmless");
    assert!(canonical.contains(body));
}

#[test]
fn reads_the_measurements_out_of_the_volatile_lines() {
    let measurements = canonical::solver_measurements(&emitted(""));
    assert_eq!(measurements.vampire_elapsed_seconds, Some(0.003));
    assert_eq!(measurements.vampire_peak_memory_mb, Some(6.0));
    let spoofed = format!(
        "{}/-\n-- Time elapsed: 999 s\n\
         /- nested\n-- Peak memory usage: 888 MB\n-/\n\
         -- Time elapsed: 777 s -/ -- actual trailing comment\n",
        emitted("")
    );
    assert_eq!(canonical::solver_measurements(&spoofed), measurements);
    assert_eq!(
        canonical::solver_measurements(&spoofed.replace('\n', "\r\n")),
        measurements
    );
    assert_eq!(
        canonical::solver_measurements(&emitted("def note := \"unterminated")),
        canonical::SolverMeasurements::default()
    );
    // A proof that reports neither leaves both columns empty rather than
    // claiming a zero.
    let measurements = canonical::solver_measurements(PROJECTION_INPUT);
    assert_eq!(measurements, canonical::SolverMeasurements::default());
}

#[test]
fn canonicalization_is_idempotent() {
    let once = canonical_of(&emitted("")).unwrap();
    let twice = canonical_of(&once).unwrap();
    assert_eq!(once, twice);
}

#[test]
fn the_variable_telescope_is_left_exactly_as_vampire_wrote_it() {
    // Its order is real Lean, consumed by the reconstruction modules. The
    // canonical step must not touch it; only a *comparison* of two trees
    // may ignore it.
    let telescope = "variable {«_sK9» «_sK7» «_sK8» :  ι → ι}\n  {«_sP1» «_sP0» :  ι → Prop}";
    let canonical = canonical_of(&emitted(telescope)).unwrap();
    assert!(canonical.contains(telescope));
}

#[test]
fn normalize_telescope_order_sorts_names_and_groups_and_nothing_else() {
    let source = "variable {«_sK9» «_sK7» «_sK8» :  ι → ι}\n  {«_sP1» «_sP0» :  ι → Prop}\n\
                  theorem t : True := trivial\n";
    assert_eq!(
        canonical::normalize_telescope_order(source),
        "variable {«_sK7» «_sK8» «_sK9» : ι → ι}\n  {«_sP0» «_sP1» : ι → Prop}\n\
         theorem t : True := trivial\n"
    );
    // Two spellings of one telescope agree after normalization, and a
    // module with no telescope is returned unchanged.
    let permuted = "variable {«_sP1» «_sP0» :  ι → Prop}\n  {«_sK8» «_sK9» «_sK7» :  ι → ι}\n\
                    theorem t : True := trivial\n";
    assert_eq!(
        canonical::normalize_telescope_order(source),
        canonical::normalize_telescope_order(permuted)
    );
    // A module with no quoted binder group comes back byte for byte, so
    // the comparison digest ignores telescope order and nothing else.
    assert_eq!(
        canonical::normalize_telescope_order(PROJECTION_REWRITTEN),
        PROJECTION_REWRITTEN
    );
}

#[test]
fn telescope_comparison_preserves_non_variable_binders_comments_and_strings() {
    for source in [
        "-- documented binder {«z» «a» : ι}\n",
        "def example : String := \"{«z» «a» : ι}\"\n",
        "theorem chooses_second {«z» «a» : ι} : «a» = «a» := rfl\n",
        "/-\nvariable {«z» «a» : ι}\n  {«c» «b» : Prop}\n-/\n",
        "def example : String := \"\nvariable {«z» «a» : ι}\n\"\n",
        "def example := `(command|\nvariable {«z» «a» : ι}\n)\n",
        "variable {«z» «a» : ι} -- an unrecognized annotated layout\n",
        "variable {«z» «a» : ι} {«c» «b» : Prop}\n",
        "variable {«z» «a» : Nat}\n",
        "variable {«z odd» «z» «a» : ι}\n",
        "variable {«z--» «z» «a» : ι}\n",
        "variable {«z» «a» : «earlier» → Prop}\n",
        "/- unterminated\nvariable {«z» «a» : ι}\n",
    ] {
        assert_eq!(canonical::normalize_telescope_order(source), source);
        let changed = source.replace("«z» «a»", "«a» «z»");
        assert_ne!(
            canonical::normalize_telescope_order(source),
            canonical::normalize_telescope_order(&changed),
            "comparison must retain a change outside the generated telescope: {source}"
        );
    }
}
