-- Running in auto input_syntax mode. Trying TPTP
-- Refutation found. Thanks to Tanya!
-- Lean proof output generated by Vampire
import VampLean
section vamproof
universe u
set_option maxHeartbeats 400000000
set_option linter.all false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option maxRecDepth 1048576


variable {ι : Type u}
variable [inst : Inhabited ι]
variable {«_sK19» «_sK20» «_sK18» «_sK15» «_sK16» «_sK17» «_sK21» «_sK22» «_sK23» «_sK24» :  ι → ι}
  {«_sK26» «_sK25» «_sK27» «_sK28» :  ι → ι → ι}
  {«_sK13» «_sK14» «_sK10» «_sK11» «_sK12» «_sK9» : ι}
  {«_op_zE» «_op_zS» «_op_zT» «_yp_zS» «_yp_zT» :  ι → ι → Prop}
  {«_sP0» «_sP1» «_sP2» :  ι → Prop}
variable {sA1 : Prop}
-- step 3 rectify
theorem inf_s3 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ True ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zT» v0 v1) ↔ ((v0=v0) ∧ (v1=v1) ∧ True ∧ False)))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True)))))))))) → (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))))))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ True ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zT» v21 v22) ↔ ((v21=v21) ∧ (v22=v22) ∧ True ∧ False)))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28) ∧ True)))))))))) → (∀ v29 : ι,(∀ v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34) ∧ True))))))))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 4 true and false elimination
theorem inf_s4 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ True ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zT» v21 v22) ↔ ((v21=v21) ∧ (v22=v22) ∧ True ∧ False)))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28) ∧ True)))))))))) → (∀ v29 : ι,(∀ v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34) ∧ True))))))))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (∀ v21 : ι,(∀ v22 : ι,(¬(«_op_zT» v21 v22)))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))))))) → (∀ v29 : ι,(∀ v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))))))) := by
  intro h
  remove_tauto at h<;>
  first | exact h | grind

-- step 5 flattening
theorem inf_s5 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (∀ v21 : ι,(∀ v22 : ι,(¬(«_op_zT» v21 v22)))) ∧ (∀ v23 : ι,(∀ v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 : ι,(∃ v26 : ι,(∃ v27 : ι,(∃ v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))))))) → (∀ v29 : ι,(∀ v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 : ι,(∃ v32 : ι,(∃ v33 : ι,(∃ v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 6 pure predicate removal
theorem inf_s6 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) := by
  grind

-- step 7 pure predicate removal
theorem inf_s7 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) := by
  grind

-- step 8 ennf transformation
theorem inf_s8 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) → (∀ v29 v30 : ι,((«_op_zS» v29 v30) ↔ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))))) →
  ((∃ v29 v30 : ι,(Xor' («_op_zS» v29 v30) ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))))) := by
  intros h
  ennf_transformation at h<;>
  exact h

-- step 9 flattening
theorem inf_s9 : ((∃ v29 v30 : ι,(Xor' («_op_zS» v29 v30) ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))))))) →
  ((∃ v29 v30 : ι,(Xor' («_op_zS» v29 v30) ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 26 nnf transformation
theorem inf_s26 : ((∃ v29 v30 : ι,(Xor' («_op_zS» v29 v30) ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) →
  ((∃ v29 v30 : ι,((((¬(«_op_zE» v29 v30)) ∧ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zE» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))) ∨ (¬(«_op_zS» v29 v30))) ∧ (((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))) ∨ («_op_zS» v29 v30)))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))) ∨ (¬(«_op_zS» v23 v24)))))) := by
  intro h
  nnf_transformation at h<;>
  first | exact h | grind

-- step 27 flattening
theorem inf_s27 : ((∃ v29 v30 : ι,((((¬(«_op_zE» v29 v30)) ∧ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zE» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))) ∨ (¬(«_op_zS» v29 v30))) ∧ (((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))) ∨ («_op_zS» v29 v30)))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28)))) ∨ (¬(«_op_zS» v23 v24)))))) →
  ((∃ v29 v30 : ι,((((¬(«_op_zE» v29 v30)) ∧ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zE» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))) ∨ (¬(«_op_zS» v29 v30))) ∧ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) ∨ («_op_zS» v29 v30)))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))) ∨ (¬(«_op_zS» v23 v24)))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 28 rectify
theorem inf_s28 : ((∃ v29 v30 : ι,((((¬(«_op_zE» v29 v30)) ∧ (∀ v31 v32 v33 v34 : ι,((¬(«_op_zE» v31 v32)) ∨ (¬(«_op_zT» v33 v34)) ∨ (¬(v32=v33)) ∨ (¬(v29=v31)) ∨ (¬(v30=v34))))) ∨ (¬(«_op_zS» v29 v30))) ∧ ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34))) ∨ («_op_zS» v29 v30)))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,(((«_op_zS» v23 v24) ∨ ((¬(«_op_zE» v23 v24)) ∧ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zE» v25 v26)) ∨ (¬(«_op_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))) ∨ (¬(«_op_zS» v23 v24)))))) →
  ((∃ v0 v1 : ι,((((¬(«_op_zE» v0 v1)) ∧ (∀ v2 v3 v4 v5 : ι,((¬(«_op_zE» v2 v3)) ∨ (¬(«_op_zT» v4 v5)) ∨ (¬(v3=v4)) ∨ (¬(v0=v2)) ∨ (¬(v1=v5))))) ∨ (¬(«_op_zS» v0 v1))) ∧ ((«_op_zE» v0 v1) ∨ (∃ v6 v7 v8 v9 : ι,((«_op_zE» v6 v7) ∧ («_op_zT» v8 v9) ∧ (v7=v8) ∧ (v0=v6) ∧ (v1=v9))) ∨ («_op_zS» v0 v1)))) ∧ (∀ v10 : ι,((∃ v11 v12 : ι,((«_op_zE» v11 v12) ∧ (v10=v11))) ∨ (∃ v13 v14 : ι,((«_op_zE» v13 v14) ∧ (v10=v14))) ∨ (∃ v15 v16 : ι,((«_op_zS» v15 v16) ∧ (v10=v15))) ∨ («_sP2» v10) ∨ («_sP1» v10) ∨ («_sP0» v10) ∨ (∃ v17 : ι,(v10=v17)) ∨ (∃ v20 : ι,(v10=v20)) ∨ (∃ v21 : ι,(v10=v21)) ∨ (∃ v24 : ι,(v10=v24)))) ∧ (∀ v25 v26 : ι,(¬(«_op_zT» v25 v26))) ∧ (∀ v27 v28 : ι,(((«_op_zS» v27 v28) ∨ ((¬(«_op_zE» v27 v28)) ∧ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zE» v29 v30)) ∨ (¬(«_op_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ ((«_op_zE» v27 v28) ∨ (∃ v33 v34 v35 v36 : ι,((«_op_zE» v33 v34) ∧ («_op_zT» v35 v36) ∧ (v34=v35) ∧ (v27=v33) ∧ (v28=v36))) ∨ (¬(«_op_zS» v27 v28)))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 78 forward subsumption resolution
theorem inf_s78 : ((«_op_zE» («_sK9») («_sK10»)) ∨ («_op_zT» («_sK13») («_sK14»)) ∨ («_op_zS» («_sK9») («_sK10»))) →
  (∀ v27 v28 : ι, (¬(«_op_zE» v27 v28)) ∨ («_op_zS» v27 v28)) →
  ((«_op_zT» («_sK13») («_sK14»)) ∨ («_op_zS» («_sK9») («_sK10»))) := by
  intros h0 h1
  have i0 := h0
  have i1 := h1 («_sK9») («_sK10»)
  grind only [cases Or]

-- step 80 forward subsumption resolution
theorem inf_s80 : ((¬(«_op_zE» («_sK9») («_sK10»))) ∨ (¬(«_op_zS» («_sK9») («_sK10»)))) →
  (∀ v27 v28 : ι, (¬(«_op_zE» v27 v28)) ∨ («_op_zS» v27 v28)) →
  ((¬(«_op_zE» («_sK9») («_sK10»)))) := by
  intros h0 h1
  have i0 := h0
  have i1 := h1 («_sK9») («_sK10»)
  grind only [cases Or]

-- step 86 avatar component clause
theorem inf_s86 : (sA1 ↔ («_op_zS» («_sK9») («_sK10»))) →
  (sA1→((«_op_zS» («_sK9») («_sK10»)))) := by
  intro h component
  have new := h.mp component
  (first | trivial | ac_nf at new ⊢ | grind [cases Or])

-- step 102 forward subsumption resolution
theorem inf_s102 : ((«_op_zT» («_sK13») («_sK14»)) ∨ («_op_zS» («_sK9») («_sK10»))) →
  (∀ v25 v26 : ι, (¬(«_op_zT» v25 v26))) →
  ((«_op_zS» («_sK9») («_sK10»))) := by
  intros h0 h1
  have i0 := h0
  have i1 := h1 («_sK13») («_sK14»)
  grind only [cases Or]

-- step 108 avatar split clause
theorem inf_s108 : ((«_op_zS» («_sK9») («_sK10»))) →
  (sA1 ↔ («_op_zS» («_sK9») («_sK10»))) →
  (sA1) := by
  intros h0 h1
  try rw[h1]
  try simp only [imp_iff_not_or] at h0
  prenexify
  prenexify at h0
  intros
  have newForm := h0
  simp (config := {failIfUnchanged := false}) only [not_and_or, not_not, eq_comm] at newForm
  simp (config := {failIfUnchanged := false}) only [eq_comm]
  ac_nf at newForm ⊢ <;>
  grind only [cases Or]

-- step 116 resolution
theorem inf_s116 : (∀ v27 v28 : ι, («_op_zT» («_sK27» v27 v28) («_sK28» v27 v28)) ∨ («_op_zE» v27 v28) ∨ (¬(«_op_zS» v27 v28))) →
  (∀ v25 v26 : ι, (¬(«_op_zT» v25 v26))) →
  (∀ v0 v1 : ι, (¬(«_op_zS» v0 v1)) ∨ («_op_zE» v0 v1)) := by
  intros h0 h1 v0 v1
  have i0 := h0 v0 v1
  have i1 := h1 («_sK27» v0 v1) («_sK28» v0 v1)
  grind only [cases Or]

-- step 121 resolution
theorem inf_s121 : (∀ v0 v1 : ι, (¬(«_op_zS» v0 v1)) ∨ («_op_zE» v0 v1)) →
  (sA1→((«_op_zS» («_sK9») («_sK10»)))) →
  (sA1→((«_op_zE» («_sK9») («_sK10»)))) := by
  intros h0 h1 x1
  have i0 := h0 («_sK9») («_sK10»)
  have i1 := h1 x1
  grind only [cases Or]

-- step 122 forward subsumption resolution
theorem inf_s122 : (sA1→((«_op_zE» («_sK9») («_sK10»)))) →
  ((¬(«_op_zE» («_sK9») («_sK10»)))) →
  (sA1→False) := by
  intros h0 h1 x1
  have i0 := h0 x1
  have i1 := h1
  grind only [cases Or]

-- step 123 avatar contradiction clause
theorem inf_s123 : (sA1→False) →
  ¬sA1 := by
  intro h
  try simp only [imp_false, imp_iff_not_or, not_not] at h
  exact h


-- step 124 avatar sat refutation
set_option maxHeartbeats 200000000 in
-- this is probably due to a suboptimal encoding
theorem inf_s124' (sA1' : Bool) : (sA1') → (!sA1') → False := by
  intro h
  bv_decide

theorem inf_s124 : (sA1) → ((¬sA1)) → False := by
  classical
  have satProof := inf_s124' (decide sA1)
  rewrite_decide_eq [sA1 ]
  sat_norm
  exact satProof

theorem fullProof : (((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ True ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zT» v0 v1) ↔ ((v0=v0) ∧ (v1=v1) ∧ True ∧ False)))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True)))))))))) → (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True)))))))))) := by

  apply Classical.byContradiction; intro step2
  have step3 := inf_s3  step2
  have step4 := inf_s4  step3
  have step5 := inf_s5  step4
  have step6 := inf_s6  step5
  have step7 := inf_s7  step6
  have step8 := inf_s8  step7
  have step9 := inf_s9  step8
  -- step10 predicate definition introduction
  let «_sP0» (v0: ι)  := (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))
  have step10 : (∀ v0 : ι,((∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (¬(«_sP0» v0)))) := by
    intros v0
    have s : (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ↔ «_sP0» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step11 predicate definition introduction
  let «_sP1» (v0: ι)  := (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))
  have step11 : (∀ v0 : ι,((∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (¬(«_sP1» v0)))) := by
    intros v0
    have s : (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ↔ «_sP1» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step12 predicate definition introduction
  let «_sP2» (v0: ι)  := (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))
  have step12 : (∀ v0 : ι,((∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (¬(«_sP2» v0)))) := by
    intros v0
    have s : (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ↔ «_sP2» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step13 definition folding
  have step13 := step9
  change ((∃ v29 v30 : ι,(Xor' («_op_zS» v29 v30) ((«_op_zE» v29 v30) ∨ (∃ v31 v32 v33 v34 : ι,((«_op_zE» v31 v32) ∧ («_op_zT» v33 v34) ∧ (v32=v33) ∧ (v29=v31) ∧ (v30=v34)))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0) ∨ (∃ v13 v14 : ι,(v0=v13)) ∨ (∃ v15 v16 : ι,(v0=v16)) ∨ (∃ v17 v18 : ι,(v0=v17)) ∨ (∃ v19 v20 : ι,(v0=v20)))) ∧ (∀ v21 v22 : ι,(¬(«_op_zT» v21 v22))) ∧ (∀ v23 v24 : ι,((«_op_zS» v23 v24) ↔ ((«_op_zE» v23 v24) ∨ (∃ v25 v26 v27 v28 : ι,((«_op_zE» v25 v26) ∧ («_op_zT» v27 v28) ∧ (v26=v27) ∧ (v23=v25) ∧ (v24=v28))))))) at step13
  have step26 := inf_s26  step13
  have step27 := inf_s27  step26
  have step28 := inf_s28  step27
  -- step39 skolemisation
  exists_prenex at step28
  let ⟨«_sK9»,«_sK10»,«_sK15»,«_sK16»,«_sK25»,«_sK26»,«_sK27»,«_sK28»,«_sK11»,«_sK12»,«_sK13»,«_sK14»,«_sK17»,«_sK18»,«_sK19»,«_sK20»,«_sK21»,«_sK22»,«_sK23»,«_sK24»,step39'⟩ := step28
  have step39 : (((((¬(«_op_zE» («_sK9») («_sK10»))) ∧ (∀ v2 v3 v4 v5 : ι,((¬(«_op_zE» v2 v3)) ∨ (¬(«_op_zT» v4 v5)) ∨ (¬(v3=v4)) ∨ (¬((«_sK9»)=v2)) ∨ (¬((«_sK10»)=v5))))) ∨ (¬(«_op_zS» («_sK9») («_sK10»)))) ∧ ((«_op_zE» («_sK9») («_sK10»)) ∨ ((«_op_zE» («_sK11») («_sK12»)) ∧ («_op_zT» («_sK13») («_sK14»)) ∧ ((«_sK12»)=(«_sK13»)) ∧ ((«_sK9»)=(«_sK11»)) ∧ ((«_sK10»)=(«_sK14»))) ∨ («_op_zS» («_sK9») («_sK10»)))) ∧ (∀ v10 : ι,(((«_op_zE» («_sK15» v10) («_sK16» v10)) ∧ ((«_sK15» v10)=v10)) ∨ ((«_op_zE» («_sK17» v10) («_sK18» v10)) ∧ ((«_sK18» v10)=v10)) ∨ ((«_op_zS» («_sK19» v10) («_sK20» v10)) ∧ ((«_sK19» v10)=v10)) ∨ («_sP2» v10) ∨ («_sP1» v10) ∨ («_sP0» v10) ∨ ((«_sK21» v10)=v10) ∨ ((«_sK22» v10)=v10) ∨ ((«_sK23» v10)=v10) ∨ ((«_sK24» v10)=v10))) ∧ (∀ v25 v26 : ι,(¬(«_op_zT» v25 v26))) ∧ (∀ v27 v28 : ι,(((«_op_zS» v27 v28) ∨ ((¬(«_op_zE» v27 v28)) ∧ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zE» v29 v30)) ∨ (¬(«_op_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ ((«_op_zE» v27 v28) ∨ ((«_op_zE» («_sK25» v27 v28) («_sK26» v27 v28)) ∧ («_op_zT» («_sK27» v27 v28) («_sK28» v27 v28)) ∧ ((«_sK26» v27 v28)=(«_sK27» v27 v28)) ∧ ((«_sK25» v27 v28)=v27) ∧ ((«_sK28» v27 v28)=v28)) ∨ (¬(«_op_zS» v27 v28)))))) := by symm_match using step39'
  have step39' := by
    prenexify at step39
    cnfify at step39
    exact step39
  let ⟨s39c0, s39c1, s39c2, s39c3, s39c4, s39c5, s39c6, s39c7, s39c8, s39c9, s39c10, s39c11, s39c12, s39c13, s39c14, s39c15, s39c16, s39c17, s39c18, s39c19, s39c20, s39c21, s39c22⟩ := step39'
  ac_nf0 at s39c0 s39c1 s39c2 s39c3 s39c4 s39c5 s39c6 s39c7 s39c8 s39c9 s39c10 s39c11 s39c12 s39c13 s39c14 s39c15 s39c16 s39c17 s39c18 s39c19 s39c20 s39c21 s39c22
  have step49 : (∀ v27 v28 : ι, («_op_zT» («_sK27» v27 v28) («_sK28» v27 v28)) ∨ («_op_zE» v27 v28) ∨ (¬(«_op_zS» v27 v28))) := by
    try simp only
    ac_nf0
    assumption

  have step52 : (∀ v27 v28 : ι, (¬(«_op_zE» v27 v28)) ∨ («_op_zS» v27 v28)) := by
    try simp only
    ac_nf0
    assumption

  have step53 : (∀ v25 v26 : ι, (¬(«_op_zT» v25 v26))) := by
    try simp only
    ac_nf0
    assumption

  have step65 : ((«_op_zE» («_sK9») («_sK10»)) ∨ («_op_zT» («_sK13») («_sK14»)) ∨ («_op_zS» («_sK9») («_sK10»))) := by
    try simp only
    ac_nf0
    assumption

  have step68 : ((¬(«_op_zE» («_sK9») («_sK10»))) ∨ (¬(«_op_zS» («_sK9») («_sK10»)))) := by
    try simp only
    ac_nf0
    assumption

  have step78 := inf_s78  step65 step52
  have step80 := inf_s80  step68 step52
  -- step84 avatar definition
  let sA1 := («_op_zS» («_sK9») («_sK10»))
  have step84 : (sA1 ↔ («_op_zS» («_sK9») («_sK10»))) := Iff.rfl
  have step86 := inf_s86  step84
  have step102 := inf_s102  step78 step53
  have step108 := inf_s108  step102 step84
  have step116 := inf_s116  step49 step53
  have step121 := inf_s121  step116 step86
  have step122 := inf_s122  step121 step80
  have step123 := inf_s123  step122
  have step124 := inf_s124 step108 step123
  exact step124

end vamproof
-- ------------------------------
-- Version: Vampire 5.0.1 (Release build, commit a9e19dacc on 2026-09-07 00:00:00 +0000)
-- CaDiCaL version: 2.1.3
-- Termination reason: Refutation
-- ------------------------------
-- ------------------------------
