-- Running in auto input_syntax mode. Trying TPTP
-- Refutation found. Thanks to Tanya!
-- Lean proof output generated by Vampire
import VampLean
section vamproof
universe u
set_option maxHeartbeats 400000000
set_option linter.all false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option maxRecDepth 1048576


variable {ι : Type u}
variable [inst : Inhabited ι]
variable {«_sK31» «_sK30» «_sK27» «_sK28» «_sK29» «_sK32» :  ι → ι}
  {«_sK38» «_sK22» «_sK26» «_sK23» «_sK24» «_sK25» «_sK21» «_sK37» : ι}
  {«_sK40» «_sK41» «_sK42» «_sK35» «_sK36» «_sK39» «_sK33» «_sK34» :  ι → ι → ι}
  {«_op_zE» «_op_zS» «_op_zT» «_yp_zS» «_yp_zT» :  ι → ι → Prop}
  {«_sP0» «_sP1» «_sP6» «_sP5» «_sP2» «_sP3» «_sP4» :  ι → Prop}
variable {sA5 sA6 : Prop}
-- step 3 rectify
theorem inf_s3 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_yp_zT» v0 v1)))) ∧ (¬(∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ («_op_zT» v0 v1))))) ∧ (¬(¬(∀ v0 : ι,(∀ v1 : ι,((«_yp_zS» v0 v1) ↔ («_yp_zT» v0 v1)))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_yp_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True)))))))))) → (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zS» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_yp_zT» v0 v1)))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 : ι,(∃ v24 : ι,(∃ v25 : ι,(∃ v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26) ∧ True))))))))) ∧ (∀ v27 : ι,(∀ v28 : ι,((∃ v29 : ι,(∃ v30 : ι,(∃ v31 : ι,(∃ v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32) ∧ True))))) → («_yp_zT» v27 v28)))) ∧ (¬(∀ v33 : ι,(∀ v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34))))) ∧ (¬(¬(∀ v35 : ι,(∀ v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36)))))) ∧ (∀ v37 : ι,(∀ v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 : ι,(∃ v40 : ι,(∃ v41 : ι,(∃ v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42) ∧ True)))))))))) → (∀ v43 : ι,(∀ v44 : ι,((∃ v45 : ι,(∃ v46 : ι,(∃ v47 : ι,(∃ v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48) ∧ True))))) → («_yp_zT» v43 v44)))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 4 true and false elimination
theorem inf_s4 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))) ∨ False)) ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 : ι,(∃ v24 : ι,(∃ v25 : ι,(∃ v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26) ∧ True))))))))) ∧ (∀ v27 : ι,(∀ v28 : ι,((∃ v29 : ι,(∃ v30 : ι,(∃ v31 : ι,(∃ v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32) ∧ True))))) → («_yp_zT» v27 v28)))) ∧ (¬(∀ v33 : ι,(∀ v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34))))) ∧ (¬(¬(∀ v35 : ι,(∀ v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36)))))) ∧ (∀ v37 : ι,(∀ v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 : ι,(∃ v40 : ι,(∃ v41 : ι,(∃ v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42) ∧ True)))))))))) → (∀ v43 : ι,(∀ v44 : ι,((∃ v45 : ι,(∃ v46 : ι,(∃ v47 : ι,(∃ v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48) ∧ True))))) → («_yp_zT» v43 v44)))))) →
  (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 : ι,(∃ v24 : ι,(∃ v25 : ι,(∃ v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))))))) ∧ (∀ v27 : ι,(∀ v28 : ι,((∃ v29 : ι,(∃ v30 : ι,(∃ v31 : ι,(∃ v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32)))))) → («_yp_zT» v27 v28)))) ∧ (¬(∀ v33 : ι,(∀ v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34))))) ∧ (¬(¬(∀ v35 : ι,(∀ v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36)))))) ∧ (∀ v37 : ι,(∀ v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 : ι,(∃ v40 : ι,(∃ v41 : ι,(∃ v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))))))) → (∀ v43 : ι,(∀ v44 : ι,((∃ v45 : ι,(∃ v46 : ι,(∃ v47 : ι,(∃ v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48)))))) → («_yp_zT» v43 v44)))))) := by
  intro h
  remove_tauto at h<;>
  first | exact h | grind

-- step 5 flattening
theorem inf_s5 : (¬(((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v3 : ι,(∃ v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4)))) ∨ (∃ v5 : ι,(∃ v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5)))) ∨ (∃ v7 : ι,(∃ v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))) ∨ (∃ v9 : ι,(∃ v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))) ∨ (∃ v11 : ι,(∃ v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))) ∨ (∃ v13 : ι,(∃ v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))) ∨ (∃ v15 : ι,(∃ v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))) ∨ (∃ v17 : ι,(∃ v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))) ∨ (∃ v19 : ι,(∃ v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))))) ∧ (∀ v21 : ι,(∀ v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 : ι,(∃ v24 : ι,(∃ v25 : ι,(∃ v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))))))) ∧ (∀ v27 : ι,(∀ v28 : ι,((∃ v29 : ι,(∃ v30 : ι,(∃ v31 : ι,(∃ v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32)))))) → («_yp_zT» v27 v28)))) ∧ (¬(∀ v33 : ι,(∀ v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34))))) ∧ (¬(¬(∀ v35 : ι,(∀ v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36)))))) ∧ (∀ v37 : ι,(∀ v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 : ι,(∃ v40 : ι,(∃ v41 : ι,(∃ v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))))))) → (∀ v43 : ι,(∀ v44 : ι,((∃ v45 : ι,(∃ v46 : ι,(∃ v47 : ι,(∃ v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48)))))) → («_yp_zT» v43 v44)))))) →
  (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((∃ v29 v30 v31 v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32))) → («_yp_zT» v27 v28))) ∧ (¬(∀ v33 v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34)))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))) → (∀ v43 v44 : ι,((∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))) → («_yp_zT» v43 v44))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 6 ennf transformation
theorem inf_s6 : (¬(((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((∃ v29 v30 v31 v32 : ι,((«_op_zT» v29 v30) ∧ («_yp_zT» v31 v32) ∧ (v30=v31) ∧ (v27=v29) ∧ (v28=v32))) → («_yp_zT» v27 v28))) ∧ (¬(∀ v33 v34 : ι,((«_op_zS» v33 v34) ↔ («_op_zT» v33 v34)))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))) → (∀ v43 v44 : ι,((∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))) → («_yp_zT» v43 v44))))) →
  ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(Xor' («_op_zS» v33 v34) («_op_zT» v33 v34))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42)))))))) := by
  intros h
  ennf_transformation at h<;>
  exact h

-- step 7 flattening
theorem inf_s7 : ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ ((∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(Xor' («_op_zS» v33 v34) («_op_zT» v33 v34))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42)))))))) →
  ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(Xor' («_op_zS» v33 v34) («_op_zT» v33 v34))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 44 nnf transformation
theorem inf_s44 : ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(Xor' («_op_zS» v33 v34) («_op_zT» v33 v34))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))) →
  ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ ((¬(«_op_zE» v21 v22)) ∧ (∀ v23 v24 v25 v26 : ι,((¬(«_op_zE» v23 v24)) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(v24=v25)) ∨ (¬(v21=v23)) ∨ (¬(v22=v26)))))) ∧ (((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(((¬(«_op_zT» v33 v34)) ∨ (¬(«_op_zS» v33 v34))) ∧ ((«_op_zT» v33 v34) ∨ («_op_zS» v33 v34)))) ∧ (∀ v35 v36 : ι,(((«_yp_zS» v35 v36) ∨ (¬(«_yp_zT» v35 v36))) ∧ ((«_yp_zT» v35 v36) ∨ (¬(«_yp_zS» v35 v36))))) ∧ (∀ v37 v38 : ι,(((«_yp_zS» v37 v38) ∨ ((¬(«_op_zE» v37 v38)) ∧ (∀ v39 v40 v41 v42 : ι,((¬(«_op_zE» v39 v40)) ∨ (¬(«_yp_zT» v41 v42)) ∨ (¬(v40=v41)) ∨ (¬(v37=v39)) ∨ (¬(v38=v42)))))) ∧ (((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42)))) ∨ (¬(«_yp_zS» v37 v38)))))) := by
  intro h
  nnf_transformation at h<;>
  first | exact h | grind

-- step 45 flattening
theorem inf_s45 : ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ ((¬(«_op_zE» v21 v22)) ∧ (∀ v23 v24 v25 v26 : ι,((¬(«_op_zE» v23 v24)) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(v24=v25)) ∨ (¬(v21=v23)) ∨ (¬(v22=v26)))))) ∧ (((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(((¬(«_op_zT» v33 v34)) ∨ (¬(«_op_zS» v33 v34))) ∧ ((«_op_zT» v33 v34) ∨ («_op_zS» v33 v34)))) ∧ (∀ v35 v36 : ι,(((«_yp_zS» v35 v36) ∨ (¬(«_yp_zT» v35 v36))) ∧ ((«_yp_zT» v35 v36) ∨ (¬(«_yp_zS» v35 v36))))) ∧ (∀ v37 v38 : ι,(((«_yp_zS» v37 v38) ∨ ((¬(«_op_zE» v37 v38)) ∧ (∀ v39 v40 v41 v42 : ι,((¬(«_op_zE» v39 v40)) ∨ (¬(«_yp_zT» v41 v42)) ∨ (¬(v40=v41)) ∨ (¬(v37=v39)) ∨ (¬(v38=v42)))))) ∧ (((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42)))) ∨ (¬(«_yp_zS» v37 v38)))))) →
  ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ ((¬(«_op_zE» v21 v22)) ∧ (∀ v23 v24 v25 v26 : ι,((¬(«_op_zE» v23 v24)) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(v24=v25)) ∨ (¬(v21=v23)) ∨ (¬(v22=v26)))))) ∧ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26))) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(((¬(«_op_zT» v33 v34)) ∨ (¬(«_op_zS» v33 v34))) ∧ ((«_op_zT» v33 v34) ∨ («_op_zS» v33 v34)))) ∧ (∀ v35 v36 : ι,(((«_yp_zS» v35 v36) ∨ (¬(«_yp_zT» v35 v36))) ∧ ((«_yp_zT» v35 v36) ∨ (¬(«_yp_zS» v35 v36))))) ∧ (∀ v37 v38 : ι,(((«_yp_zS» v37 v38) ∨ ((¬(«_op_zE» v37 v38)) ∧ (∀ v39 v40 v41 v42 : ι,((¬(«_op_zE» v39 v40)) ∨ (¬(«_yp_zT» v41 v42)) ∨ (¬(v40=v41)) ∨ (¬(v37=v39)) ∨ (¬(v38=v42)))))) ∧ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))) ∨ (¬(«_yp_zS» v37 v38)))))) := by
  intro h
  flattening at h<;>
  first | exact h | grind

-- step 46 rectify
theorem inf_s46 : ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,(((«_op_zS» v21 v22) ∨ ((¬(«_op_zE» v21 v22)) ∧ (∀ v23 v24 v25 v26 : ι,((¬(«_op_zE» v23 v24)) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(v24=v25)) ∨ (¬(v21=v23)) ∨ (¬(v22=v26)))))) ∧ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26))) ∨ (¬(«_op_zS» v21 v22))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(((¬(«_op_zT» v33 v34)) ∨ (¬(«_op_zS» v33 v34))) ∧ ((«_op_zT» v33 v34) ∨ («_op_zS» v33 v34)))) ∧ (∀ v35 v36 : ι,(((«_yp_zS» v35 v36) ∨ (¬(«_yp_zT» v35 v36))) ∧ ((«_yp_zT» v35 v36) ∨ (¬(«_yp_zS» v35 v36))))) ∧ (∀ v37 v38 : ι,(((«_yp_zS» v37 v38) ∨ ((¬(«_op_zE» v37 v38)) ∧ (∀ v39 v40 v41 v42 : ι,((¬(«_op_zE» v39 v40)) ∨ (¬(«_yp_zT» v41 v42)) ∨ (¬(v40=v41)) ∨ (¬(v37=v39)) ∨ (¬(v38=v42)))))) ∧ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))) ∨ (¬(«_yp_zS» v37 v38)))))) →
  ((∃ v0 v1 : ι,((¬(«_yp_zT» v0 v1)) ∧ (∃ v2 v3 v4 v5 : ι,((«_op_zS» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5))))) ∧ (∀ v6 : ι,((∃ v7 v8 : ι,((«_op_zE» v7 v8) ∧ (v6=v7))) ∨ (∃ v9 v10 : ι,((«_op_zE» v9 v10) ∧ (v6=v10))) ∨ (∃ v11 v12 : ι,((«_op_zS» v11 v12) ∧ (v6=v11))) ∨ («_sP6» v6) ∨ («_sP5» v6) ∨ («_sP4» v6) ∨ («_sP3» v6) ∨ («_sP2» v6) ∨ («_sP1» v6) ∨ («_sP0» v6))) ∧ (∀ v13 v14 : ι,(((«_op_zS» v13 v14) ∨ ((¬(«_op_zE» v13 v14)) ∧ (∀ v15 v16 v17 v18 : ι,((¬(«_op_zE» v15 v16)) ∨ (¬(«_op_zT» v17 v18)) ∨ (¬(v16=v17)) ∨ (¬(v13=v15)) ∨ (¬(v14=v18)))))) ∧ ((«_op_zE» v13 v14) ∨ (∃ v19 v20 v21 v22 : ι,((«_op_zE» v19 v20) ∧ («_op_zT» v21 v22) ∧ (v20=v21) ∧ (v13=v19) ∧ (v14=v22))) ∨ (¬(«_op_zS» v13 v14))))) ∧ (∀ v23 v24 : ι,((«_yp_zT» v23 v24) ∨ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zT» v25 v26)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (∃ v29 v30 : ι,(((¬(«_op_zT» v29 v30)) ∨ (¬(«_op_zS» v29 v30))) ∧ ((«_op_zT» v29 v30) ∨ («_op_zS» v29 v30)))) ∧ (∀ v31 v32 : ι,(((«_yp_zS» v31 v32) ∨ (¬(«_yp_zT» v31 v32))) ∧ ((«_yp_zT» v31 v32) ∨ (¬(«_yp_zS» v31 v32))))) ∧ (∀ v33 v34 : ι,(((«_yp_zS» v33 v34) ∨ ((¬(«_op_zE» v33 v34)) ∧ (∀ v35 v36 v37 v38 : ι,((¬(«_op_zE» v35 v36)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38)))))) ∧ ((«_op_zE» v33 v34) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v33=v39) ∧ (v34=v42))) ∨ (¬(«_yp_zS» v33 v34)))))) := by
  intro h
  try simp only [forall_const, exists_const, -iff_self, -eq_self] at h
  symm_match using h

-- step 103 definition unfolding
theorem inf_s103 : ((¬(«_yp_zT» («_sK21») («_sK22»)))) →
  (((«_sK21»)=(«_sK23»))) →
  (((«_sK22»)=(«_sK26»))) →
  ((¬(«_yp_zT» («_sK23») («_sK26»)))) := by
  intros h0 h1 h2
  have i0 := h0
  rewrite (occs := [1]) [h1] at i0
  rewrite (occs := [1]) [h2] at i0
  grind only
-- step 104 definition unfolding
theorem inf_s104 : ((«_op_zS» («_sK23») («_sK24»))) →
  (((«_sK24»)=(«_sK25»))) →
  ((«_op_zS» («_sK23») («_sK25»))) := by
  intros h0 h1
  have i0 := h0
  rewrite (occs := [1]) [h1] at i0
  grind only
-- step 108 equality resolution
theorem inf_s108 : (∀ v23 v24 v25 v26 v27 v28 : ι, («_yp_zT» v23 v24) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28))) →
  (∀ v23 v24 v25 v27 v28 : ι, («_yp_zT» v23 v24) ∨ (¬(«_op_zT» v25 v27)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28))) := by
  intros h0 v23 v24 v25 v27 v28
  have i0 := h0 v23 v24 v25 v27 v27 v28
  grind only [cases Or]

-- step 109 equality resolution
theorem inf_s109 : (∀ v23 v24 v25 v27 v28 : ι, («_yp_zT» v23 v24) ∨ (¬(«_op_zT» v25 v27)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28))) →
  (∀ v24 v25 v27 v28 : ι, («_yp_zT» v25 v24) ∨ (¬(«_op_zT» v25 v27)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v24=v28))) := by
  intros h0 v24 v25 v27 v28
  have i0 := h0 v25 v24 v25 v27 v28
  grind only [cases Or]

-- step 110 equality resolution
theorem inf_s110 : (∀ v24 v25 v27 v28 : ι, («_yp_zT» v25 v24) ∨ (¬(«_op_zT» v25 v27)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v24=v28))) →
  (∀ v25 v27 v28 : ι, (¬(«_yp_zT» v27 v28)) ∨ (¬(«_op_zT» v25 v27)) ∨ («_yp_zT» v25 v28)) := by
  intros h0 v25 v27 v28
  have i0 := h0 v28 v25 v27 v28
  grind only [cases Or]

-- step 111 equality resolution
theorem inf_s111 : (∀ v33 v34 v35 v36 v37 v38 : ι, («_yp_zS» v33 v34) ∨ (¬(«_op_zE» v35 v36)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) →
  (∀ v33 v34 v35 v37 v38 : ι, («_yp_zS» v33 v34) ∨ (¬(«_op_zE» v35 v37)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) := by
  intros h0 v33 v34 v35 v37 v38
  have i0 := h0 v33 v34 v35 v37 v37 v38
  grind only [cases Or]

-- step 112 equality resolution
theorem inf_s112 : (∀ v33 v34 v35 v37 v38 : ι, («_yp_zS» v33 v34) ∨ (¬(«_op_zE» v35 v37)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) →
  (∀ v34 v35 v37 v38 : ι, («_yp_zS» v35 v34) ∨ (¬(«_op_zE» v35 v37)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v34=v38))) := by
  intros h0 v34 v35 v37 v38
  have i0 := h0 v35 v34 v35 v37 v38
  grind only [cases Or]

-- step 113 equality resolution
theorem inf_s113 : (∀ v34 v35 v37 v38 : ι, («_yp_zS» v35 v34) ∨ (¬(«_op_zE» v35 v37)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v34=v38))) →
  (∀ v35 v37 v38 : ι, (¬(«_yp_zT» v37 v38)) ∨ (¬(«_op_zE» v35 v37)) ∨ («_yp_zS» v35 v38)) := by
  intros h0 v35 v37 v38
  have i0 := h0 v38 v35 v37 v38
  grind only [cases Or]

-- step 127 resolution
theorem inf_s127 : (∀ v25 v27 v28 : ι, (¬(«_yp_zT» v27 v28)) ∨ (¬(«_op_zT» v25 v27)) ∨ («_yp_zT» v25 v28)) →
  ((«_yp_zT» («_sK25») («_sK26»))) →
  (∀ v0 : ι, (¬(«_op_zT» v0 («_sK25»))) ∨ («_yp_zT» v0 («_sK26»))) := by
  intros h0 h1 v0
  have i0 := h0 v0 («_sK25») («_sK26»)
  have i1 := h1
  grind only [cases Or]

-- step 128 resolution
theorem inf_s128 : (∀ v35 v37 v38 : ι, (¬(«_yp_zT» v37 v38)) ∨ (¬(«_op_zE» v35 v37)) ∨ («_yp_zS» v35 v38)) →
  ((«_yp_zT» («_sK25») («_sK26»))) →
  (∀ v0 : ι, (¬(«_op_zE» v0 («_sK25»))) ∨ («_yp_zS» v0 («_sK26»))) := by
  intros h0 h1 v0
  have i0 := h0 v0 («_sK25») («_sK26»)
  have i1 := h1
  grind only [cases Or]

-- step 142 resolution
theorem inf_s142 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK36» v13 v14)=v14) ∨ («_op_zE» v13 v14)) →
  ((«_op_zS» («_sK23») («_sK25»))) →
  (((«_sK25»)=(«_sK36» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) := by
  intros h0 h1
  have i0 := h0 («_sK23») («_sK25»)
  have i1 := h1
  grind only [cases Or]

-- step 146 avatar component clause
theorem inf_s146 : (sA5 ↔ («_op_zE» («_sK23») («_sK25»))) →
  ((¬sA5)→((¬(«_op_zE» («_sK23») («_sK25»))))) := by
  intro h component
  have new := not_imp_not.mpr h.mpr component
  (first | trivial | ac_nf at new ⊢ | grind [cases Or])

-- step 147 avatar component clause
theorem inf_s147 : (sA5 ↔ («_op_zE» («_sK23») («_sK25»))) →
  (sA5→((«_op_zE» («_sK23») («_sK25»)))) := by
  intro h component
  have new := h.mp component
  (first | trivial | ac_nf at new ⊢ | grind [cases Or])

-- step 151 avatar component clause
theorem inf_s151 : (sA6 ↔ ((«_sK25»)=(«_sK36» («_sK23») («_sK25»)))) →
  (sA6→(((«_sK25»)=(«_sK36» («_sK23») («_sK25»))))) := by
  intro h component
  have new := h.mp component
  (first | trivial | ac_nf at new ⊢ | grind [cases Or])

-- step 152 avatar split clause
theorem inf_s152 : (((«_sK25»)=(«_sK36» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) →
  (sA6 ↔ ((«_sK25»)=(«_sK36» («_sK23») («_sK25»)))) →
  (sA5 ↔ («_op_zE» («_sK23») («_sK25»))) →
  (sA5 ∨ sA6) := by
  intros h0 h1 h2
  try rw[h1]
  try rw[h2]
  try simp only [imp_iff_not_or] at h0
  prenexify
  prenexify at h0
  intros
  have newForm := h0
  simp (config := {failIfUnchanged := false}) only [not_and_or, not_not, eq_comm] at newForm
  simp (config := {failIfUnchanged := false}) only [eq_comm]
  ac_nf at newForm ⊢ <;>
  grind only [cases Or]

-- step 155 resolution
theorem inf_s155 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK33» v13 v14)=v13) ∨ («_op_zE» v13 v14)) →
  ((«_op_zS» («_sK23») («_sK25»))) →
  (((«_sK23»)=(«_sK33» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) := by
  intros h0 h1
  have i0 := h0 («_sK23») («_sK25»)
  have i1 := h1
  grind only [cases Or]

-- step 168 resolution
theorem inf_s168 : (∀ v0 : ι, (¬(«_op_zE» v0 («_sK25»))) ∨ («_yp_zS» v0 («_sK26»))) →
  (sA5→((«_op_zE» («_sK23») («_sK25»)))) →
  (sA5→((«_yp_zS» («_sK23») («_sK26»)))) := by
  intros h0 h1 x5
  have i0 := h0 («_sK23»)
  have i1 := h1 x5
  grind only [cases Or]

-- step 174 resolution
theorem inf_s174 : (sA5→((«_yp_zS» («_sK23») («_sK26»)))) →
  (∀ v31 v32 : ι, (¬(«_yp_zS» v31 v32)) ∨ («_yp_zT» v31 v32)) →
  (sA5→((«_yp_zT» («_sK23») («_sK26»)))) := by
  intros h0 h1 x5
  have i0 := h0 x5
  have i1 := h1 («_sK23») («_sK26»)
  grind only [cases Or]

-- step 175 forward subsumption resolution
theorem inf_s175 : (sA5→((«_yp_zT» («_sK23») («_sK26»)))) →
  ((¬(«_yp_zT» («_sK23») («_sK26»)))) →
  (sA5→False) := by
  intros h0 h1 x5
  have i0 := h0 x5
  have i1 := h1
  grind only [cases Or]

-- step 176 avatar contradiction clause
theorem inf_s176 : (sA5→False) →
  ¬sA5 := by
  intro h
  try simp only [imp_false, imp_iff_not_or, not_not] at h
  exact h


-- step 196 forward subsumption resolution
theorem inf_s196 : (((«_sK23»)=(«_sK33» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) →
  ((¬sA5)→((¬(«_op_zE» («_sK23») («_sK25»))))) →
  ((¬sA5)→(((«_sK23»)=(«_sK33» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5
  have i0 := h0
  have i1 := h1 x5
  grind only [cases Or]

-- step 197 resolution
theorem inf_s197 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK34» v13 v14)=(«_sK35» v13 v14)) ∨ («_op_zE» v13 v14)) →
  ((«_op_zS» («_sK23») («_sK25»))) →
  (((«_sK34» («_sK23») («_sK25»))=(«_sK35» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) := by
  intros h0 h1
  have i0 := h0 («_sK23») («_sK25»)
  have i1 := h1
  grind only [cases Or]

-- step 199 forward subsumption resolution
theorem inf_s199 : (((«_sK34» («_sK23») («_sK25»))=(«_sK35» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»))) →
  ((¬sA5)→((¬(«_op_zE» («_sK23») («_sK25»))))) →
  ((¬sA5)→(((«_sK34» («_sK23») («_sK25»))=(«_sK35» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5
  have i0 := h0
  have i1 := h1 x5
  grind only [cases Or]

-- step 201 superposition
theorem inf_s201 : (∀ v13 v14 : ι, («_op_zT» («_sK35» v13 v14) («_sK36» v13 v14)) ∨ («_op_zE» v13 v14) ∨ (¬(«_op_zS» v13 v14))) →
  (sA6→(((«_sK25»)=(«_sK36» («_sK23») («_sK25»))))) →
  (sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)) ∨ («_op_zE» («_sK23») («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) := by
  intros h0 h1 x6
  have i0 := h0 («_sK23») («_sK25»)
  have i1 := h1 x6
  grind only [cases Or]

-- step 202 forward subsumption resolution
theorem inf_s202 : (sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)) ∨ («_op_zE» («_sK23») («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) →
  ((¬sA5)→((¬(«_op_zE» («_sK23») («_sK25»))))) →
  ((¬sA5)→sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x6
  have i1 := h1 x5
  grind only [cases Or]

-- step 203 forward subsumption resolution
theorem inf_s203 : ((¬sA5)→sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) →
  ((«_op_zS» («_sK23») («_sK25»))) →
  ((¬sA5)→sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6
  have i1 := h1
  grind only [cases Or]

-- step 204 forward demodulation
theorem inf_s204 : ((¬sA5)→sA6→((«_op_zT» («_sK35» («_sK23») («_sK25»)) («_sK25»)))) →
  ((¬sA5)→(((«_sK34» («_sK23») («_sK25»))=(«_sK35» («_sK23») («_sK25»))))) →
  ((¬sA5)→sA6→((«_op_zT» («_sK34» («_sK23») («_sK25»)) («_sK25»)))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6
  have i1 := h1 x5
  grind only [cases Or]

-- step 207 superposition
theorem inf_s207 : (∀ v13 v14 : ι, («_op_zE» («_sK33» v13 v14) («_sK34» v13 v14)) ∨ («_op_zE» v13 v14) ∨ (¬(«_op_zS» v13 v14))) →
  ((¬sA5)→(((«_sK23»)=(«_sK33» («_sK23») («_sK25»))))) →
  ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5
  have i0 := h0 («_sK23») («_sK25»)
  have i1 := h1 x5
  grind only [cases Or]

-- step 208 forward subsumption resolution
theorem inf_s208 : ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))) ∨ («_op_zE» («_sK23») («_sK25»)) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) →
  ((¬sA5)→((¬(«_op_zE» («_sK23») («_sK25»))))) →
  ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5
  have i0 := h0 x5
  have i1 := h1 x5
  grind only [cases Or]

-- step 209 forward subsumption resolution
theorem inf_s209 : ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))) ∨ (¬(«_op_zS» («_sK23») («_sK25»))))) →
  ((«_op_zS» («_sK23») («_sK25»))) →
  ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))))) := by
  intros h0 h1 x5
  have i0 := h0 x5
  have i1 := h1
  grind only [cases Or]

-- step 210 resolution
theorem inf_s210 : ((¬sA5)→sA6→((«_op_zT» («_sK34» («_sK23») («_sK25»)) («_sK25»)))) →
  (∀ v0 : ι, (¬(«_op_zT» v0 («_sK25»))) ∨ («_yp_zT» v0 («_sK26»))) →
  ((¬sA5)→sA6→((«_yp_zT» («_sK34» («_sK23») («_sK25»)) («_sK26»)))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6
  have i1 := h1 («_sK34» («_sK23») («_sK25»))
  grind only [cases Or]

-- step 219 resolution
theorem inf_s219 : ((¬sA5)→sA6→((«_yp_zT» («_sK34» («_sK23») («_sK25»)) («_sK26»)))) →
  (∀ v35 v37 v38 : ι, (¬(«_yp_zT» v37 v38)) ∨ (¬(«_op_zE» v35 v37)) ∨ («_yp_zS» v35 v38)) →
  ((¬sA5)→sA6→(∀ v0 : ι, (¬(«_op_zE» v0 («_sK34» («_sK23») («_sK25»)))) ∨ («_yp_zS» v0 («_sK26»)))) := by
  intros h0 h1 x5 x6 v0
  have i0 := h0 x5 x6
  have i1 := h1 v0 («_sK34» («_sK23») («_sK25»)) («_sK26»)
  grind only [cases Or]

-- step 283 resolution
theorem inf_s283 : ((¬sA5)→sA6→(∀ v0 : ι, (¬(«_op_zE» v0 («_sK34» («_sK23») («_sK25»)))) ∨ («_yp_zS» v0 («_sK26»)))) →
  ((¬sA5)→((«_op_zE» («_sK23») («_sK34» («_sK23») («_sK25»))))) →
  ((¬sA5)→sA6→((«_yp_zS» («_sK23») («_sK26»)))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6 («_sK23»)
  have i1 := h1 x5
  grind only [cases Or]

-- step 291 resolution
theorem inf_s291 : ((¬sA5)→sA6→((«_yp_zS» («_sK23») («_sK26»)))) →
  (∀ v31 v32 : ι, (¬(«_yp_zS» v31 v32)) ∨ («_yp_zT» v31 v32)) →
  ((¬sA5)→sA6→((«_yp_zT» («_sK23») («_sK26»)))) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6
  have i1 := h1 («_sK23») («_sK26»)
  grind only [cases Or]

-- step 292 forward subsumption resolution
theorem inf_s292 : ((¬sA5)→sA6→((«_yp_zT» («_sK23») («_sK26»)))) →
  ((¬(«_yp_zT» («_sK23») («_sK26»)))) →
  ((¬sA5)→sA6→False) := by
  intros h0 h1 x5 x6
  have i0 := h0 x5 x6
  have i1 := h1
  grind only [cases Or]

-- step 293 avatar contradiction clause
theorem inf_s293 : ((¬sA5)→sA6→False) →
  (sA5 ∨ ¬sA6) := by
  intro h
  try simp only [imp_false, imp_iff_not_or, not_not] at h
  exact h


-- step 297 avatar sat refutation
set_option maxHeartbeats 200000000 in
-- this is probably due to a suboptimal encoding
theorem inf_s297' (sA5' sA6' : Bool) : (sA5' || sA6') → (!sA5') → (sA5' || !sA6') → False := by
  intro h
  bv_decide

theorem inf_s297 : (sA5 ∨ sA6) → ((¬sA5)) → (sA5 ∨ (¬sA6)) → False := by
  classical
  have satProof := inf_s297' (decide sA5) (decide sA6)
  rewrite_decide_eq [sA5 sA6 ]
  sat_norm
  exact satProof

theorem fullProof : (((∀ v0 : ι,((∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_op_zT» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zS» v1 v2) ∧ (v0=v2)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v1)))) ∨ (∃ v1 : ι,(∃ v2 : ι,((«_yp_zT» v1 v2) ∧ (v0=v2)))) ∨ False)) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_op_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zT» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_yp_zT» v0 v1)))) ∧ (¬(∀ v0 : ι,(∀ v1 : ι,((«_op_zS» v0 v1) ↔ («_op_zT» v0 v1))))) ∧ (¬(¬(∀ v0 : ι,(∀ v1 : ι,((«_yp_zS» v0 v1) ↔ («_yp_zT» v0 v1)))))) ∧ (∀ v0 : ι,(∀ v1 : ι,((«_yp_zS» v0 v1) ↔ ((«_op_zE» v0 v1) ∨ (∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zE» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True)))))))))) → (∀ v0 : ι,(∀ v1 : ι,((∃ v2 : ι,(∃ v3 : ι,(∃ v4 : ι,(∃ v5 : ι,((«_op_zS» v2 v3) ∧ («_yp_zT» v4 v5) ∧ (v3=v4) ∧ (v0=v2) ∧ (v1=v5) ∧ True))))) → («_yp_zT» v0 v1))))) := by

  apply Classical.byContradiction; intro step2
  have step3 := inf_s3  step2
  have step4 := inf_s4  step3
  have step5 := inf_s5  step4
  have step6 := inf_s6  step5
  have step7 := inf_s7  step6
  -- step8 predicate definition introduction
  let «_sP0» (v0: ι)  := (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20)))
  have step8 : (∀ v0 : ι,((∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))) ∨ (¬(«_sP0» v0)))) := by
    intros v0
    have s : (∃ v19 v20 : ι,((«_yp_zT» v19 v20) ∧ (v0=v20))) ↔ «_sP0» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step9 predicate definition introduction
  let «_sP1» (v0: ι)  := (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17)))
  have step9 : (∀ v0 : ι,((∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ∨ (¬(«_sP1» v0)))) := by
    intros v0
    have s : (∃ v17 v18 : ι,((«_yp_zT» v17 v18) ∧ (v0=v17))) ↔ «_sP1» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step10 predicate definition introduction
  let «_sP2» (v0: ι)  := (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16)))
  have step10 : (∀ v0 : ι,((∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ∨ (¬(«_sP2» v0)))) := by
    intros v0
    have s : (∃ v15 v16 : ι,((«_yp_zS» v15 v16) ∧ (v0=v16))) ↔ «_sP2» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step11 predicate definition introduction
  let «_sP3» (v0: ι)  := (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13)))
  have step11 : (∀ v0 : ι,((∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ∨ (¬(«_sP3» v0)))) := by
    intros v0
    have s : (∃ v13 v14 : ι,((«_yp_zS» v13 v14) ∧ (v0=v13))) ↔ «_sP3» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step12 predicate definition introduction
  let «_sP4» (v0: ι)  := (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12)))
  have step12 : (∀ v0 : ι,((∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ∨ (¬(«_sP4» v0)))) := by
    intros v0
    have s : (∃ v11 v12 : ι,((«_op_zT» v11 v12) ∧ (v0=v12))) ↔ «_sP4» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step13 predicate definition introduction
  let «_sP5» (v0: ι)  := (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9)))
  have step13 : (∀ v0 : ι,((∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ∨ (¬(«_sP5» v0)))) := by
    intros v0
    have s : (∃ v9 v10 : ι,((«_op_zT» v9 v10) ∧ (v0=v9))) ↔ «_sP5» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step14 predicate definition introduction
  let «_sP6» (v0: ι)  := (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8)))
  have step14 : (∀ v0 : ι,((∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ∨ (¬(«_sP6» v0)))) := by
    intros v0
    have s : (∃ v7 v8 : ι,((«_op_zS» v7 v8) ∧ (v0=v8))) ↔ «_sP6» v0 := Iff.rfl
    (first | exact s | exact or_comm.mp (imp_iff_not_or.mp s.mpr) | have res := (or_comm.mp (imp_iff_not_or.mp s.mpr)); simp only[or_assoc] at res; trivial | exact imp_iff_not_or.mp s.mp)
  -- step15 definition folding
  have step15 := step7
  change ((∃ v43 v44 : ι,((¬(«_yp_zT» v43 v44)) ∧ (∃ v45 v46 v47 v48 : ι,((«_op_zS» v45 v46) ∧ («_yp_zT» v47 v48) ∧ (v46=v47) ∧ (v43=v45) ∧ (v44=v48))))) ∧ (∀ v0 : ι,((∃ v1 v2 : ι,((«_op_zE» v1 v2) ∧ (v0=v1))) ∨ (∃ v3 v4 : ι,((«_op_zE» v3 v4) ∧ (v0=v4))) ∨ (∃ v5 v6 : ι,((«_op_zS» v5 v6) ∧ (v0=v5))) ∨ («_sP6» v0) ∨ («_sP5» v0) ∨ («_sP4» v0) ∨ («_sP3» v0) ∨ («_sP2» v0) ∨ («_sP1» v0) ∨ («_sP0» v0))) ∧ (∀ v21 v22 : ι,((«_op_zS» v21 v22) ↔ ((«_op_zE» v21 v22) ∨ (∃ v23 v24 v25 v26 : ι,((«_op_zE» v23 v24) ∧ («_op_zT» v25 v26) ∧ (v24=v25) ∧ (v21=v23) ∧ (v22=v26)))))) ∧ (∀ v27 v28 : ι,((«_yp_zT» v27 v28) ∨ (∀ v29 v30 v31 v32 : ι,((¬(«_op_zT» v29 v30)) ∨ (¬(«_yp_zT» v31 v32)) ∨ (¬(v30=v31)) ∨ (¬(v27=v29)) ∨ (¬(v28=v32)))))) ∧ (∃ v33 v34 : ι,(Xor' («_op_zS» v33 v34) («_op_zT» v33 v34))) ∧ (∀ v35 v36 : ι,((«_yp_zS» v35 v36) ↔ («_yp_zT» v35 v36))) ∧ (∀ v37 v38 : ι,((«_yp_zS» v37 v38) ↔ ((«_op_zE» v37 v38) ∨ (∃ v39 v40 v41 v42 : ι,((«_op_zE» v39 v40) ∧ («_yp_zT» v41 v42) ∧ (v40=v41) ∧ (v37=v39) ∧ (v38=v42))))))) at step15
  have step44 := inf_s44  step15
  have step45 := inf_s45  step44
  have step46 := inf_s46  step45
  -- step55 skolemisation
  exists_prenex at step46
  let ⟨«_sK21»,«_sK22»,«_sK27»,«_sK28»,«_sK37»,«_sK38»,«_sK39»,«_sK40»,«_sK41»,«_sK42»,«_sK23»,«_sK24»,«_sK25»,«_sK26»,«_sK29»,«_sK30»,«_sK31»,«_sK32»,«_sK33»,«_sK34»,«_sK35»,«_sK36»,step55'⟩ := step46
  have step55 : (((¬(«_yp_zT» («_sK21») («_sK22»))) ∧ ((«_op_zS» («_sK23») («_sK24»)) ∧ («_yp_zT» («_sK25») («_sK26»)) ∧ ((«_sK24»)=(«_sK25»)) ∧ ((«_sK21»)=(«_sK23»)) ∧ ((«_sK22»)=(«_sK26»)))) ∧ (∀ v6 : ι,(((«_op_zE» («_sK27» v6) («_sK28» v6)) ∧ ((«_sK27» v6)=v6)) ∨ ((«_op_zE» («_sK29» v6) («_sK30» v6)) ∧ ((«_sK30» v6)=v6)) ∨ ((«_op_zS» («_sK31» v6) («_sK32» v6)) ∧ ((«_sK31» v6)=v6)) ∨ («_sP6» v6) ∨ («_sP5» v6) ∨ («_sP4» v6) ∨ («_sP3» v6) ∨ («_sP2» v6) ∨ («_sP1» v6) ∨ («_sP0» v6))) ∧ (∀ v13 v14 : ι,(((«_op_zS» v13 v14) ∨ ((¬(«_op_zE» v13 v14)) ∧ (∀ v15 v16 v17 v18 : ι,((¬(«_op_zE» v15 v16)) ∨ (¬(«_op_zT» v17 v18)) ∨ (¬(v16=v17)) ∨ (¬(v13=v15)) ∨ (¬(v14=v18)))))) ∧ ((«_op_zE» v13 v14) ∨ ((«_op_zE» («_sK33» v13 v14) («_sK34» v13 v14)) ∧ («_op_zT» («_sK35» v13 v14) («_sK36» v13 v14)) ∧ ((«_sK34» v13 v14)=(«_sK35» v13 v14)) ∧ ((«_sK33» v13 v14)=v13) ∧ ((«_sK36» v13 v14)=v14)) ∨ (¬(«_op_zS» v13 v14))))) ∧ (∀ v23 v24 : ι,((«_yp_zT» v23 v24) ∨ (∀ v25 v26 v27 v28 : ι,((¬(«_op_zT» v25 v26)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28)))))) ∧ (((¬(«_op_zT» («_sK37») («_sK38»))) ∨ (¬(«_op_zS» («_sK37») («_sK38»)))) ∧ ((«_op_zT» («_sK37») («_sK38»)) ∨ («_op_zS» («_sK37») («_sK38»)))) ∧ (∀ v31 v32 : ι,(((«_yp_zS» v31 v32) ∨ (¬(«_yp_zT» v31 v32))) ∧ ((«_yp_zT» v31 v32) ∨ (¬(«_yp_zS» v31 v32))))) ∧ (∀ v33 v34 : ι,(((«_yp_zS» v33 v34) ∨ ((¬(«_op_zE» v33 v34)) ∧ (∀ v35 v36 v37 v38 : ι,((¬(«_op_zE» v35 v36)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38)))))) ∧ ((«_op_zE» v33 v34) ∨ ((«_op_zE» («_sK39» v33 v34) («_sK40» v33 v34)) ∧ («_yp_zT» («_sK41» v33 v34) («_sK42» v33 v34)) ∧ ((«_sK40» v33 v34)=(«_sK41» v33 v34)) ∧ ((«_sK39» v33 v34)=v33) ∧ ((«_sK42» v33 v34)=v34)) ∨ (¬(«_yp_zS» v33 v34)))))) := by symm_match using step55'
  have step55' := by
    prenexify at step55
    cnfify at step55
    exact step55
  let ⟨s55c0, s55c1, s55c2, s55c3, s55c4, s55c5, s55c6, s55c7, s55c8, s55c9, s55c10, s55c11, s55c12, s55c13, s55c14, s55c15, s55c16, s55c17, s55c18, s55c19, s55c20, s55c21, s55c22, s55c23, s55c24, s55c25, s55c26, s55c27, s55c28, s55c29, s55c30, s55c31, s55c32⟩ := step55'
  ac_nf0 at s55c0 s55c1 s55c2 s55c3 s55c4 s55c5 s55c6 s55c7 s55c8 s55c9 s55c10 s55c11 s55c12 s55c13 s55c14 s55c15 s55c16 s55c17 s55c18 s55c19 s55c20 s55c21 s55c22 s55c23 s55c24 s55c25 s55c26 s55c27 s55c28 s55c29 s55c30 s55c31 s55c32
  have step75 : (∀ v33 v34 v35 v36 v37 v38 : ι, («_yp_zS» v33 v34) ∨ (¬(«_op_zE» v35 v36)) ∨ (¬(«_yp_zT» v37 v38)) ∨ (¬(v36=v37)) ∨ (¬(v33=v35)) ∨ (¬(v34=v38))) := by
    try simp only
    ac_nf0
    assumption

  have step77 : (∀ v31 v32 : ι, (¬(«_yp_zS» v31 v32)) ∨ («_yp_zT» v31 v32)) := by
    try simp only
    ac_nf0
    assumption

  have step81 : (∀ v23 v24 v25 v26 v27 v28 : ι, («_yp_zT» v23 v24) ∨ (¬(«_op_zT» v25 v26)) ∨ (¬(«_yp_zT» v27 v28)) ∨ (¬(v26=v27)) ∨ (¬(v23=v25)) ∨ (¬(v24=v28))) := by
    try simp only
    ac_nf0
    assumption

  have step82 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK36» v13 v14)=v14) ∨ («_op_zE» v13 v14)) := by
    try simp only
    ac_nf0
    assumption

  have step83 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK33» v13 v14)=v13) ∨ («_op_zE» v13 v14)) := by
    try simp only
    ac_nf0
    assumption

  have step84 : (∀ v13 v14 : ι, (¬(«_op_zS» v13 v14)) ∨ ((«_sK34» v13 v14)=(«_sK35» v13 v14)) ∨ («_op_zE» v13 v14)) := by
    try simp only
    ac_nf0
    assumption

  have step85 : (∀ v13 v14 : ι, («_op_zT» («_sK35» v13 v14) («_sK36» v13 v14)) ∨ («_op_zE» v13 v14) ∨ (¬(«_op_zS» v13 v14))) := by
    try simp only
    ac_nf0
    assumption

  have step86 : (∀ v13 v14 : ι, («_op_zE» («_sK33» v13 v14) («_sK34» v13 v14)) ∨ («_op_zE» v13 v14) ∨ (¬(«_op_zS» v13 v14))) := by
    try simp only
    ac_nf0
    assumption

  have step97 : (((«_sK22»)=(«_sK26»))) := by
    try simp only
    ac_nf0
    assumption

  have step98 : (((«_sK21»)=(«_sK23»))) := by
    try simp only
    ac_nf0
    assumption

  have step99 : (((«_sK24»)=(«_sK25»))) := by
    try simp only
    ac_nf0
    assumption

  have step100 : ((«_yp_zT» («_sK25») («_sK26»))) := by
    try simp only
    ac_nf0
    assumption

  have step101 : ((«_op_zS» («_sK23») («_sK24»))) := by
    try simp only
    ac_nf0
    assumption

  have step102 : ((¬(«_yp_zT» («_sK21») («_sK22»)))) := by
    try simp only
    ac_nf0
    assumption

  have step103 := inf_s103  step102 step98 step97
  have step104 := inf_s104  step101 step99
  have step108 := inf_s108  step81
  have step109 := inf_s109  step108
  have step110 := inf_s110  step109
  have step111 := inf_s111  step75
  have step112 := inf_s112  step111
  have step113 := inf_s113  step112
  have step127 := inf_s127  step110 step100
  have step128 := inf_s128  step113 step100
  have step142 := inf_s142  step82 step104
  -- step145 avatar definition
  let sA5 := («_op_zE» («_sK23») («_sK25»))
  have step145 : (sA5 ↔ («_op_zE» («_sK23») («_sK25»))) := Iff.rfl
  have step146 := inf_s146  step145
  have step147 := inf_s147  step145
  -- step149 avatar definition
  let sA6 := ((«_sK25»)=(«_sK36» («_sK23») («_sK25»)))
  have step149 : (sA6 ↔ ((«_sK25»)=(«_sK36» («_sK23») («_sK25»)))) := Iff.rfl
  have step151 := inf_s151  step149
  have step152 := inf_s152  step142 step149 step145
  have step155 := inf_s155  step83 step104
  have step168 := inf_s168  step128 step147
  have step174 := inf_s174  step168 step77
  have step175 := inf_s175  step174 step103
  have step176 := inf_s176  step175
  have step196 := inf_s196  step155 step146
  have step197 := inf_s197  step84 step104
  have step199 := inf_s199  step197 step146
  have step201 := inf_s201  step85 step151
  have step202 := inf_s202  step201 step146
  have step203 := inf_s203  step202 step104
  have step204 := inf_s204  step203 step199
  have step207 := inf_s207  step86 step196
  have step208 := inf_s208  step207 step146
  have step209 := inf_s209  step208 step104
  have step210 := inf_s210  step204 step127
  have step219 := inf_s219  step210 step113
  have step283 := inf_s283  step219 step209
  have step291 := inf_s291  step283 step77
  have step292 := inf_s292  step291 step103
  have step293 := inf_s293  step292
  have step297 := inf_s297 step152 step176 step293
  exact step297

end vamproof
-- ------------------------------
-- Version: Vampire 5.0.1 (Release build, commit a9e19dacc on 2026-09-07 00:00:00 +0000)
-- CaDiCaL version: 2.1.3
-- Termination reason: Refutation
-- ------------------------------
-- ------------------------------
