-- Author: Jesse Comer
import Databases.FinStruct.Basic
import Databases.UnnamedModel.Instance

/-
  This file translates unnamed database instances to finite
  first-order structures.

  Key definitions include:
    * `FinStruct.constantsFixed`
    * `FinStruct.relAdom`
    * `FinStruct.satisfiesAdom`
    * `Instance.toFinStruct`

  Key theorems include:
    * `Instance.toFinStruct_constantsFixed`
    * `Instance.toFinStruct_satisfiesAdom`

  Intervening definitions and lemmas are construction,
  helper, or proof support.
-/

------------------------------------------------------------
-- Expansion Properties
------------------------------------------------------------

namespace FinStruct

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]

/-
  For an FOL signature obtained by converting an unnamed
  relational schema, this Prop asserts that the nullary
  function symbols are interpreted by their underlying
  domain values.
-/
def constantsFixed
    {Γ : UnnamedSchema A}
    {C : Finset D}
    (M : FinStruct D (Γ.toFOLSignature C)) :
    Prop :=
  ∀ f : (Γ.toFOLSignature C).Fun,
    M.funcs f Tuple.empty = f.1

/-
  Active domain generated by the relation facts of a
  function-expanded finite structure.
-/
def relAdom
    {Γ : UnnamedSchema A}
    {C : Finset D}
    (M : FinStruct D (Γ.toFOLSignature C)) : Finset D :=
  Finset.fold (op := (· ∪ ·)) ∅
    (fun X : Γ.syms =>
      Finset.fold (op := (· ∪ ·)) ∅
        (fun t => t.toList.toFinset) (M.rels X))
    Γ.syms.attach

/-
  Active-domain closure for a function-expanded finite
  structure. The set `C` is an additional arbitrary finite
  set of constants, typically used for constants occurring
  in a given query.
-/
def satisfiesAdom
    {Γ : UnnamedSchema A}
    {C : Finset D}
    (M : FinStruct D (Γ.toFOLSignature C)) :
    Prop :=
  ∀ d : D,
    d ∈ M.carrier ↔ d ∈ M.relAdom ∪ C

/-
  Active-domain closure determines the carrier as relation
  active domain plus constants.
-/
theorem carrier_eq_of_satisfiesAdom
    {Γ : UnnamedSchema A}
    {C : Finset D}
    (M : FinStruct D (Γ.toFOLSignature C))
    (hAdom : M.satisfiesAdom) :
    M.carrier = M.relAdom ∪ C := by
  apply Finset.ext
  intro d
  exact hAdom d

/-
  A carrier element outside the relation active domain plus
  constants prevents active-domain closure.
-/
theorem not_satisfiesAdom_of_isolated
    {Γ : UnnamedSchema A}
    {C : Finset D}
    (M : FinStruct D (Γ.toFOLSignature C))
    {d : D}
    (hdCarrier : d ∈ M.carrier)
    (hdAdom : d ∉ M.relAdom ∪ C) :
    ¬ M.satisfiesAdom := by
  intro hAdom
  exact hdAdom ((hAdom d).mp hdCarrier)

end FinStruct

------------------------------------------------------------
-- Function Expansions of Instances
------------------------------------------------------------

namespace Instance

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]

/-
  Expand an instance to a finite nonempty FOL structure.
  The carrier is `I.Adom ∪ C`: in addition to values that
  occur in relation facts, we explicitly include every
  constant in `C`, since a formula may mention constants not
  present in the instance active domain.
-/
def toFinStruct
    {Γ : UnnamedSchema A}
    (I : Instance D Γ)
    (C : Finset D)
    (hNonempty : (I.Adom ∪ C).Nonempty) :
    FinStruct D (Γ.toFOLSignature C) where
  carrier := I.Adom ∪ C
  carrier_nonempty := hNonempty
  rels := fun X => I X
  rels_closed := by
    intro X t ht i
    exact Finset.mem_union.mpr
      (Or.inl
        (Instance.isTupleOver_Adom_of_mem
          (I := I) (s := X) ht i))
  funcs := fun f _ => f.1
  funcs_closed := by
    intro f _args _hArgs
    exact Finset.mem_union.mpr (Or.inr f.2)

/-
  Computable expansion when the intended carrier
  `I.Adom ∪ C` is nonempty.
-/
def toFinStruct?
    {Γ : UnnamedSchema A}
    (I : Instance D Γ)
    (C : Finset D) :
    Option
      (FinStruct D (Γ.toFOLSignature C)) :=
  if h : (I.Adom ∪ C).Nonempty then
    some (I.toFinStruct C h)
  else
    none

/- The canonical expansion fixes constants. -/
theorem toFinStruct_constantsFixed
    {Γ : UnnamedSchema A}
    (I : Instance D Γ)
    (C : Finset D)
    (hNonempty : (I.Adom ∪ C).Nonempty) :
    (I.toFinStruct C hNonempty).constantsFixed := by
  intro f
  rfl

/-
  The canonical expansion has exactly the intended active
  domain plus constants as carrier.
-/
theorem toFinStruct_satisfiesAdom
    {Γ : UnnamedSchema A}
    (I : Instance D Γ)
    (C : Finset D)
    (hNonempty : (I.Adom ∪ C).Nonempty) :
    (I.toFinStruct C hNonempty).satisfiesAdom := by
  intro d
  rfl

end Instance
