-- Lean proof output generated by Vampire
import VampLean.Runtime
section vamproof
universe u
variable {ι : Type u}
variable [inst : Inhabited ι]
theorem fullProof : True := by
  have step19' := by
    prenexify at step19
    cnfify at step19
    exact step19
  let ⟨s19c0, s19c1, s19c2, s19c3, s19c4, s19c5, s19c6⟩ := step19'
  ac_nf0 at s19c0 s19c1 s19c2 s19c3 s19c4 s19c5 s19c6
  have step47 : (∀ v0 v1 : ι, (¬(«_sP3» v0 v1)) ∨ ((«_sK7» v0 v1)=v0) ∨ («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0)) := by
    try simp only
    ac_nf0
    assumption

  have step48 : (∀ v0 v1 : ι, (¬(«_sP3» v0 v1)) ∨ ((«_sK4» v0 v1)=v1) ∨ («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0)) := by
    try simp only
    ac_nf0
    assumption

  have step49 : (∀ v0 v1 : ι, (¬(«_sP3» v0 v1)) ∨ ((«_sK5» v0 v1)=(«_sK6» v0 v1)) ∨ («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0)) := by
    try simp only
    ac_nf0
    assumption

  have step50 : (∀ v0 v1 : ι, («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_S_0_» («_sK6» v0 v1) («_sK7» v0 v1)) ∨ («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0) ∨ (¬(«_sP3» v0 v1))) := by
    try simp only
    ac_nf0
    assumption

  have step51 : (∀ v0 v1 : ι, («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» («_sK4» v0 v1) («_sK5» v0 v1)) ∨ («_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0) ∨ (¬(«_sP3» v0 v1))) := by
    try simp only
    ac_nf0
    assumption

  have step52 : (∀ v0 v1 v2 v3 v4 v5 : ι, («_sP3» v0 v1) ∨ (¬(«_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v2 v3)) ∨ (¬(«_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_S_0_» v4 v5)) ∨ (¬(v3=v4)) ∨ (¬(v1=v2)) ∨ (¬(v0=v5))) := by
    try simp only
    ac_nf0
    assumption

  have step53 : (∀ v0 v1 : ι, (¬(«_r_Whiel_Concrete_WhielNames_ordinary__Whiel_Concrete_ProgramNames_programSymbol_E_0_» v1 v0)) ∨ («_sP3» v0 v1)) := by
    try simp only
    ac_nf0
    assumption
  trivial
end vamproof
-- Version: fixture
