#!/usr/bin/env python3
"""Generate typed registry modules from immediate Benchmark Input files.

A case is a directory `Benchmark/<id>/` holding `Input.lean` and
`Metadata.json`. Everything the registry needs is derived from the directory
name and the input itself; the metadata only has to name the same id. The
generator also writes the library roots `Benchmark/Inputs.lean` and
`Benchmark/Certificates.lean`, the root of the compiler-fidelity proofs
`Benchmark/Fidelity.lean`, the root of the certificates the placement ledger
keeps outside the library `Benchmark/OutsideLibrary.lean`, one notation
round-trip module and one preprocessed round-trip module per input and the
per-case axiom audit, so adding a case
needs no hand edit.

The input digest covers the five canonical declarations only. Comments,
imports, namespace lines and whitespace are outside it.

Default discovery is the whole current inventory. --ids is an explicit,
transitional development selection; it is never a maintained allowlist.
--check performs validation and comparison without writing any file.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path("Whiel/Synthesis/Runtime/FixedAmbientRegistry")
INPUTS_ROOT = Path("Benchmark/Inputs.lean")
CERTIFICATES_ROOT = Path("Benchmark/Certificates.lean")
PLACEMENT = Path("Benchmark/CertificatePlacement.json")
ROUND_TRIP = Path("Whiel/Synthesis/Tests/BenchmarkNotationRoundTrip")
PREPROC_ROUND_TRIP = Path("Whiel/Synthesis/Tests/BenchmarkPreprocRoundTrip")
FIDELITY_ROOT = Path("Benchmark/Fidelity.lean")
OUTSIDE_ROOT = Path("Benchmark/OutsideLibrary.lean")
CASE_AUDIT = Path("Whiel/Synthesis/Tests/FixedAmbientRegistryCaseAxiomAudit.lean")
DECLARATIONS = ("inputSchema", "inputPre", "inputCmd", "inputPost", "inputPreproc")
DIGEST_DOMAIN = "whiel-input-declarations-v1"
EMITTER_MARK = "-- Generated by the Lean-owned fixed-ambient certificate emitter."
EMITTER_MARKS = (EMITTER_MARK, "-- Generated by the Lean-owned fixed-ambient certificate-emitter-v2.")
CERTIFICATE_MODULES = ("Valid", "ProposalBinding", "Invalid")
# Contributor order: students, then advisors, each alphabetical by last name.
CONTRIBUTORS = ("Jesse Comer", "Fangzhu Shen", "Leo Zhang",
                "Mayur Naik", "Sudeepa Roy", "Val Tannen")
HEADER = "-- Benchmark contributors: "
MARKER = "-- Generated fixed-ambient registry format: 1\n"
END = "-- End generated fixed-ambient registry format: 1\n"
SAFE_ID = re.compile(r"[A-Za-z][A-Za-z0-9_]*\Z", re.ASCII)


class RegistryError(ValueError):
    """Invalid inventory or generated state; no changes have been made."""


@dataclass(frozen=True)
class Input:
    canonical_id: str
    module: str
    namespace: str
    sha256: str
    certificates: tuple[str, ...] = ()
    fidelity: bool = False
    outside: bool = False


def lex(text: str, label: str) -> tuple[str, list[str]]:
    """Remove Lean comments in one left-to-right pass.

    Returns the text with every comment replaced by a space and every string
    literal replaced by a numbered placeholder, plus the literals verbatim, so
    that nothing inside a string is ever read as a comment or as whitespace.
    """
    out: list[str] = []
    strings: list[str] = []
    index, size = 0, len(text)
    while index < size:
        if text.startswith("--", index):
            end = text.find("\n", index)
            index = size if end < 0 else end
        elif text.startswith("/-", index):
            depth, index = 1, index + 2
            while depth:
                opened, closed = text.find("/-", index), text.find("-/", index)
                if closed < 0:
                    raise RegistryError(f"unterminated block comment: {label}")
                if 0 <= opened < closed:
                    depth, index = depth + 1, opened + 2
                else:
                    depth, index = depth - 1, closed + 2
            out.append(" ")
        elif text[index] == '"':
            end = index + 1
            while end < size and text[end] != '"':
                end += 2 if text[end] == "\\" else 1
            if end >= size:
                raise RegistryError(f"unterminated string literal: {label}")
            strings.append(text[index:end + 1])
            out.append(f"\x00{len(strings) - 1}\x00")
            index = end + 1
        else:
            out.append(text[index])
            index += 1
    return "".join(out), strings


SET_OPTION = re.compile(
    r"set_option (maxRecDepth|maxHeartbeats|linter\.[A-Za-z.]+) (\d+|true|false)( in)?\Z")


def top_level_allowed(line: str, canonical_id: str, state: dict) -> bool:
    """The fixed shape of an input file: nothing else may sit at column 0."""
    if re.fullmatch(r"import [A-Za-z_][A-Za-z0-9_.]*", line):
        return not state["opened"]
    scopes = ["Whiel", "Benchmark", canonical_id]
    if line.startswith("namespace "):
        expected = len(state["scopes"])
        if expected < 3 and line == f"namespace {scopes[expected]}":
            state["scopes"].append(scopes[expected])
            state["opened"] = True
            return True
        return False
    if line.startswith("end "):
        if state["scopes"] and line == f"end {state['scopes'][-1]}":
            state["scopes"].pop()
            state["closed"] += 1
            return True
        return False
    inside = len(state["scopes"]) == 3
    if line == "open Concrete" or SET_OPTION.match(line):
        return inside
    if line == "#eval inputPreproc.display":
        return inside
    return False


def require_contributor_header(text: str, label: str) -> None:
    """The first line names the case's contributors, known and in order."""
    first = text.split("\n", 1)[0]
    if not first.startswith(HEADER):
        raise RegistryError(f"missing contributor header: {label}")
    names = first[len(HEADER):].split(", ")
    unknown = [name for name in names if name not in CONTRIBUTORS]
    if unknown:
        raise RegistryError(f"unknown contributor {unknown[0]!r}: {label}")
    order = [CONTRIBUTORS.index(name) for name in names]
    if order != sorted(set(order)):
        raise RegistryError(f"contributors repeated or out of order: {label}")


def declaration_digest(text: str, label: str) -> str:
    """Digest of the five canonical declarations, and of nothing else.

    The file must have the fixed input shape, so that no command outside the
    five declarations can change what they mean: imports, the three namespace
    lines, `open Concrete`, the five `def`s, elaboration options and the
    closing display line. Anything else at column 0 is refused.
    """
    stripped, strings = lex(text, label)
    bodies: dict[str, str] = {}
    state = {"scopes": [], "opened": False, "closed": 0}
    current = None
    for line in stripped.split("\n"):
        line = line.rstrip()
        if line[:1] not in ("", " ", "\t"):
            match = re.match(r"def ([A-Za-z_][A-Za-z0-9_]*)(?=[\s:])", line)
            if match and match.group(1) in DECLARATIONS and len(state["scopes"]) == 3:
                current = match.group(1)
                if current in bodies:
                    raise RegistryError(f"duplicate declaration {current}: {label}")
                bodies[current] = ""
            elif top_level_allowed(line, label, state):
                current = None
            else:
                raise RegistryError(f"unexpected top-level line in {label}: {line[:60]!r}")
        if current is not None:
            bodies[current] += line + "\n"
    missing = [name for name in DECLARATIONS if name not in bodies]
    if missing:
        raise RegistryError(f"missing canonical declarations {missing}: {label}")
    if state["scopes"] or state["closed"] != 3:
        raise RegistryError(f"unbalanced namespaces: {label}")

    def canonical(body: str) -> str:
        collapsed = " ".join(body.split())
        return re.sub(r"\x00(\d+)\x00", lambda found: strings[int(found.group(1))], collapsed)

    text = DIGEST_DOMAIN + "\n" + "".join(
        name + "\n" + canonical(bodies[name]) + "\n" for name in DECLARATIONS)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def require_plain(path: Path, directory: bool = False) -> None:
    if path.is_symlink():
        raise RegistryError(f"symlink refused: {path}")
    if not (path.is_dir() if directory else path.is_file()):
        raise RegistryError(f"missing or invalid {'directory' if directory else 'file'}: {path}")


def unique_object(pairs: list[tuple[str, object]]) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise RegistryError(f"duplicate metadata key: {key}")
        result[key] = value
    return result


def placement_problems(root: Path) -> list[str]:
    """What `scripts/place_certificates.py --check` would report, without building."""
    import importlib.util
    script = Path(__file__).resolve().with_name("place_certificates.py")
    spec = importlib.util.spec_from_file_location("place_certificates", script)
    module = importlib.util.module_from_spec(spec)
    sys.modules.setdefault(spec.name, module)
    spec.loader.exec_module(module)
    return module.ledger_problems(root)


def outside_library(root: Path) -> set[str]:
    """Cases whose certificates the placement ledger keeps outside the library.

    `scripts/place_certificates.py` owns the ledger: it records, per certified
    case, whether the certificate fits the watched build's memory limit.
    """
    ledger = root / PLACEMENT
    if ledger.is_symlink():
        raise RegistryError(f"symlink refused: {ledger}")
    problems = placement_problems(root)
    if problems:
        raise RegistryError("certificate placement ledger is not current; run "
                            "scripts/place_certificates.py: " + "; ".join(problems[:3]))
    if not ledger.exists():
        return set()
    try:
        entries = json.loads(ledger.read_text())["certificates"]
        return {name for name, entry in entries.items() if entry["fits"] is False}
    except (ValueError, KeyError, TypeError, AttributeError, UnicodeError) as error:
        raise RegistryError(f"malformed certificate placement ledger: {error}") from error


def discover(root: Path) -> list[Input]:
    benchmark = root / "Benchmark"
    require_plain(benchmark, directory=True)
    outside = outside_library(root)
    result = []
    seen = set()
    for directory in sorted(benchmark.iterdir()):
        # A linked directory cannot be trusted even to inspect its inventory.
        if directory.is_symlink():
            raise RegistryError(f"symlink refused: {directory}")
        if not directory.is_dir():
            continue
        source = directory / "Input.lean"
        if not source.exists() and not source.is_symlink():
            continue
        require_plain(source)
        require_plain(directory / "Metadata.json")
        if not SAFE_ID.fullmatch(directory.name):
            raise RegistryError(f"unsafe canonical directory: {directory.name}")
        try:
            metadata = json.loads((directory / "Metadata.json").read_text(),
                                  object_pairs_hook=unique_object)
        except (ValueError, UnicodeError) as error:
            raise RegistryError(f"malformed metadata for {directory.name}: {error}") from error
        if not isinstance(metadata, dict):
            raise RegistryError(f"metadata must be an object: {directory.name}")
        canonical_id = metadata.get("canonicalId")
        if not isinstance(canonical_id, str) or not SAFE_ID.fullmatch(canonical_id):
            raise RegistryError(f"unsafe canonical id: {canonical_id!r}")
        if canonical_id in seen:
            raise RegistryError(f"duplicate canonical id: {canonical_id}")
        seen.add(canonical_id)
        if canonical_id != directory.name:
            raise RegistryError(f"metadata canonicalId mismatch for {directory.name}")
        certificates = []
        for name in CERTIFICATE_MODULES:
            certificate = directory / "Certificate" / f"{name}.lean"
            if certificate.is_symlink():
                raise RegistryError(f"symlink refused: {certificate}")
            # Only emitter output joins the library; anything else is not a certificate.
            if certificate.is_file() and certificate.read_text().split("\n", 1)[0] in EMITTER_MARKS:
                certificates.append(name)
        if b"\r" in source.read_bytes():
            raise RegistryError(f"carriage return in input: {directory.name}")
        require_contributor_header(source.read_text(), directory.name)
        result.append(Input(canonical_id, f"Benchmark.{directory.name}.Input",
                            f"Whiel.Benchmark.{directory.name}",
                            declaration_digest(source.read_text(), directory.name),
                            tuple(certificates),
                            fidelity_module(directory),
                            directory.name in outside))
    if not result:
        raise RegistryError("empty Benchmark input inventory")
    return result


def render_input(item: Input) -> str:
    id = item.canonical_id
    return MARKER + f'''import {item.module}
import Whiel.Synthesis.Runtime.FixedAmbientRegistry.Support

/- Typed registration derived from the authoritative Input. -/

namespace Whiel
namespace Synthesis
namespace Runtime
namespace FixedAmbientRegistry
namespace {id}

open Benchmark.{id}

/- Canonical input identity: the digest covers the five declarations. -/
def canonicalId : String :=
  "{id}"

def identity : TaskIdentity where
  canonicalId := canonicalId
  moduleName := "{item.module}"
  namespaceName :=
    "{item.namespace}"
  sourceSha256 :=
    "{item.sha256[:32]}" ++
      "{item.sha256[32:]}"
  semanticVersion := 1
  encodingVersion := 1

/- Evaluated over the computed preprocessing schema. -/
def manifest : BoundTaskManifest :=
  liftedTaskJson% identity,
    {item.namespace}.inputPre,
    {item.namespace}.inputCmd,
    {item.namespace}.inputPost,
    {item.namespace}.inputPreproc

/- Registration uses the production preprocessing path. -/
theorem inputPreproc_eq_preprocess :
    inputPreproc =
      Hoare.preprocess inputPre inputCmd inputPost := by
  rfl

/- All typed worker operations use the shared constructor. -/
def entry : Entry :=
  Entry.ofInput identity manifest inputPreproc

end {id}
end FixedAmbientRegistry
end Runtime
end Synthesis
end Whiel
''' + END


def expected_files(inputs: list[Input]) -> dict[Path, str]:
    result = {OUTPUT / "Generated" / f"{item.canonical_id}.lean": render_input(item)
              for item in inputs}
    aggregate = MARKER
    aggregate += "".join(f"import Whiel.Synthesis.Runtime.FixedAmbientRegistry.Generated.{item.canonical_id}\n"
                         for item in inputs)
    aggregate += '''
/- Current generated inventory, in canonical directory order. -/
namespace Whiel.Synthesis.Runtime.FixedAmbientRegistry

def entries : List Entry :=
'''
    aggregate += "  [" + ",\n    ".join(f"{item.canonical_id}.entry" for item in inputs) + "]\n\n"
    aggregate += "end Whiel.Synthesis.Runtime.FixedAmbientRegistry\n" + END
    result[OUTPUT / "Generated.lean"] = aggregate
    return result


def fidelity_module(directory: Path) -> bool:
    module = directory / "Fidelity" / f"{directory.name}.lean"
    if module.is_symlink():
        raise RegistryError(f"symlink refused: {module}")
    return module.is_file()


def fidelity_root(inputs: list[Input]) -> str:
    """Root of the compiler-fidelity proofs; built apart from the library."""
    return MARKER + "".join(
        f"import Benchmark.{item.canonical_id}.Fidelity.{item.canonical_id}\n"
        for item in inputs if item.fidelity) + END


def certificate_imports(inputs: list[Input], outside: bool) -> str:
    return "".join(f"import Benchmark.{item.canonical_id}.Certificate.{name}\n"
                   for name in CERTIFICATE_MODULES for item in inputs
                   if item.outside == outside and name in item.certificates)


def inputs_root(inputs: list[Input]) -> str:
    return MARKER + "".join(f"import {item.module}\n" for item in inputs) + END


def certificates_root(inputs: list[Input]) -> str:
    """Every emitter certificate that fits the watched build."""
    return MARKER + certificate_imports(inputs, outside=False) + END


def outside_root(inputs: list[Input]) -> str:
    """Certificates too heavy for the watched library build; built on their own."""
    return MARKER + certificate_imports(inputs, outside=True) + END


def round_trip_modules(inputs: list[Input], base: Path, imported: str, command: str,
                       purpose: str) -> dict[Path, str]:
    """One round-trip module per input under `base`/Cases, and their aggregate."""
    result = {}
    module = ".".join(base.parts)
    for item in inputs:
        result[base / "Cases" / f"{item.canonical_id}.lean"] = MARKER + f"""import {item.module}
import {imported}

/- {purpose} -/

open Whiel.Synthesis.Tests.BenchmarkNotationRoundTrip

set_option linter.hashCommand false
set_option linter.style.setOption false
set_option maxRecDepth 16384
set_option maxHeartbeats 4000000

{command} {item.namespace}
""" + END
    result[Path(str(base) + "Cases.lean")] = MARKER + "".join(
        f"import {module}.Cases.{item.canonical_id}\n" for item in inputs) + END
    return result


def round_trip_files(inputs: list[Input]) -> dict[Path, str]:
    """The source triple and the preprocessed loop of every input round trip.

    The source side is cheap and belongs to the test root. The preprocessed
    side, the loop and prophecy schema a proposer is shown, costs up to minutes
    per input and is built as its own target.
    """
    result = round_trip_modules(
        inputs, ROUND_TRIP, "Whiel.Synthesis.Tests.BenchmarkNotationRoundTrip", "#roundTrip",
        "The printed input re-reads as the declared input.")
    result.update(round_trip_modules(
        inputs, PREPROC_ROUND_TRIP, "Whiel.Synthesis.Tests.BenchmarkPreprocRoundTrip",
        "#roundTripPreproc", "The printed preprocessed loop re-reads as the computed one."))
    return result


def case_audit(inputs: list[Input]) -> str:
    text = MARKER + """import Whiel.Synthesis.Runtime.FixedAmbientRegistry

/- Axiom audit of the registry assembly: one preprocessing theorem
   per registered entry. -/
"""
    for item in inputs:
        name = ("Whiel.Synthesis.Runtime.FixedAmbientRegistry."
                f"{item.canonical_id}.inputPreproc_eq_preprocess")
        text += f"""
/-- info: '{name}' depends on axioms: [propext,
 Classical.choice,
 Quot.sound] -/
#guard_msgs (whitespace := lax) in
#print axioms
  {name}
"""
    return text + END


def generate(root: Path, check: bool = False, ids: list[str] | None = None) -> list[str]:
    inputs = discover(root)
    if ids is not None:
        if not ids or len(ids) != len(set(ids)):
            raise RegistryError("empty or duplicate explicit selection")
        missing = set(ids) - {item.canonical_id for item in inputs}
        if missing:
            raise RegistryError(f"unknown selected ids: {sorted(missing)}")
        inputs = [item for item in inputs if item.canonical_id in ids]
    expected = expected_files(inputs)
    expected.update(round_trip_files(inputs))
    singles = {}
    if ids is None:
        singles = {INPUTS_ROOT: inputs_root(inputs), CERTIFICATES_ROOT: certificates_root(inputs),
                   CASE_AUDIT: case_audit(inputs), FIDELITY_ROOT: fidelity_root(inputs),
                   OUTSIDE_ROOT: outside_root(inputs)}
    # Validate the entire managed tree before any writes or removals.
    for parent in reversed((root / OUTPUT / "Generated").parents):
        if parent == root or root in parent.parents:
            if parent.is_symlink():
                raise RegistryError(f"symlink refused: {parent}")
    existing = set()
    for managed in (root / OUTPUT / "Generated", root / ROUND_TRIP / "Cases",
                    root / PREPROC_ROUND_TRIP / "Cases"):
        if managed.exists() or managed.is_symlink():
            require_plain(managed, directory=True)
            for path in managed.iterdir():
                require_plain(path)
                if path.suffix != ".lean" or not SAFE_ID.fullmatch(path.stem):
                    raise RegistryError(f"unknown generated file: {path}")
                existing.add(path.relative_to(root))
    for aggregate in (root / OUTPUT / "Generated.lean", root / (str(ROUND_TRIP) + "Cases.lean"),
                      root / (str(PREPROC_ROUND_TRIP) + "Cases.lean")):
        if aggregate.exists() or aggregate.is_symlink():
            require_plain(aggregate)
            existing.add(aggregate.relative_to(root))
    for relative in sorted(existing):
        text = (root / relative).read_text()
        if not text.startswith(MARKER) or not text.endswith(END) or text.count(MARKER) != 1 or text.count(END) != 1:
            raise RegistryError(f"unknown generated-region format: {relative}")
    for relative in singles:
        path = root / relative
        if path.is_symlink():
            raise RegistryError(f"symlink refused: {path}")
        if path.exists():
            require_plain(path)
            existing.add(relative)
    expected.update(singles)
    stale = sorted(existing - expected.keys())
    changed = sorted(path for path, text in expected.items()
                     if path not in existing or (root / path).read_text() != text)
    if check and (stale or changed):
        raise RegistryError("generated registry is stale: " + ", ".join(map(str, stale + changed)))
    if not check:
        for relative in changed:
            path = root / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected[relative])
        for relative in stale:
            (root / relative).unlink()
    return [item.canonical_id for item in inputs]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--ids", nargs="+", help="explicit transitional development subset")
    args = parser.parse_args()
    try:
        ids = generate(ROOT, args.check, args.ids)
    except (RegistryError, OSError, UnicodeError) as error:
        print(f"registry generation failed: {error}", file=sys.stderr)
        return 1
    print(f"{'checked' if args.check else 'generated'} {len(ids)} typed registrations")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
