//! Unit tests for the AVATAR kernel-SAT rewrite.
//!
//! The fixture is the captured `casc_2025` AVATAR block of an
//! `init_clause_0` leancheck run, trailing emitter whitespace included, so
//! the pinned shape is exercised exactly as the emitter prints it. The
//! expected rewritten block and the LRAT trace below are the legacy
//! Python's own output for that block (differential parity fixture:
//! `rewrite_avatar_kernel_sat` plus the pinned CaDiCaL).

use super::*;
use std::os::unix::fs::PermissionsExt;
use std::time::{SystemTime, UNIX_EPOCH};

/// The captured AVATAR block, byte for byte. Note the trailing space the
/// emitter leaves after the `have satProof :=` application.
pub(crate) const AVATAR_BLOCK: &str = concat!(
    "-- step 199 avatar sat refutation\n",
    "set_option maxHeartbeats 200000000 in\n",
    "-- this is probably due to a suboptimal encoding\n",
    "theorem inf_s199' (sA2' sA3' sA15' : Bool) : (sA2' || sA3') → (sA15') → \
     (!sA2' || !sA15') → (!sA3') → False := by\n",
    "  intro h\n",
    "  bv_decide\n",
    "\n",
    "theorem inf_s199 : (sA2 ∨ sA3) → (sA15) → ((¬sA2) ∨ (¬sA15)) → ((¬sA3)) → False := by\n",
    "  classical\n",
    "  have satProof := inf_s199' (decide sA2) (decide sA3) (decide sA15) \n",
    "  rewrite_decide_eq [sA2 sA3 sA15 ]\n",
    "  sat_norm\n",
    "  exact satProof\n",
);

/// The trace the pinned CaDiCaL produces for this block's DIMACS.
pub(crate) const LRAT_TRACE: &str = "5 -1 0 2 3 0\n5 d 3 0\n6 2 0 5 1 0\n7 0 6 4 0\n";

const EXPECTED_DIMACS: &str = "p cnf 3 4\n1 2 0\n3 0\n-1 -3 0\n-2 0\n";

/// The legacy Python's rendered replacement, byte for byte.
const EXPECTED_BLOCK: &str = concat!(
    "-- step 199 avatar sat refutation via kernel-checked LRAT\n",
    "lrat_proof inf_s199_lrat\n",
    "  \"p cnf 3 4\\n1 2 0\\n3 0\\n-1 -3 0\\n-2 0\\n\"\n",
    "  \"5 -1 0 2 3 0\\n5 d 3 0\\n6 2 0 5 1 0\\n7 0 6 4 0\\n\"\n",
    "\n",
    "theorem inf_s199 : (sA2 ∨ sA3) → (sA15) → ((¬sA2) ∨ (¬sA15)) → ((¬sA3)) → False := by\n",
    "  intro h1 h2 h3 h4\n",
    "  have h := inf_s199_lrat sA2 sA3 sA15\n",
    "  exact (fun hs => Or.elim hs (fun hs => Or.elim hs (fun hf => Or.elim h1 hf.1 \
     (fun hr => hf.2 hr)) (fun hf => hf h2)) (fun hs => Or.elim hs (fun hf => Or.elim h3 \
     (fun hn => hn hf.1) (fun hr => (fun hn => hn hf.2) hr)) (fun hf => (fun hn => hn hf) h4))) h\n",
);

/// A whole raw leancheck proof around `body`, in the emitted shape.
pub(crate) fn raw_proof(body: &str) -> String {
    format!(
        concat!(
            "-- Lean proof output generated by Vampire\n",
            "import VampLean\n",
            "section vamproof\n",
            "universe u\n",
            "set_option maxHeartbeats 0\n",
            "set_option maxRecDepth 100000000\n",
            "variable {{sA2 sA3 sA15 : Prop}}\n",
            "\n",
            "{}",
            "\n",
            "theorem fullProof : True := by\n",
            "  trivial\n",
            "\n",
            "end vamproof\n",
        ),
        body
    )
}

fn recorded() -> RecordedLratSolver {
    RecordedLratSolver::new(vec![(199, LRAT_TRACE.to_string())])
}

fn transform(raw: &str) -> Result<KernelSatTransform, KernelSatError> {
    transform_avatar_kernel_sat(raw, "init_clause_0", &recorded())
}

// ------------------------------------------------------------
// The Pinned Shape
// ------------------------------------------------------------

#[test]
fn plans_the_captured_avatar_shape() {
    let problems = plan_avatar_kernel_sat(&raw_proof(AVATAR_BLOCK), "init_clause_0").unwrap();
    assert_eq!(problems.len(), 1);
    let problem = &problems[0];
    assert_eq!(problem.step_id, 199);
    assert_eq!(problem.kind, AvatarKind::Sat);
    assert_eq!(problem.variable_ids, vec![2, 3, 15]);
    assert_eq!(
        problem.clauses,
        vec![
            vec![(2, true), (3, true)],
            vec![(15, true)],
            vec![(2, false), (15, false)],
            vec![(3, false)],
        ]
    );
    assert_eq!(problem.cnf_source, EXPECTED_DIMACS);
}

#[test]
fn prepared_traces_require_the_exact_cnf_and_step() {
    let problem = plan_avatar_kernel_sat(&raw_proof(AVATAR_BLOCK), "init_clause_0")
        .unwrap()
        .remove(0);
    let solver = PreparedLratSolver::new(vec![(problem.clone(), LRAT_TRACE.to_string())]);
    assert_eq!(
        solver.refute(problem.step_id, &problem.cnf_source).unwrap(),
        LRAT_TRACE
    );
    assert!(
        solver
            .refute(problem.step_id + 1, &problem.cnf_source)
            .is_err()
    );
    assert!(solver.refute(problem.step_id, "p cnf 0 0\n").is_err());
}

#[test]
fn native_plan_does_not_resolve_an_embedded_trace_again() {
    let raw = raw_proof(AVATAR_BLOCK);
    assert_eq!(
        plan_native_avatar_kernel_sat(&raw, "init_clause_0")
            .unwrap()
            .len(),
        1
    );
    let rewritten = transform(&raw).unwrap();
    assert!(
        plan_native_avatar_kernel_sat(&rewritten.text, "init_clause_0")
            .unwrap()
            .is_empty()
    );
}

#[test]
fn a_proof_without_avatar_is_returned_unchanged() {
    let raw = raw_proof("theorem inf_s1 : True := by\n  trivial\n");
    let outcome = transform(&raw).unwrap();
    assert_eq!(outcome.outcome, KernelSatOutcome::NoHelpers);
    assert_eq!(outcome.text, raw);
    assert!(outcome.helpers.is_empty());
    assert!(outcome.probe_source.is_none());
    assert!(!outcome.requires_from_lrat_import());
}

#[test]
fn native_closers_without_avatar_markers_fail_closed() {
    for closer in ["bv_decide", "native_decide"] {
        let raw = raw_proof(&format!("theorem unused : True := by\n  {closer}\n"));
        let error = transform(&raw).unwrap_err();
        assert!(
            error.to_string().contains(&format!("executable {closer}")),
            "{error}"
        );
    }
}

#[test]
fn unpaired_lrat_without_avatar_markers_fails_closed() {
    for body in [
        "lrat_proof inf_s199_lrat\n  \"p cnf 0 1\\n0\\n\"\n  \"1 0 0\\n\"\n",
        "def trace := include_str \"external.lrat\"\n",
        "theorem inf_s199' : True := by\n  trivial\n",
    ] {
        let error = transform(&raw_proof(body)).unwrap_err();
        assert!(error.to_string().contains("unpaired"), "{error}");
    }
}

#[test]
fn helper_tokens_in_comments_and_strings_do_not_require_avatar_markers() {
    let raw = raw_proof(concat!(
        "-- bv_decide and native_decide are forbidden tactics\n",
        "/- lrat_proof inf_s199_lrat -/\n",
        "def note := \"native_decide include_str lrat_proof\"\n",
    ));
    let outcome = transform(&raw).unwrap();
    assert_eq!(outcome.outcome, KernelSatOutcome::NoHelpers);
    assert_eq!(outcome.text, raw);
}

// ------------------------------------------------------------
// Differential Parity With The Legacy Python
// ------------------------------------------------------------

#[test]
fn rewrites_the_captured_block_exactly_as_the_legacy_python_does() {
    let outcome = transform(&raw_proof(AVATAR_BLOCK)).unwrap();
    assert_eq!(outcome.outcome, KernelSatOutcome::Applied);
    assert!(outcome.text.contains(EXPECTED_BLOCK));
    assert!(!outcome.text.contains("bv_decide"));
    assert!(outcome.requires_from_lrat_import());

    let helper = &outcome.helpers[0];
    assert_eq!(helper.lrat_source, LRAT_TRACE);
    assert_eq!(helper.lrat_additions, 3);
    assert_eq!(helper.lrat_deletions, 1);
    assert_eq!(helper.lrat_max_clause_id, 7);
}

#[test]
fn the_rewritten_proof_asks_for_the_import_rather_than_writing_it() {
    // `packageProof` takes the extra import as a payload and inserts it
    // after its own `import VampLean`, so the rewritten text must carry no
    // import line of its own.
    let outcome = transform(&raw_proof(AVATAR_BLOCK)).unwrap();
    assert!(outcome.requires_from_lrat_import());
    assert!(!outcome.text.contains(&format!("import {FROM_LRAT_IMPORT}")));
    assert_eq!(
        outcome
            .text
            .split('\n')
            .filter(|line| line.trim_start().starts_with("import "))
            .collect::<Vec<_>>(),
        ["import VampLean"]
    );
}

#[test]
fn the_probe_declares_and_audits_every_helper_in_isolation() {
    let outcome = transform(&raw_proof(AVATAR_BLOCK)).unwrap();
    let probe = outcome.probe_source.unwrap();
    assert!(probe.starts_with(&format!("import {FROM_LRAT_IMPORT}")));
    assert!(probe.contains("namespace KernelSatStep199"));
    assert!(probe.contains("variable (sA2 sA3 sA15 : Prop)"));
    assert!(probe.contains("#print axioms inf_s199_lrat"));
    assert!(probe.contains("#print axioms inf_s199"));
    assert!(probe.contains(EXPECTED_BLOCK));
}

#[test]
fn an_already_rewritten_proof_is_returned_unchanged() {
    let first = transform(&raw_proof(AVATAR_BLOCK)).unwrap();
    // The solver must never be consulted again: an empty recording would
    // fail if it were.
    let solver = RecordedLratSolver::new(Vec::new());
    let second = transform_avatar_kernel_sat(&first.text, "init_clause_0", &solver).unwrap();
    assert_eq!(second.outcome, KernelSatOutcome::AlreadyApplied);
    assert_eq!(second.text, first.text);
    assert_eq!(second.helpers, first.helpers);
}

#[test]
fn an_altered_embedded_proof_term_fails_closed() {
    let first = transform(&raw_proof(AVATAR_BLOCK)).unwrap();
    let altered = first
        .text
        .replace("  intro h1 h2 h3 h4", "  intro h1 h2 h3 h4 h5");
    let solver = RecordedLratSolver::new(Vec::new());
    let error = transform_avatar_kernel_sat(&altered, "init_clause_0", &solver).unwrap_err();
    assert!(matches!(error, KernelSatError::Shape(_)), "{error}");
    assert!(
        error
            .to_string()
            .contains("embedded LRAT bridge was altered")
    );
}

// ------------------------------------------------------------
// Fail-Closed Shape Checks
// ------------------------------------------------------------

#[test]
fn a_truncated_helper_fails_closed() {
    let truncated: String = AVATAR_BLOCK
        .split_inclusive('\n')
        .take(6)
        .collect::<String>();
    let error = transform(&raw_proof(&truncated)).unwrap_err();
    assert!(matches!(error, KernelSatError::Shape(_)), "{error}");
}

#[test]
fn a_changed_boolean_closer_fails_closed() {
    let changed = AVATAR_BLOCK.replace("  bv_decide", "  decide");
    let error = transform(&raw_proof(&changed)).unwrap_err();
    assert!(
        error.to_string().contains("unexpected Boolean closer"),
        "{error}"
    );
}

#[test]
fn mismatched_boolean_and_prop_clauses_fail_closed() {
    let changed = AVATAR_BLOCK.replace("(sA15) →", "(sA3) →");
    let error = transform(&raw_proof(&changed)).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("Boolean and Prop clauses differ"),
        "{error}"
    );
}

#[test]
fn a_duplicated_avatar_step_fails_closed() {
    let doubled = format!("{AVATAR_BLOCK}\n{AVATAR_BLOCK}");
    let error = transform(&raw_proof(&doubled)).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("repeats an AVATAR refutation step"),
        "{error}"
    );
}

#[test]
fn an_unrecognized_avatar_marker_fails_closed() {
    let changed = AVATAR_BLOCK.replace(
        "-- step 199 avatar sat refutation",
        "-- step 199 avatar native refutation",
    );
    let error = transform(&raw_proof(&changed)).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("unrecognized AVATAR refutation marker"),
        "{error}"
    );
}

#[test]
fn a_native_closer_outside_a_helper_fails_closed() {
    let body = format!("{AVATAR_BLOCK}\ntheorem other : True := by\n  bv_decide\n");
    let error = transform(&raw_proof(&body)).unwrap_err();
    assert!(
        error
            .to_string()
            .contains("executable bv_decide outside a pinned AVATAR helper"),
        "{error}"
    );
}

#[test]
fn noncanonical_boolean_binders_fail_closed() {
    let changed = AVATAR_BLOCK.replace("(sA2' sA3' sA15' : Bool)", "(sA3' sA2' sA15' : Bool)");
    let error = transform(&raw_proof(&changed)).unwrap_err();
    assert!(
        error.to_string().contains("noncanonical Boolean variables"),
        "{error}"
    );
}

// ------------------------------------------------------------
// LRAT Validation
// ------------------------------------------------------------

fn problem() -> KernelSatProblem {
    plan_avatar_kernel_sat(&raw_proof(AVATAR_BLOCK), "init_clause_0")
        .unwrap()
        .remove(0)
}

fn validate(trace: &str) -> Result<ValidatedKernelSat, KernelSatError> {
    validate_lrat(problem(), trace, "init_clause_0")
}

#[test]
fn a_rat_hint_is_an_unsupported_miss_not_an_acceptance() {
    // The same trace with a RAT group appended to the first addition's
    // hints: well formed, outside the accepted RUP-only fragment.
    let trace = "5 -1 0 2 3 -1 2 0\n6 2 0 5 1 0\n7 0 6 4 0\n";
    let error = validate(trace).unwrap_err();
    assert!(matches!(error, KernelSatError::Unsupported(_)), "{error}");
    assert!(error.to_string().contains("requires RAT hints"));
}

#[test]
fn a_nonsequential_addition_fails_closed() {
    let error = validate("6 -1 0 2 3 0\n7 2 0 6 1 0\n8 0 7 4 0\n").unwrap_err();
    assert!(
        error.to_string().contains("nonsequential LRAT addition"),
        "{error}"
    );
}

#[test]
fn trailing_tokens_after_the_hints_fail_closed() {
    let error = validate("5 -1 0 2 3 0 9\n").unwrap_err();
    assert!(
        error.to_string().contains("trailing LRAT tokens"),
        "{error}"
    );
}

#[test]
fn a_trace_without_an_empty_clause_fails_closed() {
    let error = validate("5 -1 0 2 3 0\n").unwrap_err();
    assert!(
        error
            .to_string()
            .contains("does not end in exactly one empty-clause proof"),
        "{error}"
    );
}

#[test]
fn steps_after_the_empty_clause_fail_closed() {
    let error = validate("5 0 1 2 3 4 0\n6 -1 0 2 3 0\n").unwrap_err();
    assert!(
        error
            .to_string()
            .contains("LRAT steps after the empty clause"),
        "{error}"
    );
}

#[test]
fn a_hint_naming_a_deleted_clause_fails_closed() {
    let error = validate("5 -1 0 2 3 0\n5 d 3 0\n6 2 0 5 3 0\n7 0 6 4 0\n").unwrap_err();
    assert!(error.to_string().contains("invalid RUP hint"), "{error}");
}

#[test]
fn a_trace_that_is_not_canonical_text_fails_closed() {
    assert!(validate("5 -1 0 2 3 0").is_err());
    assert!(validate("5 -1 0 2 3 0\r\n7 0 6 4 0\n").is_err());
    assert!(validate("").is_err());
    assert!(validate("5 –1 0 2 3 0\n").is_err());
}

#[test]
fn a_deletion_that_is_not_at_the_current_step_fails_closed() {
    let error = validate("5 -1 0 2 3 0\n4 d 3 0\n6 2 0 5 1 0\n7 0 6 4 0\n").unwrap_err();
    assert!(
        error.to_string().contains("malformed LRAT deletion line"),
        "{error}"
    );
}

#[test]
fn a_literal_outside_the_variable_range_fails_closed() {
    let error = validate("5 -9 0 2 3 0\n6 2 0 5 1 0\n7 0 6 4 0\n").unwrap_err();
    assert!(error.to_string().contains("invalid LRAT clause"), "{error}");
}

// ------------------------------------------------------------
// Name Qualification (Transformation 6)
// ------------------------------------------------------------

#[test]
fn executable_collisions_are_qualified_and_comments_are_not() {
    let source = concat!(
        "-- imp_iff_not_or in a comment stays\n",
        "theorem t : True := by\n",
        "  simp only [imp_iff_not_or, not_and_or, Xor', not_imp_not]\n",
        "  exact trivial\n",
        "-- \"not_and_or\" quoted inside a comment stays\n",
    );
    let qualified = qualify_lrat_collisions(source, "init_clause_0").unwrap();
    assert!(qualified.contains(
        "  simp only [VampLean.imp_iff_not_or, VampLean.not_and_or, VampLean.Xor', \
         VampLean.not_imp_not]"
    ));
    assert!(qualified.contains("-- imp_iff_not_or in a comment stays"));
    assert!(qualified.contains("-- \"not_and_or\" quoted inside a comment stays"));
}

#[test]
fn already_qualified_occurrences_are_left_alone() {
    let source = "theorem t : True := by\n  simp only [VampLean.not_and_or]\n  exact trivial\n";
    assert_eq!(
        qualify_lrat_collisions(source, "init_clause_0").unwrap(),
        source
    );
}

#[test]
fn a_longer_name_containing_a_collision_is_not_qualified() {
    let source = "theorem t : True := by\n  simp only [my_not_and_or, not_and_ore]\n";
    assert_eq!(
        qualify_lrat_collisions(source, "init_clause_0").unwrap(),
        source
    );
}

#[test]
fn a_quoted_collision_spelling_fails_closed() {
    let source = "theorem t : True := by\n  exact «not_and_or»\n";
    let error = qualify_lrat_collisions(source, "init_clause_0").unwrap_err();
    assert!(
        error.to_string().contains("quotes LRAT/VampLean collision"),
        "{error}"
    );
}

#[test]
fn a_redeclared_collision_fails_closed() {
    let source = "theorem not_imp_not : True := trivial\n";
    let error = qualify_lrat_collisions(source, "init_clause_0").unwrap_err();
    assert!(
        error
            .to_string()
            .contains("redeclares LRAT/VampLean collision"),
        "{error}"
    );
}

#[test]
fn a_foreign_qualification_of_a_collision_fails_closed() {
    let source = "theorem t : True := by\n  exact Mathlib.not_and_or\n";
    let error = qualify_lrat_collisions(source, "init_clause_0").unwrap_err();
    assert!(
        error
            .to_string()
            .contains("retained externally qualified LRAT/VampLean collision"),
        "{error}"
    );
}

#[test]
fn qualification_runs_over_the_whole_rewritten_proof() {
    let body = format!("{AVATAR_BLOCK}\ntheorem u : True := by\n  simp only [not_and_or]\n");
    let outcome = transform(&raw_proof(&body)).unwrap();
    assert!(outcome.text.contains("simp only [VampLean.not_and_or]"));
}

// ------------------------------------------------------------
// Rendering Details
// ------------------------------------------------------------

#[test]
fn a_unit_clause_uses_the_whole_falsification() {
    assert_eq!(falsification_access(1, 0), "hf");
}

#[test]
fn a_wide_clause_walks_the_falsification_tuple() {
    assert_eq!(falsification_access(3, 0), "hf.1");
    assert_eq!(falsification_access(3, 1), "hf.2.1");
    assert_eq!(falsification_access(3, 2), "hf.2.2");
}

#[test]
fn json_strings_match_the_python_rendering() {
    assert_eq!(json_string("p cnf 1 1\n1 0\n"), "\"p cnf 1 1\\n1 0\\n\"");
    assert_eq!(json_string("a\"b\\c"), "\"a\\\"b\\\\c\"");
}

// ------------------------------------------------------------
// The Pinned CaDiCaL Seam
// ------------------------------------------------------------

/// A scratch root holding a fake `cadical` that runs `script`, and a solver
/// pointed at it.
///
/// Modelled on the lock reader's fake-binary fixtures in `leancheck.rs`:
/// the exit-code contract is this seam's whole decision, so it is exercised
/// against a scripted binary rather than the pinned one. The script sees the
/// DIMACS path as `$1` and the trace path it is expected to write as `$2`.
fn fake_cadical(label: &str, script: &str) -> (PathBuf, CadicalLratSolver) {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!(
        "whiel_lrat_cadical_{label}_{}_{nanos}",
        std::process::id()
    ));
    std::fs::create_dir_all(&root).unwrap();
    let executable = root.join("cadical");
    std::fs::write(&executable, script).unwrap();
    let mut permissions = std::fs::metadata(&executable).unwrap().permissions();
    permissions.set_mode(0o755);
    std::fs::set_permissions(&executable, permissions).unwrap();
    let solver = CadicalLratSolver::new(executable, vec!["--lrat".to_string()], root.join("work"));
    (root, solver)
}

#[test]
fn exit_twenty_reads_back_the_written_trace() {
    let (root, solver) = fake_cadical(
        "unsat",
        "#!/bin/sh\nprintf '5 -1 0 2 3 0\\n' > \"$2\"\nexit 20\n",
    );
    assert_eq!(
        solver.refute(199, EXPECTED_DIMACS).unwrap(),
        "5 -1 0 2 3 0\n"
    );
    std::fs::remove_dir_all(&root).unwrap();
}

#[test]
fn a_satisfiable_clause_set_is_a_shape_error_not_a_solver_fault() {
    // Exit 10 is a model: the emitted helper was never a refutation, which
    // is a fact about the proof text, not a fault of the solver.
    let (root, solver) = fake_cadical("sat", "#!/bin/sh\nexit 10\n");
    let error = solver.refute(199, EXPECTED_DIMACS).unwrap_err();
    assert!(matches!(error, KernelSatError::Shape(_)), "{error}");
    assert!(
        error
            .to_string()
            .contains("AVATAR step 199 clause set is satisfiable"),
        "{error}"
    );
    std::fs::remove_dir_all(&root).unwrap();
}

#[test]
fn any_other_exit_code_is_a_solver_fault() {
    let (root, solver) = fake_cadical("fault", "#!/bin/sh\nexit 1\n");
    let error = solver.refute(199, EXPECTED_DIMACS).unwrap_err();
    assert!(matches!(error, KernelSatError::Solver(_)), "{error}");
    assert!(
        error.to_string().contains("CaDiCaL exited with Some(1)"),
        "{error}"
    );
    std::fs::remove_dir_all(&root).unwrap();
}

#[test]
fn exit_twenty_without_a_trace_file_is_a_solver_fault() {
    let (root, solver) = fake_cadical("unsat_no_trace", "#!/bin/sh\nexit 20\n");
    let error = solver.refute(199, EXPECTED_DIMACS).unwrap_err();
    assert!(matches!(error, KernelSatError::Solver(_)), "{error}");
    assert!(error.to_string().contains("proof.lrat"), "{error}");
    std::fs::remove_dir_all(&root).unwrap();
}

#[test]
fn concurrent_same_step_calls_read_only_their_own_input_and_trace() {
    let (root, solver) = fake_cadical(
        "same-step",
        r#"#!/bin/sh
root=$(dirname "$0")
printf '%s\n' "$PWD" >> "$root/started"
while [ ! -e "$root/release" ]; do sleep 0.01; done
cat "$1" > "$2"
exit 20
"#,
    );
    let solver = std::sync::Arc::new(solver);
    let threads: Vec<_> = ["first CNF\n", "second CNF\n"]
        .into_iter()
        .map(|input| {
            let solver = solver.clone();
            std::thread::spawn(move || (input, solver.refute(199, input)))
        })
        .collect();
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
    let count = loop {
        let count = std::fs::read_to_string(root.join("started"))
            .unwrap_or_default()
            .lines()
            .count();
        if count == 2 || std::time::Instant::now() >= deadline {
            break count;
        }
        std::thread::sleep(std::time::Duration::from_millis(5));
    };
    // Release even on a timeout so failed assertions cannot strand a child.
    std::fs::write(root.join("release"), b"go").unwrap();
    let results: Vec<_> = threads
        .into_iter()
        .map(|thread| thread.join().unwrap())
        .collect();
    assert_eq!(count, 2, "both children reached the controlled overlap");
    for (input, result) in results {
        assert_eq!(result.unwrap(), input);
    }
    let started = std::fs::read_to_string(root.join("started")).unwrap();
    let directories: std::collections::BTreeSet<_> = started.lines().collect();
    assert_eq!(directories.len(), 2);
    for directory in directories {
        assert_eq!(
            std::fs::read(Path::new(directory).join("input.cnf")).unwrap(),
            std::fs::read(Path::new(directory).join("proof.lrat")).unwrap()
        );
    }
    std::fs::remove_dir_all(root).unwrap();
}

#[test]
fn repeated_step_retains_prior_evidence_and_cannot_reuse_a_stale_trace() {
    let (root, solver) = fake_cadical(
        "repeat-step",
        r#"#!/bin/sh
if [ "$(cat "$1")" = "good" ]; then printf 'good trace\n' > "$2"; fi
exit 20
"#,
    );
    assert_eq!(solver.refute(199, "good\n").unwrap(), "good trace\n");
    let first = std::fs::read_dir(root.join("work"))
        .unwrap()
        .next()
        .unwrap()
        .unwrap()
        .path();
    assert!(solver.refute(199, "bad\n").is_err());
    assert_eq!(
        std::fs::read_to_string(first.join("input.cnf")).unwrap(),
        "good\n"
    );
    assert_eq!(
        std::fs::read_to_string(first.join("proof.lrat")).unwrap(),
        "good trace\n"
    );
    assert_eq!(solver.refute(199, "good\n").unwrap(), "good trace\n");
    assert_eq!(std::fs::read_dir(root.join("work")).unwrap().count(), 3);
    std::fs::remove_dir_all(root).unwrap();
}
