-- Author: Jesse Comer
import Databases.RelCalc.CQ.ToInstance
import Databases.UnnamedModel.Homomorphism
import Mathlib.Algebra.BigOperators.Group.Finset.Defs

/-
  This file records minimization-oriented notions for
  equality-free conjunctive queries represented as ordinary
  RelCalc queries.

  Key definitions include:
    * `RelCalc.Query.Equivalent`
    * `RelCalc.Query.AtomMinimal`
    * `RelCalc.Query.IsMinimized`

  Core- and homomorphism-based consequences use
  `RelCalc.Query.chandra_merlin`.
-/

------------------------------------------------------------
-- Atom Counts
------------------------------------------------------------

namespace RelCalc

namespace Formula

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]
variable {Γ : UnnamedSchema A}

/- Number of relation-atom occurrences in a formula. -/
def relAtomCount : Formula D Γ → Nat
| .rel _ => 1
| .and φ ψ => relAtomCount φ + relAtomCount ψ
| .or φ ψ => relAtomCount φ + relAtomCount ψ
| .imp φ ψ => relAtomCount φ + relAtomCount ψ
| .iff φ ψ => relAtomCount φ + relAtomCount ψ
| .not φ => relAtomCount φ
| .forall_ _ φ => relAtomCount φ
| .exists_ _ φ => relAtomCount φ
| .top => 0
| .bot => 0
| .eq _ _ => 0

end Formula

namespace Query

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]
variable {Γ : UnnamedSchema A}
variable {n : Nat}

/- Number of relation-atom occurrences in a query. -/
def atomCount
    (q : Query D Γ n) : Nat :=
  q.form.relAtomCount

/- Number of canonical facts generated by a query. -/
def canonicalFactCount
    (q : Query D Γ n) : Nat :=
  Γ.syms.attach.sum
    (fun X => (q.canonicalInstance X).card)

/-
  Raw atom occurrences have no duplicates when the raw count
  agrees with the number of generated canonical facts.
-/
def NoDuplicateRelAtoms
    (q : Query D Γ n) : Prop :=
  q.atomCount = q.canonicalFactCount

instance
    (q : Query D Γ n) :
    Decidable q.NoDuplicateRelAtoms := by
  unfold NoDuplicateRelAtoms
  infer_instance

end Query

end RelCalc

------------------------------------------------------------
-- Equivalence And Minimality
------------------------------------------------------------

namespace RelCalc

namespace Query

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]
variable {Γ : UnnamedSchema A}
variable {n : Nat}

/- Mutual domain-polymorphic containment. -/
def Equivalent
    (q₁ q₂ : Query D Γ n) : Prop :=
  q₁.Contained q₂ ∧ q₂.Contained q₁

/- CQ containment is reflexive. -/
theorem Contained.refl
    (q : Query D Γ n) :
    q.Contained q := by
  intro E _ η
  exact QueryEval.Contained.refl
    (D := E) (Γ := Γ) (n := n)
    (q.mapConstants η)

/- CQ containment is transitive. -/
theorem Contained.trans
    {q₁ q₂ q₃ : Query D Γ n}
    (h₁₂ : q₁.Contained q₂)
    (h₂₃ : q₂.Contained q₃) :
    q₁.Contained q₃ := by
  intro E _ η I t ht
  exact h₂₃ η I (h₁₂ η I ht)

/- Equivalence is reflexive. -/
theorem Equivalent.refl
    (q : Query D Γ n) :
    Equivalent q q :=
  ⟨Contained.refl q, Contained.refl q⟩

/- Equivalence is symmetric. -/
theorem Equivalent.symm
    {q₁ q₂ : Query D Γ n}
    (h : Equivalent q₁ q₂) :
    Equivalent q₂ q₁ :=
  ⟨h.2, h.1⟩

/- Equivalence is transitive. -/
theorem Equivalent.trans
    {q₁ q₂ q₃ : Query D Γ n}
    (h₁₂ : Equivalent q₁ q₂)
    (h₂₃ : Equivalent q₂ q₃) :
    Equivalent q₁ q₃ :=
  ⟨Contained.trans h₁₂.1 h₂₃.1,
    Contained.trans h₂₃.2 h₁₂.2⟩

/-
  Raw atom minimality among equivalent equality-free CQs of
  the same arity.
-/
def AtomMinimal
    (q : Query D Γ n) : Prop :=
  q.IsSafeRelCQ ∧
    ∀ q' : Query D Γ n,
      q'.IsSafeRelCQ →
        Equivalent q q' →
          q.atomCount ≤ q'.atomCount

/-
  A decidable minimization predicate: an equality-free CQ
  with no duplicate relation atoms whose canonical instance
  is a core.
-/
def IsMinimized
    (q : Query D Γ n) : Prop :=
  q.IsSafeRelCQ ∧
    q.NoDuplicateRelAtoms ∧
      Instance.IsCore q.canonicalInstance

instance
    (q : Query D Γ n) :
    Decidable q.IsMinimized := by
  unfold IsMinimized
  infer_instance

/- A core canonical instance yields a minimized CQ. -/
theorem isMinimized_of_canonicalInstance_isCore
    (q : Query D Γ n)
    (hRel : q.IsSafeRelCQ)
    (hNoDup : q.NoDuplicateRelAtoms)
    (hCore : Instance.IsCore q.canonicalInstance) :
    q.IsMinimized :=
  ⟨hRel, hNoDup, hCore⟩

end Query

end RelCalc

------------------------------------------------------------
-- Homomorphism Characterizations
------------------------------------------------------------

namespace RelCalc

namespace Query

variable {A D : Type}
variable [RelationNames A]
variable [Domain D]
variable {Γ : UnnamedSchema A}
variable {n : Nat}

/-
  CQ equivalence is exactly the existence of canonical
  homomorphisms in both directions.
-/
theorem equivalent_iff_canonicalHoms
    (q₁ q₂ : Query D Γ n)
    (h₁ : q₁.IsSafeRelCQ)
    (h₂ : q₂.IsSafeRelCQ) :
    Equivalent q₁ q₂ ↔
      q₂.CanonicalHom q₁ ∧ q₁.CanonicalHom q₂ := by
  unfold Equivalent
  rw [chandra_merlin q₁ q₂ h₁ h₂]
  rw [chandra_merlin q₂ q₁ h₂ h₁]

/- Mutual canonical homomorphisms imply equivalence. -/
theorem equivalent_of_canonicalHoms
    {q₁ q₂ : Query D Γ n}
    (h₁ : q₁.IsSafeRelCQ)
    (h₂ : q₂.IsSafeRelCQ)
    (h₂₁ : q₂.CanonicalHom q₁)
    (h₁₂ : q₁.CanonicalHom q₂) :
    Equivalent q₁ q₂ :=
  (equivalent_iff_canonicalHoms q₁ q₂ h₁ h₂).mpr
    ⟨h₂₁, h₁₂⟩

/- Equivalent CQs have canonical homomorphisms both ways. -/
theorem canonicalHoms_of_equivalent
    {q₁ q₂ : Query D Γ n}
    (h₁ : q₁.IsSafeRelCQ)
    (h₂ : q₂.IsSafeRelCQ)
    (h : Equivalent q₁ q₂) :
    q₂.CanonicalHom q₁ ∧ q₁.CanonicalHom q₂ :=
  (equivalent_iff_canonicalHoms q₁ q₂ h₁ h₂).mp h

end Query

end RelCalc
