-- Author: Jesse Comer
import Databases.Core.Signature

/-
  Finite first-order structures for FOL.

  Key declaration: `FinStruct`.
-/

------------------------------------------------------------
-- Finite First-Order Structures
------------------------------------------------------------

/-
  A finite first-order structure over a finite nonempty
  carrier. Isolated carrier elements are allowed: the
  carrier need not be generated by relation facts or
  function values.
-/
structure FinStruct
    {A F : Type}
    [RelationNames A]
    [FunctionNames F]
    (D : Type)
    [Domain D]
    (Sig : Signature A F) where
  carrier : Finset D
  carrier_nonempty : carrier.Nonempty
  rels :
    (X : Signature.Rel Sig) →
      FinRelation D (Sig.arity X)
  rels_closed :
    ∀ (X : Signature.Rel Sig)
      (t : Tuple D (Sig.arity X)),
      t ∈ rels X → t.isTupleOver carrier
  funcs :
    (f : Signature.Fun Sig) →
      Tuple D (Sig.funArity f) → D
  funcs_closed :
    ∀ (f : Signature.Fun Sig)
      (args : Tuple D (Sig.funArity f)),
      args.isTupleOver carrier →
        funcs f args ∈ carrier

namespace FinStruct

variable {A F D : Type}
variable [RelationNames A]
variable [FunctionNames F]
variable [Domain D]
variable {Sig : Signature A F}

/- Carrier membership as a set predicate. -/
def carrierSet
    (M : FinStruct D Sig) : Set D :=
  fun d => d ∈ M.carrier

/- Relation interpretations are closed under the carrier. -/
def RelClosed
    (carrier : Finset D)
    (rels :
      (X : Signature.Rel Sig) →
        FinRelation D (Sig.arity X)) : Prop :=
  ∀ X : Signature.Rel Sig,
    ∀ t ∈ rels X, t.isTupleOver carrier

instance
    (carrier : Finset D)
    (rels :
      (X : Signature.Rel Sig) →
        FinRelation D (Sig.arity X)) :
    Decidable (RelClosed carrier rels) := by
  unfold RelClosed
  infer_instance

/- Function interpretations are closed under the carrier. -/
def FuncClosed
    (carrier : Finset D)
    (funcs :
      (f : Signature.Fun Sig) →
        Tuple D (Sig.funArity f) → D) : Prop :=
  ∀ f : Signature.Fun Sig,
    ∀ args : Tuple D (Sig.funArity f),
      args.isTupleOver carrier →
      funcs f args ∈ carrier

instance
    (carrier : Finset D)
    (funcs :
      (f : Signature.Fun Sig) →
        Tuple D (Sig.funArity f) → D) :
    Decidable (FuncClosed carrier funcs) := by
  dsimp [FuncClosed]
  let check :=
    ∀ f : Signature.Fun Sig,
      ∀ args ∈ Tuple.allOver carrier (Sig.funArity f),
        funcs f args ∈ carrier
  have hIff : check ↔
      ∀ f : Signature.Fun Sig,
        ∀ args : Tuple D (Sig.funArity f),
          args.isTupleOver carrier →
            funcs f args ∈ carrier := by
    constructor
    · intro h f args hArgs
      exact h f args
        (Tuple.mem_allOver_of_isTupleOver carrier hArgs)
    · intro h f args hArgs
      exact h f args
        (Tuple.isTupleOver_of_mem_allOver carrier hArgs)
  exact decidable_of_iff check hIff

/-
  Try to build a finite structure from raw carrier,
  relation, and function data.
-/
def mk?
    (carrier : Finset D)
    (rels :
      (X : Signature.Rel Sig) →
        FinRelation D (Sig.arity X))
    (funcs :
      (f : Signature.Fun Sig) →
        Tuple D (Sig.funArity f) → D) :
    Option (FinStruct D Sig) :=
  if hNonempty : carrier.Nonempty then
    if hRels : RelClosed carrier rels then
      if hFuncs : FuncClosed carrier funcs then
        some
          { carrier := carrier
            carrier_nonempty := hNonempty
            rels := rels
            rels_closed := by
              intro X t ht
              exact hRels X t ht
            funcs := funcs
            funcs_closed := by
              intro f args hArgs
              exact hFuncs f args hArgs }
      else
        none
    else
      none
  else
    none

instance
    (M : FinStruct D Sig) :
    DecidablePred M.carrierSet := by
  intro d
  unfold carrierSet
  infer_instance

end FinStruct
