-- Running in auto input_syntax mode. Trying TPTP
-- Refutation found. Thanks to Tanya!
-- Lean proof output generated by Vampire
import VampLean
section vamproof
universe u
set_option maxHeartbeats 0
set_option linter.all false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option maxRecDepth 100000000


variable {ι : Type u}
variable [inst : Inhabited ι]
variable {«_f» «_sF0» :  ι → ι → ι}
  {«_g» :  ι → ι}
  {«_p» :  ι → Prop}
-- step 4 ennf transformation
theorem inf_s4 : (¬(∃ v0 v1 : ι,(«_p» («_f» v1 («_g» v0))))) →
  (∀ v0 v1 : ι,(¬(«_p» («_f» v1 («_g» v0))))) := by
  intros h
  ennf_transformation at h<;>
  exact h

-- step 8 definition folding
theorem inf_s8 : (∀ v0 v1 : ι, (¬(«_p» («_f» v1 («_g» v0))))) →
  (∀ v0 v1 : ι, ((«_f» v1 («_g» v0))=(«_sF0» v1 v0))) →
  (∀ v0 v1 : ι, (¬(«_p» («_sF0» v1 v0)))) := by
  intros h0 h1 v0 v1
  have i0 := h0 v0 v1
  have i1 := h1 v0 v1
  grind only

-- step 9 superposition
theorem inf_s9 : (∀ v0 v1 : ι, («_p» («_f» v0 v1))) →
  (∀ v0 v1 : ι, ((«_f» v1 («_g» v0))=(«_sF0» v1 v0))) →
  (∀ v0 v1 : ι, («_p» («_sF0» v0 v1))) := by
  intros h0 h1 v0 v1
  have i0 := h0 v0 («_g» v1)
  have i1 := h1 v1 v0
  grind only [cases Or]

-- step 10 forward subsumption resolution
theorem inf_s10 : (∀ v0 v1 : ι, («_p» («_sF0» v0 v1))) →
  (∀ v0 v1 : ι, (¬(«_p» («_sF0» v1 v0)))) →
  False := by
  intros h0 h1 
  have i0 := h0 default default
  have i1 := h1 default default
  grind only [cases Or]

theorem fullProof : (∀ v0 v1 : ι,(«_p» («_f» v0 v1))) → (∃ v0 v1 : ι,(«_p» («_f» v1 («_g» v0)))) := by
  intros step1 
  apply Classical.byContradiction; intro step3
  have step4 := inf_s4  step3
  have step5 : (∀ v0 v1 : ι, («_p» («_f» v0 v1))) := by
    try simp only
    prenexify at step1<;>
    ac_nf0<;>
    ac_nf at step1

  have step6 : (∀ v0 v1 : ι, (¬(«_p» («_f» v1 («_g» v0))))) := by
    try simp only
    prenexify at step4<;>
    ac_nf0<;>
    ac_nf at step4

  -- step7 function definition
  let «_sF0» v1 v0:= («_f» v1 («_g» v0))
  have step7 : (∀ v0 v1 : ι, ((«_f» v1 («_g» v0))=(«_sF0» v1 v0))) := fun v1 v0 => rfl
  have step8 := inf_s8  step6 step7
  have step9 := inf_s9  step5 step7
  have step10 := inf_s10  step9 step8
  exact step10

end vamproof
-- ------------------------------
-- Version: Vampire 5.0.1 (Release build, commit a9e19dacc on 2026-09-07 00:00:00 +0000)
-- CaDiCaL version: 2.1.3
-- Termination reason: Refutation
-- Time elapsed: 0.0000 s
-- Peak memory usage: 6 MB
-- ------------------------------
-- ------------------------------
