-- Running in auto input_syntax mode. Trying TPTP
-- Refutation found. Thanks to Tanya!
-- Lean proof output generated by Vampire
import VampLean
section vamproof
universe u
set_option maxHeartbeats 0
set_option linter.all false
set_option linter.unusedSectionVars false
set_option linter.unusedTactic false
set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option maxRecDepth 100000000


variable {ι : Type u}
variable [inst : Inhabited ι]
variable {«_sF1» «_sF0» «_g» :  ι → ι}
  {«_f» :  ι → ι → ι}
  {«_p» :  ι → Prop}
-- step 4 ennf transformation
theorem inf_s4 : (¬(∃ v0 v1 : ι,(«_p» («_f» v1 («_g» v0))))) →
  (∀ v0 v1 : ι,(¬(«_p» («_f» v1 («_g» v0))))) := by
  intros h
  ennf_transformation at h<;>
  exact h

-- step 9 definition folding
theorem inf_s9 : (∀ v0 v1 : ι, (¬(«_p» («_f» v1 («_g» v0))))) →
  (∀ v1 : ι, ((«_f» v1 («_sF0»))=(«_sF1»))) →
  (∀ v0 : ι, ((«_g» v0)=(«_sF0»))) →
  ((¬(«_p» («_sF1»)))) := by
  intros h0 h1 h2 
  have i0 := h0 default default
  have i1 := h1 default
  have i2 := h2 default
  grind only

-- step 10 superposition
theorem inf_s10 : (∀ v0 v1 : ι, («_p» («_f» v0 v1))) →
  (∀ v1 : ι, ((«_f» v1 («_sF0»))=(«_sF1»))) →
  ((«_p» («_sF1»))) := by
  intros h0 h1 
  have i0 := h0 default («_sF0»)
  have i1 := h1 default
  grind only [cases Or]

-- step 11 forward subsumption resolution
theorem inf_s11 : ((«_p» («_sF1»))) →
  ((¬(«_p» («_sF1»)))) →
  False := by
  intros h0 h1 
  have i0 := h0 
  have i1 := h1 
  grind only [cases Or]

theorem fullProof : (∀ v0 v1 : ι,(«_p» («_f» v0 v1))) → (∃ v0 v1 : ι,(«_p» («_f» v1 («_g» v0)))) := by
  intros step1 
  apply Classical.byContradiction; intro step3
  have step4 := inf_s4  step3
  have step5 : (∀ v0 v1 : ι, («_p» («_f» v0 v1))) := by
    try simp only
    prenexify at step1<;>
    ac_nf0<;>
    ac_nf at step1

  have step6 : (∀ v0 v1 : ι, (¬(«_p» («_f» v1 («_g» v0))))) := by
    try simp only
    prenexify at step4<;>
    ac_nf0<;>
    ac_nf at step4

  -- step7 function definition
  let «_sF0» v0:= («_g» v0)
  have step7 : (∀ v0 : ι, ((«_g» v0)=(«_sF0»))) := rfl
  -- step8 function definition
  let «_sF1» v1:= («_f» v1 («_sF0»))
  have step8 : (∀ v1 : ι, ((«_f» v1 («_sF0»))=(«_sF1»))) := rfl
  have step9 := inf_s9  step6 step8 step7
  have step10 := inf_s10  step5 step8
  have step11 := inf_s11  step10 step9
  exact step11

end vamproof
-- ------------------------------
-- Version: Vampire 5.0.1 (Release build, commit a75412b26 on 2026-09-02 00:00:00 +0000)
-- CaDiCaL version: 2.1.3
-- Termination reason: Refutation
-- Time elapsed: 0.001 s
-- Peak memory usage: 6 MB
-- ------------------------------
-- ------------------------------
